### ISSUE TITLE
[Feature]: Special Events

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#1247]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I would like to ask: Is it possible to put in the M3 settings an option to determine if that week there is a special event? Why and what is the idea: In the week of the circuit overseer's visit it is standard that the meeting is on Tuesday, if it is possible in the settings to add the date of the visit, the program would automatically change the meeting to Tuesday, in the week of the assemblies and conventions, the program would not download any media (not so important this option because the program would not be used), and in the week of the Memorial, the program would not download the media of the week or weekend meetings (when the date falls on Saturday or Sunday) and would have the option to add the songs and images for the Memorial talk.

### Describe alternatives you've considered

Actually, I thought of this as improvements or adjustments to M3.

**Comment by sircharlo** [comment]
I see multiple things here:
- Possibility of indicating CO visit week: could be a date picker that allows user to select multiple dates in the present/future, for all known CO visit dates, stored as an array. When one of the dates is in the past, it would be deleted from the array. If one of the dates corresponds to the current week, then the midweek meeting date would be moved to Tuesday for that day automatically.
- Possibility of indicating weeks of assemblies and conventions: not sure this one is really needed, as like you mentioned the app wouldn't be used on those weeks anyways.
- Possibility of indicating date of the Memorial: not sure this one is really needed either, since the app will not download media for a meeting that doesn't exist anyways; it will simply display a notification saying "no media found for XX date", which the user would expect anyways, seeing as he would full well know that it is Memorial. As for having the option to add the songs and images for the Memorial talk, these features are already present, not sure any change would be required per se.

Am I missing anything?

**Comment by mtdvlpr** [comment]
I actually thought about this too! @e-Feitosa beat me to the punch. @sircharlo I think your assessment is spot on! I would however say the date select would only hold one date range at a time (similar to the date picker on the home screen).

**Comment by sircharlo** [comment]
> I actually thought about this too! @e-Feitosa beat me to the punch. @sircharlo I think your assessment is spot on! I would however say the date select would only hold one date range at a time (similar to the date picker on the home screen).

So for example, something like "Next scheduled CO visit"?

**Comment by mtdvlpr** [comment]
Yeah, and clear it if the date is in the past.

**Comment by mtdvlpr** [comment]
> > Yeah, and clear it if the date is in the past.
> 
> Should not be a mandatory field, but it should sync to cong server!

Yes. I think it should not be lockable, but just always sync it with the cong server

**Comment by sircharlo** [comment]
That would be new, synced but not lockable!

**Comment by mtdvlpr** [comment]
Well, we could also just make it lockable, but then you give people the option to not lock it and have it not always synced.

**Comment by e-Feitosa** [comment]
> > Sim, e limpe-o se a data estiver no passado.
> > Não deve ser um campo obrigatório, mas deve sincronizar com o servidor cong!

I really liked the observations. i think the focus would really be on the CO visit. 
___
Also [and going off topic], which of the 4 servers (sync to cong server) do you use in the congregation?

**Comment by mtdvlpr** [comment]
I use koofr which hasn't failed me as of yet.

**Comment by sircharlo** [comment]
At various times we used my own server (hosted at home), and Koofr. Both excellent options.

**Comment by mtdvlpr** [comment]
@sircharlo, on second thought, I think just making it lockable is enough. Theoretically, you only change the value every 6 months. So unlocking it, changing and locking it again every 6 months is not that much effort, I'd say.

**Comment by mtdvlpr** [comment]
Another thought. For the CO visit, we could automatically skip the cbs media

**Comment by sircharlo** [comment]
> Another thought. For the CO visit, we could automatically skip the cbs media and the final song.

Now that's a golden idea..!

**Comment by sircharlo** [comment]
Also, for the WE meeting, the CO chooses the final song, so the 2nd WT song could be ignored as well.

**Comment by mtdvlpr** [comment]
@sircharlo, done and done :)

**Comment by sircharlo** [comment]
Hear me out: would it be a good idea to add a toggle switch ("start/end") to the "last minute song" picker, to be able to add a song either to to the start (default, for public talks) or to the end (for end of CO meetings) of the media list?

**Comment by Chipperchap** [comment]
Since the C.O media is either sent directly to the CoBoE, and / or other items are downloaded via JW.ORG Login, would it be an idea to have a warning / alert that M<sup>3</sup> does not automatically download media for the C.O talks and these need to be imported manually?

**Comment by mtdvlpr** [comment]
@Chipperchap, nice suggestion! We do need some form of explanation now that you mention it. However, I think adding a question mark to the setting, similar to what we've done already for the Zoom scen for example is the way to go for consistency sake.

**Comment by mtdvlpr** [comment]
@sircharlo, will you be the tie breaker? :)

**Comment by sircharlo** [comment]
> @Chipperchap, nice suggestion! We do need some form of explanation now that you mention it. However, I think adding a question mark to the setting, similar to what we've done already for the Zoom scene for example is the way to go for consistency sake. What do you think @sircharlo?

Definitely, tooltip question mark is the way to go

**Comment by mtdvlpr** [comment]
@e-Feitosa, the feature has been finished and will be in the next release :)

**Comment by e-Feitosa** [comment]
> @e-Feitosa, o recurso foi concluído e estará na próxima versão :)

**Your skill is impressive, thank you!**
🤲

**Comment by mtdvlpr** [comment]
We'll close the issue once the new version with this feature has been released :)
