### ISSUE TITLE
[Bug]: Cached file not used, redownloaded every time

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#1262]
### What happened?

When syncing media, some JWPUB files that should be cached and reused are redownloaded every time, which could be costly and take more time.

### To Reproduce

1. Clear cache
2. Download media for week 1 (lff JWPUB downloads)
3. Download media for week 2 (lff JWPUB downloads again!)

### What did you expect to happen?

The JWPUB files should be downloaded only when not already cached. When cached, the cached version should be used, unless a newer version is available online.

### Version

Dev

### What platform are you seeing the problem on?

Windows

### Screenshots

[localhost-1674140286551.log](https://github.com/sircharlo/meeting-media-manager/files/10457886/localhost-1674140286551.log)

https://user-images.githubusercontent.com/1275666/213475631-19cb1610-7be5-4e12-9b5e-97eaabbf61de.mp4

Note in the video, the `it` JWPUB file does not redownload every time, but the `lff` one does.

**Comment by mtdvlpr** [comment]
Hmm, I can't seem to replicate this. Been pushing the fetch button for every week currently selectable, but no duplicate calls...

**Comment by sircharlo** [comment]
Ha :) The problem is with the API.

The [API link](https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?pub=lff&issue=0&fileformat=JWPUB&langwritten=S&output=json) for the Spanish `lff` shows a `filesize` of `130043345`. However, both the `Content-Length` and the resulting file have an actual filesize of `130039103`.

**Comment by sircharlo** [comment]
Which is why JW Library itself also shows the "eternally updating" publication, no matter how many times the update button is clicked:

![image](https://user-images.githubusercontent.com/1275666/213485793-a1950884-b2af-4a04-ab6f-9e087a5e2248.png)
