### ISSUE TITLE
WebDAV with 4shared not working

### ISSUE THREAD

**Issue by stepstra** [sircharlo/meeting-media-manager#1264]
### What happened?

After our problems with Google Drive I tried using 4shared as it offers a free WebDAV service. But I can't get it to work with M3. The folder is recognized on first setup but after switching to homepage trying to update media folders the 4shared folder can't be found by M3 anymore.

### To Reproduce

1. Go to congregation sync
2. Click on web address
3. Do enter login information for 4shared
4. See error "folder cannot be found"

### What did you expect to happen?

M3 should synchronize all media and settings with the specified 4shared folder. (I can map the 4shared folder in windows explorer as a network folder without any problems).

### Version

23.1.1

### What platform are you seeing the problem on?

Windows

**Comment by wifilogo** [comment]
Hi @stepstra.

Our audio/video sisters have been using WebDav with Windows for months without any problems. It works very well.
They are delighted with M3 and the WebDav function. When they arrive at the Kingdom Hall, the media list they have prepared from home is automatically updated when they open M3.

Keep [this](https://sircharlo.github.io/meeting-media-manager/en/#congregation-sync) in mind:
_`Note: Make sure that all congregation sync users input the same folder path; otherwise the sync won't work as expected.`_

Configure the WebDav settings in M3 and don't touch it anymore.
We use a folder called M3 in the root folder of WebDav.
[Add media](https://sircharlo.github.io/meeting-media-manager/en/#manage-media) normally and it should work.

![image](https://user-images.githubusercontent.com/11198837/213635709-7b93ef03-8ec3-482f-b406-92ff6af10b9c.png)

**Comment by Chipperchap** [comment]
One thing that has caught me out a few times is the date format for the folder. I need to remind myself to always check that I have the same format across devices. 

![Screenshot 2023-01-20 at 8 11 32 PM](https://user-images.githubusercontent.com/35364657/213638598-8caadf3e-34cf-450c-a82e-c3649d9d477f.png)

**Comment by mtdvlpr** [comment]
@Chipperchap, the date format is lockable, forcing the same format on all connected devices.

**Comment by mtdvlpr** [comment]
@stepstra, could you try [this test version](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9)? 4shared has been difficult since the beginning, but I improved the logic to prevent an error that has been occurring a lot.

**Comment by Chipperchap** [comment]
> @Chipperchap, the date format is lockable, forcing the same format on all connected devices :)

Yay! I just tried it and it worked!
I was trying to sync with an old laptop that I use for training and no matter what I did it simply would not sync.  It was driving me nuts! (well, more nuts than usual...) 🥴
What I found out was that the MMM folder I had created in my "Documents" folder was actually part of a OneDrive sync folder. I used to use OneDrive with this laptop but don't anymore... so I just deleted OneDrive and all the files I had put in (song and media for the PT this WE and a audio file for another meeting) miraculously appeared!

By the way, I installed the 4Shared Beta on my home PC and the laptop first to see if that would help - but OneDrive was the culprit. 

> Edit: actually, my mistake was having English at home and Dutch at the Kingdom Hall with the localized day in the format, so the media was uploaded to a Wednesday folder instead of Woensdag...

You are blessed to be able to speak two languages - well three if you include the "pure language". 😁

**Comment by stepstra** [comment]
> @stepstra, could you try [this test version](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9)? 4shared has been difficult since the beginning, but I improved the logic to prevent an error that has been occurring a lot.

Thank you, I will test when I get home this evening.

**Comment by stepstra** [comment]
OK. One step further: the error message is gone, but M3 still doesn't upload any media to the selected folder on 4shared.com :-/

**Comment by mtdvlpr** [comment]
@stepstra, could you describe your setup? What folder structure do you have on 4shared? Which folder did you set in M3?

**Comment by stepstra** [comment]
On 4shared it's "/M3", on my local PC it's my "user-folder/documents/M3"
<img width="474" alt="image" src="https://user-images.githubusercontent.com/10519895/213788026-892287c2-de13-4559-b266-efa98287170a.png">

**Comment by mtdvlpr** [comment]
Did M3 create a Media and Hidden folder?

**Comment by stepstra** [comment]
No

**Comment by mtdvlpr** [comment]
I cleaned my 4shared server and created an M3 folder. Added media to the midweek meeting and it was successfully uploaded.

**Comment by mtdvlpr** [comment]
Could you try opening the network tab and see if the call correctly went trough?

**Comment by stepstra** [comment]
This is for next week ...
<img width="415" alt="image" src="https://user-images.githubusercontent.com/10519895/213791256-430a380c-33f2-4681-ab29-724a12ffba02.png">

**Comment by mtdvlpr** [comment]
Could you filter on 4shared using the filter textfield?

**Comment by stepstra** [comment]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/10519895/213791706-fb8f3328-0ff0-4ecf-b6a4-ab2b44746185.png">

**Comment by mtdvlpr** [comment]
It should look like this...
![Screenshot from 2023-01-20 20-42-55](https://user-images.githubusercontent.com/46671786/213791688-00074ebc-650b-4fc8-9b22-e34775ca95ab.png)

**Comment by mtdvlpr** [comment]
Could you go back to settings and press the blue/green connect button (globe icon)? And then show the network tab again

**Comment by stepstra** [comment]
On second try I got this ...
<img width="417" alt="image" src="https://user-images.githubusercontent.com/10519895/213792032-8e20a65a-29da-404d-a193-06fb82c623ec.png">

**Comment by mtdvlpr** [comment]
Did you add a local file to the media before looking at the network tab?

**Comment by stepstra** [comment]
No, I did a media folder update.
BTW: You can come on my machine, if you like ...

**Comment by mtdvlpr** [comment]
Sure. You can reach me at 149895ja@gmail.com

**Comment by mtdvlpr** [comment]
The test version fixed the issue and will be included in the next release :)

**Comment by e-Feitosa** [comment]
I tested the dynamics of the WebDAV server and found it a bit "confusing" for general users to sign up and use. Why am I saying this? I'm testing Koofr's service and I've done the following and it works fine:
1. Installed on PC
2. I created the folders on the PC inside Koofr
3. Similar to Google Drive, syncs well
4. On M3, I put the folder that I'm going to use on KH's PC

https://app.koofr.net/
### On-line [Site]
![image](https://user-images.githubusercontent.com/90984283/215240608-c8fee1d0-a267-4aa4-92b0-b7a51a219f89.png)

### PC KH
![image](https://user-images.githubusercontent.com/90984283/215240765-c5cd1284-7577-43fb-ac0c-f6a92a5c87a7.png)

**_I know that wasn't the idea, but when I download the media here, and the team opens it in KH, the media syncs similar to Google Drive that I mentioned in another post._**

**Comment by mtdvlpr** [comment]
@e-Feitosa you're not supposed to create a local Koofr folder. The local media folder should be a regular folder. JW media won't be uploaded to Koofr, only extra custom media is added to Koofr. Then in the KH, M3 fetches the JW media like normal and the extra custom media from Koofr and places both in the local media folder. Does that make sense to you?

**Comment by mtdvlpr** [comment]
Example:
- all users should be connected to the same webdav server and directory
- Add song 1 for the public talk speaker and 3 images to the weekend meeting through M3
- M3 will upload the song and images to koofr.net/[your directoy]/media/[date of the weekend meeting]/
- In the KH, the JW media is fetched and in Koofr M3 will look for a /[your directory]/media/[date of meeting] folder and if it exists will download everything in that folder and add it to the JW media.

**Comment by e-Feitosa** [comment]
> 



> @e-Feitosa você não deve criar uma pasta Koofr local (se você quiser especificar qual pasta no Koofr usar, use o campo de diretório na configuração de sincronização da congregação). A pasta de mídia local deve ser uma pasta normal. A mídia JW não será carregada no Koofr, apenas a mídia personalizada extra será adicionada ao Koofr. Em seguida, no KH, o M3 busca a mídia JW como normal e a mídia extra personalizada do Koofr e coloca ambas na pasta de mídia local. Isso faz sentido para você?

**Thanks for the clarification, I'll do some more tests.**
