### ISSUE TITLE
[Feature]: Allow more seconds for automatic play stop

### ISSUE THREAD

**Issue by stepstra** [sircharlo/meeting-media-manager#1290]
### Is your feature request related to a problem?

We use a 60s countdown video before the meeting, but it is actually 72 seconds long, because it has a short animation before the countdown starts.

### Describe the solution you'd like

I'd like the slider to allow for max. 90s or possibly enter a custom amount of seconds freely.

### Describe alternatives you've considered

Look at the clock and stop playing manually ;-)

**Comment by mtdvlpr** [comment]
Just making sure I understand: you start your countdown video and the shuffle music simultaneously 72+ seconds before the meeting and want the video and music to stop at the same time?

**Comment by stepstra** [comment]
No, we let the shuffle music run for hair an hour or so until the meeting starts. But for the countdown video we have to stop the music (more or less exactly) 72 seconds before the meeting starts.

And you can't have shuffle music and a video playing simultaneously, can you?

**Comment by mtdvlpr** [comment]
You can play them simultaneously actually (see #858).

**Comment by mtdvlpr** [comment]
Oh, you want to stop the shuffle music so that the video can start?

**Comment by stepstra** [comment]
> You can play them simultaneously actually (see #858).

Thank you, I wasn't aware of this. Then 60s seconds is sufficient!

**Comment by stepstra** [comment]
> Oh, you want to stop the shuffle music so that the video can start?

That was the original plan. Here 60s wouldn't have been enough.
