### ISSUE TITLE
[Bug]: Check for Updates

### ISSUE THREAD

**Issue by Chipperchap** [sircharlo/meeting-media-manager#1318]
### What happened?

When M<sup>3</sup> opens it gives a long list of data why it cannot check for updates as shown below...

![Check_for_Updates](https://user-images.githubusercontent.com/35364657/215250968-a7a3bfc5-ac36-43c7-afb6-3bff18ede53e.png)

### To Reproduce

1. Just open M<sup>3</sup> as usual

### What did you expect to happen?

Updated version to download if one exists...

### Version

v23.1.1

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Not sure if this helps:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 source
5f0f8a8.js:1
Learn more: User-Agent String Reduction
```

### Screenshots

![Error](https://user-images.githubusercontent.com/35364657/215251209-213cfa18-ca7c-4899-b396-88e650cb9b12.png)

### Additional context

I will probably just re-download the program later as it is not a big problem as I don't think there is an updated version ready lately...

**Comment by mtdvlpr** [comment]
Hi @Chipperchap, it seems to be an issue with GitHub and not M3. GitHub returned a HTML page instead of a list of releases. What I will do is remove the lengthy error and put in the console, but besides that, there's nothing to do. Does this happen on every startup or only once?

**Comment by Chipperchap** [comment]
It has been happening all day but when I tested it just now (opened M<sup>3</sup>) it opened without error.  Tried several times and still no error. 
In other words it has come right, is all good, fixed, solved, nothing to see here, move on, close and go and have a cup of tea. 😁

**Comment by mtdvlpr** [comment]
Great! Like I said, GitHub issue, not M3, so they either fixed it or it's something that happens under specific circumstances.
