### ISSUE TITLE
[Docs]: Improve OBS feature documentation

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#1332]
As I mentioned earlier, it's a single point that I notice that some have difficulty setting up OBS Studio.

_Originally posted by @e-Feitosa in https://github.com/sircharlo/meeting-media-manager/discussions/1325#discussioncomment-4812289_

**Comment by mtdvlpr** [comment]
@e-Feitosa, could you provide some more information about what's difficult and how we could improve the documentation site to explain it better?

**Comment by sircharlo** [comment]
Also, we don't want to go into too much details, as setting up OBS Studio is slightly out of te scope of M3. If a brother has issues setting up OBS, who will provide tech support to him and his team if something doesn't work as planned?
