### ISSUE TITLE
[Bug]: WebDAV server not connecting on startup

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#1356]
### What happened?

Can you help me? Only on the PC of a sound operator, the server does not connect automatically, for example, when it opens, the initial screen already shows only the indication of JW media and nothing appears about the media of the congregation (cloud koofr). On other PCs from other brothers, it's normal. I didn't want to format the PC now, I tested a notebook and a PC on the same internet NETWORK, and both have the same problem. If you can detect something with this data, it would help a lot.

### To Reproduce

Acredito que poder um erro no Windows ou na internet, mas, depois de fazer vários testes, tudo funciona, menos o M3

### What did you expect to happen?

Open M3 and it connects normally to the koofr server, currently I need to go to the settings and click on the cloud for it to connect, and if I close M3 and open it, it does not connect automatically.

### Version

v23.1.1

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
{}
```

### Additional context

Windows 11 x64
### Anonymized `prefs.json`
```
[....]
```

**Comment by mtdvlpr** [comment]
@e-Feitosa, do you see a M3 warning that you're not connected to the internet? How many congregation profiles have you made in M3?

**Comment by e-Feitosa** [comment]
The PC is normally connected to the internet and downloads the standard media from JW, the PC just doesn't connect to the server, however, if you open the settings and click on the server's globe icon, then it connects and downloads the media from the server, and if you close the M3 and open again, you have to do the same thing to access the media on the server. On this machine in question, I did several tests, including accessing it remotely, removing all M3, creating a single profile, and testing with other profiles and nothing. I tried to eliminate all possible causes and as I said, it's a Desktop PC and a Notebook in the same place, and both with the same problem. I even downloaded this last test version that you made available here, and nothing makes the m3 connect to the server. If you don't have anything in that history to send, I'll ask the sound operator to format his machine (PC), because it's only on his machines that it doesn't work to connect the server automatically.

**Comment by mtdvlpr** [comment]
@e-Feitosa, alright. Well the only check I do is checking if the device is connected to the internet. And if it is, it tries to connect on startup. I can give you a test version without the check to see if it helps.

**Comment by e-Feitosa** [comment]
There is, another detail, on this machine that is giving this error, I tested it with the 4Shared server and the same problem happens, the media only downloads if you open the settings and click on the globe icon, and then the M3 connects to the server.

**Comment by mtdvlpr** [comment]
@e-Feitosa then it's almost definitely the internet check. Somehow M3's check to see if the device is connected to the internet fails. Could be Windows 11 related, could be his specific device, I'm not sure.

**Comment by e-Feitosa** [comment]
Thank you very much for the help and excellent work, I will check if he can format the machines (PCs), because apparently there is no error on M3 and not on the servers (koofr / 4shared)

**Comment by mtdvlpr** [comment]
@e-Feitosa let me know what happens!

**Comment by e-Feitosa** [comment]
@mtdvlpr, I tested it with another sound operator and had the same problem on his PC (Does not sync as expected), here we have 3 congregations in the same KH and the 3 use the same email on the WebDAV server, only the passwords are different, and we have an account set up for special meetings, is something blocking the M3 not to activate the server automatically (would I have to create a WebDAV account for each congregation?)? _The curious detail is that when you click on the globe, it connects and downloads the media after clearing the cache._

**Comment by e-Feitosa** [comment]
**What is the difference between downloading one of these two files [pc X64]?**

[69.8 MB]
[meeting-media-manager-23.1.1-x64.exe](https://github.com/sircharlo/meeting-media-manager/releases/download/v23.1.1/meeting-media-manager-23.1.1-x64.exe)

[135 MB]
[meeting-media-manager-23.1.1.exe](https://github.com/sircharlo/meeting-media-manager/releases/download/v23.1.1/meeting-media-manager-23.1.1.exe)

**Comment by mtdvlpr** [comment]
@e-Feitosa, curious. Your setup should work. 

As for the difference. The x64 file will install thr x64 version and the other one will either install the x64 or the x32 version, depending on the device, so that shouldn't make a difference (as long as the device and windows version are x64 and not x32). 

I'm currently generating a test version for you.

**Comment by e-Feitosa** [comment]
This message started to appear after I configured the SR's PC with the 3 congregation accounts on the Koofr server and 3 more PCs to send the media using the server. I'm going to test this version you sent now.
![image](https://user-images.githubusercontent.com/90984283/216826618-66252ea5-6348-4c26-84b6-70b890bb07f4.png)

**Comment by mtdvlpr** [comment]
Which file does the warning say is not available?

**Comment by e-Feitosa** [comment]
This warning was appearing in the current version of M3, in the PC of the SR in today's meeting, it happened after I configured the server and "closed" some options in the server settings so that they would not be changed. Today I removed all the options and removed the above mentioned file from the Koofr server and it solved it. Now I installed this version that you sent me, my PC works fine [here I had no problem on this PC], so I'm going to test it on other PCs that don't connect to the server when opening M3 to see if it solves all the problems. And after the tests, I send you a message.

**Comment by e-Feitosa** [comment]
> No momento, estou gerando uma versão de teste para você.
> Deixe-me saber se funciona e o que o console diz!

### **Problem fixed successfully!**
Problem solved with this version you sent. I tested it on all machines that had a problem, including a virtual machine, on all PCs they synchronized correctly.

**Comment by mtdvlpr** [comment]
The fix will be included in the next release :)
