### ISSUE TITLE
[Bug]: Cannot fix 'Zoom scene does not exist' error even after correcting the issue.

### ISSUE THREAD

**Issue by UNiXMIT** [sircharlo/meeting-media-manager#1365]
### What happened?

I was testing the program and originally had a scene created in OBS for Zoom participants. I added that scene in M3 but then a little later removed that scene from OBS. Now M3 complains that "The configured Zoom scene does not exists anymore"
![image](https://user-images.githubusercontent.com/4117073/216823854-e41ebd55-2dc7-4e87-8146-0b1797ea09a9.png)
even though I have removed that Zoom scene now:
![05-02-23-MT-1012](https://user-images.githubusercontent.com/4117073/216823960-82b8ea98-d404-42bd-9c61-710e9017e5b4.gif)

### To Reproduce

1. Add a new scene in OBS.
2. Configure that scene in M3 for Zoom participants.
3. Close M3.
4. Delete that scene in OBS.
5. Open M3 and see the error.

### What did you expect to happen?

I expect to be able to remove a scene in OBS and be able to remove it in M3 without constantly getting an error message.

### Version

v23.1.1

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
{}
```

**Comment by UNiXMIT** [comment]
The workaround is to close M3, manually edit the prefs.json file deleting the value for 'zoomScene' and then start M3 up again. Now the error doesn't appear.

**Comment by mtdvlpr** [comment]
Hi @UNiXMIT, thanks for reporting! Will be fixed in the next release :)

**Comment by UNiXMIT** [comment]
Thanks so much.
