### ISSUE TITLE
[Bug]: Subtitles only appear after app restart

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#1462]
### What happened?

Upon enabling subtitles and fetching media, the CC icon shows up as expected. However, no subtitles are displayed.
After an app restart, all is normal.

### To Reproduce

1. Ensure subtitles are not enabled
2. Restart M3
3. Enable subtitles
4. Fetch media
5. Play video that has subtitles: no subtitles are displayed over the video
6. Restart M3
7. Play the video again: subtitles are now displayed

### What did you expect to happen?

Subtitles should display without an app restart after the setting is toggled.

### Version

v23.02.1

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
None, no errors whatsoever.
```

**Comment by mtdvlpr** [comment]
It's because the media data prop withSubtitles only gets initialized when the media window is initialized...
