### ISSUE TITLE
[Feature]: Improve custom start/end time experience

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#1469]
> We used the feature to play a video (GB Update) from a specific start to a specific end time - very helpful! But the confirm button (the check mark) at first looks like a field where you can set/unset the checkmark, not really like a confirmation button. Maybe you could make this more intuitive?

_Originally posted by @stepstra in https://github.com/sircharlo/meeting-media-manager/issues/1303#issuecomment-1431367130_
   
- [x] add tooltips to action buttons (#1467)
- [x] make time fields easier to fill in (#1475)

**Comment by stepstra** [comment]
Oh, and if I may add: the way to enter the time could be more intuitive either.
Usually, in a field like this, I would double click the minutes, enter two digits and then expect the seconds to be selected automatically so I can overwrite them with two digits as well. At the moments, you need to use the delete key or double click the seconds afterwards.
