### ISSUE TITLE
[Feature]: Auto-start meeting music

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#1473]
### Is your feature request related to a problem?

It would be nice if we could have the option of having the background music (if enabled) start automatically when the app is opened up.

### Describe the solution you'd like

The music should auto-start only if:
- background music is enabled
- a new background music auto-start toggle is enabled
- it is currently a meeting day
- the current time is between [(meeting start time) - (1 hour)] and [(meeting start time) - (music auto fade delay) - (1 minute)]

### Describe alternatives you've considered

Manually starting the music

**Comment by mtdvlpr** [comment]
@sircharlo, yes! One question. You say minus 1 minute. Is that the maximum 1 minute you can select for auto stopping? Does that mean another requirement is that `musicFadeOutType` needs to be set to `smart`?

**Comment by sircharlo** [comment]
> Or is the 1 minute so that music can at least play for one minute and if auto stop is enabled, we should substract that as well?

Yeah, that was my thinking. No use in auto-starting the music if the meeting starts in 3 seconds...

**Comment by mtdvlpr** [comment]
Great! That's how I understood it :)
