### ISSUE TITLE
[Feature]: Drag and Drop Media to Presenter

### ISSUE THREAD

**Issue by danielengels** [sircharlo/meeting-media-manager#1493]
### Is your feature request related to a problem?

Before using mmm, we used Only-M to present the media.
When someone had media to present, we just need to drag and drop media from the explorer to the presenter window and it was added.
Now we had to click on the menu open the media folder and then copy the media from source explorer window to the target and then refresh the mmm.

### Describe the solution you'd like

It would be nice, when I select one or more files in the explorer you can drag the files to the meeting presenter window and drop it there. Would be nice, if you could choose where it should be sorted inside the list and not only added to the end of the list.

### Describe alternatives you've considered

... the way you could add media is also okay, so we don't miss a feature, it would be just a way to handle it more easy.

**Comment by mtdvlpr** [comment]
@danielengels, how often does it happen that media needs to be added while presenting?

**Comment by danielengels** [comment]
Hi @mtdvlpr, depends - but i would guess 3-5 times a month. And most of the time we complete start everything and then we get additional media...
but it is more that the most of us are used to use drag and drop. it is also possible to do about the menu open the explorer and refresh. it is more a convenience feature ;)

**Comment by mtdvlpr** [comment]
@danielengels, alright. I had the assumption that additional media would always be received beforehand. In which case, you can open the manage screen for the given day (click on the day tile from the home screen) and there you have a drag-and-drop feature.

**Comment by danielengels** [comment]
to be honest - that would be really good if this we would do before and we asked for this many times but.... maybe a problem in our congregation. 
In the last meeting we had a change on the program. We don't know about the change and we don't even know that there was a video we should play and we even had to download some media from jw.org because we don't know anything about it.

**Comment by mtdvlpr** [comment]
@danielengels, if it's featured media like the governing body update, check out the manage screen. There's a new JW.org tab which lists featured media from jw.org for immediate download.

**Comment by danielengels** [comment]
it was the media from two weeks ago, when the governing body update was... 
I check a little the manage screen and saw it is also supporting pdf (what i thought m³ doesn't support) and there is the DnD-Support. 
Maybe is it a an easier way to link or open the manager from the presenter-mode without closing it and open it through a icon in the presenter? 
But just an idea - don't know how hard it will be to implement..

**Comment by mtdvlpr** [comment]
I like your suggestion! Definitely going to try it.

**Comment by Chipperchap** [comment]
> it was the media from two weeks ago, when the governing body update was... 

I wonder how many congregations got caught out by that one? I was speaking with a brother from a nearby congregation who mentioned about their interview of children during the 'Become Jehovah's Friend" section of this weeks meeting, and I said that that part had been swapped out due to the GB Update 2023 #1 - but he knew nothing about it. It was not announced via the "S-147" like usual, but rather a "corr_E_20230113" (in this country), as mentioned by @danielengels, the "Jehovah Helps Us Through Trials" part. 
I know we cannot automate everything, nor would we want to, however we do rely on our LMMO paying close attention to any meeting program changes received through correspondence. The A/V overseer & Videoconference Organiser need to work closely with the LMMO to ensure changes are recognized and implemented. 
I do wonder if a journal popup could alert the M<sup>3</sup> operator to meeting media changes, but then it is not really their role, nor would the brothers assigned for the meeting program necessarily have time to adjust and prepare to deliver for the congregation at last minute anyway...!
Thankfully it occurs only rarely.

**Comment by sircharlo** [comment]
> > it was the media from two weeks ago, when the governing body update was...
> 
> I wonder how many congregations got caught out by that one? I was speaking with a brother from a nearby congregation who mentioned about their interview of children during the 'Become Jehovah's Friend" section of this weeks meeting, and I said that that part had been swapped out due to the GB Update 2023 #1 - but he knew nothing about it. It was not announced via the "S-147" like usual, but rather a "corr_E_20230113" (in this country), as mentioned by @danielengels, the "Jehovah Helps Us Through Trials" part. I know we cannot automate everything, nor would we want to, however we do rely on our LMMO paying close attention to any meeting program changes received through correspondence. The A/V overseer & Videoconference Organiser need to work closely with the LMMO to ensure changes are recognized and implemented. I do wonder if a journal popup could alert the M3 operator to meeting media changes, but then it is not really their role, nor would the brothers assigned for the meeting program necessarily have time to adjust and prepare to deliver for the congregation at last minute anyway...! Thankfully it occurs only rarely.

Yeah, I agree this happens from time to time. Reading correspondances is important. 😄 
However, as you said, it's not really the role of the AV operator (who may or may not be an appointed brother, or even a sister) to remind anyone about replaced parts. They might not even be aware of the fact that a part has been replaced. This is the fully the LMMO's responsibility, and by extension the meeting chairman.

We wash our hands of this one 😃
