### ISSUE TITLE
[Bug]: KB-Shortcuts for OBS-Scene-Selection

### ISSUE THREAD

**Issue by danielengels** [sircharlo/meeting-media-manager#1494]
### What happened?

We have in obs a camera, a media and a scene for the prayer to hide the camera while someone do the public prayer.
When you click on the "prayer" scene when a video of a song is displayed the obs scene stays on the media scene.
If you use the shortcut "Alt+2" to change the scene to select the second scene the scene automatically also change to the prayer scene in obs.

### To Reproduce

- Go to prenster window
- Play a song with video (obs scene change to media scene)
- Press Alt+2 Keyboard-Shortcut to change the obs scene

### What did you expect to happen?

If you use the Keyboard-Shortcut it should happen the same like when clicking the scene button - so change the scene after the media is ended or stopped.

### Version

v23.2.1

### What platform are you seeing the problem on?

Windows

### Screenshots

![image](https://user-images.githubusercontent.com/6145739/219499479-1ad5af27-f960-4510-898a-46a69eb45088.png)

**Comment by mtdvlpr** [comment]
Thanks for reporting! It's fixed now and will be in the next release :)

**Comment by danielengels** [comment]
Thanks for the fast fix!

**Comment by mtdvlpr** [comment]
We'll close this issue once it's been released :)

**Comment by e-Feitosa** [comment]
I added here on M3, a **recurring media** with the text of the year to activate when you have the prayer. 
See picture of M3, **00-00 - Display during prayers**.
⬇️
![image](https://user-images.githubusercontent.com/90984283/219984933-75c8d31c-c2d5-4769-b869-275fdf2ccddb.png)

**Comment by danielengels** [comment]
Also a nice way to solve the problem! 
The advantage of the obs scene is, i think, that you can change the scene while the music is playing. So you don't have to stop the music on the end or wait for the credits after the music to show the recurring media...

**Comment by e-Feitosa** [comment]
@mtdvlpr, **Suggestion:** It would be very interesting if one of the following suggestions were possible:
1. After the end of the initial and end song M3 presents the screen of the year at Zoom Meeting automatically, and displays a POP-up Written Stop and by clicking, again displaying the camera image
2. The M3 has an icon, and when clicking, opens / closes the text screen of the year in Zoom.

![image](https://user-images.githubusercontent.com/90984283/220190105-c5703a94-b065-4432-9fb4-2d2288273162.png)

**Comment by sircharlo** [comment]
I don't think this would be useful to the majority of congregations, considering that the instructions state that there is no need to turn the camera on or off during prayers.

**Comment by mtdvlpr** [comment]
@e-Feitosa I agree with @sircharlo. Also, the options stated above (obs scene, recurring media) seem to do the job just fine.

**Comment by danielengels** [comment]
> 2. The M3 has an icon, and when clicking, opens / closes the text screen of the year in Zoom.
This is possible, if you do and extra scene in OBS. See at my Screenshot. The second Button named "Gebet" (Prayer) is the obs scene. In this screen there will be only the year text...

**Comment by e-Feitosa** [comment]
I had made a scene from OBS Studio, but there is a lot of icons because I have other scenes of the camera, so if you had a native M3, because the image is already in M3 and is the same captured by Obs Studio in media, It may not be too difficult to implement, especially if you have to display automatically after the initial prayer and final prayer.

**Comment by e-Feitosa** [comment]
> Eu não acho que isso seria útil para a maioria das congregações, considerando que, de acordo com as instruções, não há necessidade de ligar ou desligar a câmera durante as orações.

I also agree

**Comment by e-Feitosa** [comment]
> @e-Feitosa Concordo com @sircharlo. Além disso, as opções indicadas acima (obs cena, mídia recorrente) parecem fazer o trabalho muito bem.

I also agree
