### ISSUE TITLE
[Feature]: Allow applications on top of media window

### ISSUE THREAD

**Issue by alanfermtz** [sircharlo/meeting-media-manager#1516]
### Is your feature request related to a problem?

Its not really a problem

### Describe the solution you'd like

Thanks for all your effort 
The cherry in the pie of this program is to have a live countdown, like 5 minutes before meeting start

### Describe alternatives you've considered

There is a program that already does this (jmultimedia) but the problem is that the m3 window does not allow to see the jmultimedia window you need to press the hide media button

**Comment by alanfermtz** [comment]
I just see previous request of this. So i understand if this is not going to be develop is there a way to bring to the top any timer application, instead of having to hide the m3 media window?

**Comment by mtdvlpr** [comment]
@alanfermtz, thanks for your suggestion! What we could do is add a toggle in the settings which, when enabled, allows for other applications to go on top of the media window. Would that be sufficient for you?

**Comment by mtdvlpr** [comment]
@alanfermtz, I've got a test version for you. [Here](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9?usp=sharing) it is :)

**Comment by sircharlo** [comment]
Hi there @alanfermtz !
Yes, as @mtdvlpr said, unfortunately, this feature will not be implemented in M3 for the time being, the reason being that instructions state that the following must be done:

- Display the yeartext before the song, after the prayer, and during meeting when no media is being displayed
- Don't combine the yeartext with other artwork, not even artwork from publications.

Therefore, making the screen "always on top" is in accordance with these instructions.
Thanks for your understanding!

**Comment by Chipperchap** [comment]
For what it is worth, we have a "foldback" screen (LDC approved) at the very rear of the K-Hall that shows our timer for all meetings - our brothers love it as only they can see it (audience members would have to turn around to view it). It is run via a second PC that doubles as our ZOOM mute/unmute & attendant. I know some K-Halls do not use a second computer, however we found that one PC doing all the work was very processor intensive and gave us no fall-back in case of emergency. This keeps our timer function independent of what is shown on the main auditorium screens.

**Comment by sircharlo** [comment]
> For what it is worth, we have a "foldback" screen (LDC approved) at the very rear of the K-Hall that shows our timer for all meetings - our brothers love it as only they can see it (audience members would have to turn around to view it). It is run via a second PC that doubles as our ZOOM mute/unmute & attendant. I know some K-Halls do not use a second computer, however we found that one PC doing all the work was very processor intensive and gave us no fall-back in case of emergency. This keeps our timer function independent of what is shown on the main auditorium screens.

I think the requested feature was to allow a "meeting is starting soon" timer to be displayed on the main monitors, which as I mentioned we won't be supporting, unless the instructions are updated at some point. 😃

**Comment by Chipperchap** [comment]
Oops - you are right - I apologise for the hijack. 
I remember being told off once because I wanted to implement what we have at conventions at a local level - we received instructions that conventions are special and not to try and replicate locally so I took that on the chin. 😁🤛

**Comment by sircharlo** [comment]
> Oops - you are right - I apologise for the hijack. I remember being told off once because I wanted to implement what we have at conventions at a local level - we received instructions that conventions are special and not to try and replicate locally so I took that on the chin. 😁🤛

Exactly 😄
