### ISSUE TITLE
[Bug]: Calendar pop-up does not respect local date format

### ISSUE THREAD

**Issue by stepstra** [sircharlo/meeting-media-manager#1523]
### What happened?

I wanted to enter our next CO-visit. The calendar pop-up opens but week always start with sunday instead of monday - which (mondays) would be the local (german) format. Furthermore, mondays are the only option, although the visit weeks start on tuesday (but that maybe intentional, I don't know ...).

### To Reproduce

3. Do '....'

### What did you expect to happen?

M3 should use local date and time.

### Version

23.2.1

### What platform are you seeing the problem on?

Windows

### Screenshots

<img width="302" alt="image" src="https://user-images.githubusercontent.com/10519895/220080467-fb27830d-6bbf-4436-bef8-0a6d219dcdd1.png">

**Comment by mtdvlpr** [comment]
@stepstra, thanks for pointing it out! The next release will let you select only Tuesdays and will respect the locale's start of the week day.
