### ISSUE TITLE
Website as media through file shortcut

### ISSUE THREAD

**Issue by edonadeo** [sircharlo/meeting-media-manager#1587]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

We used in the past the software [OnlyM](https://www.soundboxsoftware.com/only-m). There was the possibilty to show a website through a file-shortcut in the media-folder.
We used it to view the topic of the public speech. Our simple Website was dynamic and shows always the planned topic.
The solution could work like your jw.org Beta Function in M3. Just only view the webbrowser without navigating-features.
This feature could be also usefull for other stuffs and gives more possibilities and flexibilites.

### Describe alternatives you've considered

-

**Comment by mtdvlpr** [comment]
Hi @edonadeo, thanks for reaching out! When first implementing the jw.org feature we considered having that flexibility, but decided against it, since the arguments were about using M3 in the ministry, which is out of scope.

When (before, during, after) do you usually show your dynamic website?

**Comment by edonadeo** [comment]
We used it only during the 30-min public speech on the weekend.
It´s a google spreadsheet and the topic will be updated by a script from our side.
https://docs.google.com/presentation/d/1QHwZaa4otc8H10rg9HfwVPvDgIEi7jaOW-SXv6-_DzM/present?slide=id.p

**Comment by sircharlo** [comment]
> I don't think showing anything other than the yeartext in between media is in line with the guidelines.

I'd tend to agree. The yeartext is supposed to be shown before the first song, after the final prayer, and whenever videos or pictures aren't being shown on the screens during the meeting.

**Comment by edonadeo** [comment]
You are right, regading the yeartext. Therefore the yeartext is also part of the screen. So we are also showing the yeartext always. :-)

> Secondly, showing the website would prevent you from showing media right away. This would therefore not work well together with public talk media.
When M3 could handle/show a Website like a Media-file (png,jpg,...) then it coule be easy to work together with public talk media.
At the moment we convert the the Website to a png to be able to show it.
![image](https://user-images.githubusercontent.com/31246045/225074597-025ca45f-c624-4d0b-9ff9-e6b601372bad.png)
Instead of the picture it´s easier to use the website itself.

But thanks for answering regarding this question. Thanks for your grand work!
