### ISSUE TITLE
[Feature]: Improve Zoom integration

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#1642]
What would it take to make the Zoom integration stable enough to not be a beta feature?

Possible improvements:

- [ ] Fully support M³ as host workflow
- [ ] Prevent automation failing
- [ ] Improve performance

@sircharlo, thoughts?

**Comment by joaochris** [comment]
Want to add a feature to automatically admit from the waiting room?

I tested it here, the integration is great for computers with 4gb (our case), sending the video through the integration itself the quality is very good and there is still memory left (I haven't tested the audio yet)

**Comment by mtdvlpr** [comment]
> Are you planning to add a feature to automatically admit into the waiting room?

It's definitely possible! Altough Iike the idea and would use it myself, we might want to consider the guidelines. The waiting room is a forced setting and automatically admitting is essentially bypassing the waiting room. Maybe a toggle in the presentation mode and force disabling it when the meeting has started. I'm conflicted. @sircharlo, what do you think?

**Comment by mtdvlpr** [comment]
Sorry to resurrect an old thread here, but am I missing something? What is the "issue with using the video of the M³ Zoom participant"?
In my testing, the video of the M³ Zoom participant can be set to the OBS virtual camera, and the microphone can be set to whatever input is normally used by the normal Zoom client (to hear what goes on at KH).

If things are done that way, then the integration could remain a co-host, send itself to waiting room/main meeting as needed, etc., and there would be no need to spotlight the host, but rather "itself", since the AV feed would be coming from the M³ Zoom participant.

I might be missing something though like I said. 

_Originally posted by @sircharlo in https://github.com/sircharlo/meeting-media-manager/discussions/1340#discussioncomment-5302776_

**Comment by mtdvlpr** [comment]
Odd. I still have the same problem...I'm using Windows 10 with the latest Zoom client.

My steps:
1. Startup OBS with virtual camera
2. Startup Zoom Meeting and select any camera but the virtual camera
3. Startup M3 and open presentation mode
4. Select virtual camera in M3
5. See Zoom error
6. Select virtual camera in Zoom
7. See camera in action

**Comment by mtdvlpr** [comment]
@Chipperchap, didn't you also experience this problem? Unable to use any camera as the M3 participant?

**Comment by joaochris** [comment]
I tested it on my computer and on a notebook and I didn't have this problem. What if you open the meeting from the browser?

**Comment by Chipperchap** [comment]
> @Chipperchap, didn't you also experience this problem? Unable to use any camera as the M3 participant?

Correct. I cannot figure out how to get it working for me. I have version V23.3.0

**Comment by mtdvlpr** [comment]
@joaochris @Chipperchap, could you explain your steps in detail and list the operating system you use?

**Comment by joaochris** [comment]
Following the same steps as you, I don't have the error. Windows 10.

**Comment by alanfermtz** [comment]
I see this feature as pretty unstable in terms of real life cases

1. When you exit Play Media, the user leaves the meeting
2. If m3 fails and needs to exit and reopen the program, zoom meeting will fall.

From my perspective It will always be more stable to have the Zoom Desktop instance on the side

**Comment by sircharlo** [comment]
> I see this feature as pretty unstable in terms of real life cases
> 
> 1. When you exit Play Media, the user leaves the meeting
> 2. If m3 fails and needs to exit and reopen the program, zoom meeting will fall.
> 
> From my perspective It will always be more stable to have the Zoom Desktop instance on the side

Yes, hence the _BETA_ label.

**Comment by mtdvlpr** [comment]
Bump

**Comment by mtdvlpr** [comment]
Bump

**Comment by mtdvlpr** [comment]
Bump
