### ISSUE TITLE
Song 19 Missing From Midweek Meeting (March 20-26)

### ISSUE THREAD

**Issue by Tdanforth** [sircharlo/meeting-media-manager#1718]
### What happened?

Song 19 was missing from tonight's Midweek Meeting (March 20-26). Had to use the Add a Song button to get Song 19 for the middle song.

### To Reproduce

This seemed to happen when I installed the latest release version. I went to my M3 on my home PC which was not updated and it was there.

### What did you expect to happen?

Song 19 to be included on the media list for tonight midweek meeting

### Version

v23.3.2

### What platform are you seeing the problem on?

Windows

**Comment by mtdvlpr** [comment]
Hi @Tdanforth, we also experienced this! Altough we didn't update...I'll dive into it.

**Comment by mtdvlpr** [comment]
I found and squashed the bug! It's a rare edge case where the same song (song 19) occurs in both the midweek and weekend meeting of the same week. One would be downloaded and the other ignored. Fix will be in the next release :)

**Comment by mtdvlpr** [comment]
We'll close the issue once the fix had been released
