### ISSUE TITLE
M3 shows no image being shown when it is being displayed on TVs

### ISSUE THREAD

**Issue by Tdanforth** [sircharlo/meeting-media-manager#1725]
### What happened?

This bug has been around for several versions. I can't remember when it first started. I'm just now getting around to reporting it. 

This seems to be a random occurrence that happens from time to time. When I press the play button on M3 to display an image on the TVs, it will display on the TVs but not show a stop button on M3, just the play button. So I have to press the play button again, which repeats displaying the image that is already on the TVs. Then it shows the stop button and then I can stop the image from displaying on the TVs. On the screenshot, it shows no stop button on the image, but the home button is greyed out as if media is being displayed, which it was on the TVs.

### To Reproduce

I really don't know to reproduce this. It seems to just happen at random. I usually will do a restart of M3 and it usually doesn't do it anymore.

### What did you expect to happen?

When the play button is displayed on an image, the stop button should display.

### Version

v23.3.2

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
I can get it from the KH computer if needed.
```

### Screenshots

![image](https://user-images.githubusercontent.com/51468761/227838932-87db04ef-abde-4515-8eb9-efd46a67d34d.png)

**Comment by mtdvlpr** [comment]
@Tdanforth  thanks for reporting it! I'll see if I can reproduce it. What would help me is if you could try to reproduce it yourself and once you do, go to the settings and use the report button in the footer to make another issue report. This one would be automatically filled with your preferences and the relevant logs.

**Comment by Tdanforth** [comment]
> @Tdanforth thanks for reporting it! I'll see if I can reproduce it. What would help me is if you could try to reproduce it yourself and once you do, go to the settings and use the report button in the footer to make another issue report. This one would be automatically filled with your preferences and the relevant logs. You could also copy paste those values here if you prefer.

Will do! I'll try to do that on Thursday.

**Comment by mtdvlpr** [comment]
@Tdanforth I have not been able to reproduce this bug. Were you able to reproduce it again?

**Comment by Tdanforth** [comment]
@mtdvlpr It did not happen last night. I will keep on the look out for it and grab the log when it does.
