### ISSUE TITLE
[Bug]M3: Optional OBS Image Scene Broken

### ISSUE THREAD

**Issue by advenimus** [sircharlo/meeting-media-manager#1728]
### What happened?

There seems to be an issue on both our devices with the latest version of OBS on Windows 11. 

We've created a new picture scene in OBS for use with the  _Optional separate media scene for images_ feature that was recently added. When using this feature, M3 switches to the new scene when displaying images properly, but after selecting the stop option, the scene does not switch back to stage but rather switches back to the Media window scene for some reason.

### To Reproduce

1. Create new OBS picture scene
2. Enable in M3
3. Display a photo
4. Hit stop
5. It doesn't switch back to stage scene but rather media scene

### What did you expect to happen?

Expected the program to switch back to the stage scene (speaker view)

### Version

v23.3.2

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
{}
```

**Comment by mtdvlpr** [comment]
@advenimus which obs-websocket version (v4 or v5) are you using?

**Comment by advenimus** [comment]
@mtdvlpr  I am using v4

**Comment by mtdvlpr** [comment]
Both are fully supported, but v5 comes with a few extra event listeners, one of which we use: `SceneNameChanged`. This means when you change an existing obs scene name while presenting, it will be correctly applied. When using v4, this would break the scene in question.

**Comment by advenimus** [comment]
OKay good to know! Will update to v5 then anyways. 

Thank you so much for your help!

**Comment by mtdvlpr** [comment]
No problem! We'll close this issue when the bug fix has been released :)

**Comment by mtdvlpr** [comment]
A new beta version will be released in about 8 hours. Please test that release to see if it does indeed fix your issue. You can automatically receive beta updates by enabling them in the application configuration settings.

**Comment by mtdvlpr** [comment]
@advenimus, does the latest beta release fix your issue?
