### ISSUE TITLE
[Feature]: Windows Small Resize

### ISSUE THREAD

**Issue by alanfermtz** [sircharlo/meeting-media-manager#1777]
### Is your feature request related to a problem?

Its not a problem. 

We use PowerToys FancyZones with a small monitor. So we have m3, jwl, onlyt and zoom organized to have full visibility all time. 
JwL and zoom programs, dont work very well with small sizes. 

### Describe the solution you'd like

I will to like if you can, to have the possibility to have even smaller size of the program, being able to reduce even more the windows size.

### Describe alternatives you've considered

We use autohotkey to configure sometimes the windows size for jwl but is a workaround that not always run good.

**Comment by mtdvlpr** [comment]
@alanfermtz, I'm curious, what do you use JW Library for? Doesn't M3 cover all your needs?

**Comment by alanfermtz** [comment]
we use it to follow the meeting and corroborate what has m3 during the meeting, although we analyze everything before the meeting, it works for our mental health 😂 and a plan b

**Comment by mtdvlpr** [comment]
@alanfermtz, got it. We can allow a smaller size, but we can't guarantee it's usability for the smaller sizes. Do you want the width, height or both reduced?

**Comment by alanfermtz** [comment]
we only need width

**Comment by mtdvlpr** [comment]
I changed the minimal window width from 670px to 580px. That's the most I can do without breaking the current UI. A major UI revamp is underway, so there the minimal width might change again.
