### ISSUE TITLE
[Bug]: M3 Crashes/Freezes after changing media order, then playing a video or picture.

### ISSUE THREAD

**Issue by Supamav** [sircharlo/meeting-media-manager#1781]
### What happened?

After configuring custom media for a meeting, then using the option to manually sort the order of the media for a meeting (for example adding a song, or video then moving them up or down in the order) then playing the media.  

M3 will grey out all of the play buttons for all media, including the media playing and no longer respond to input.  The media still plays but the buttons to stop playing it are replaced with a greyed out play button only that does not functional.  A forced restart is required to regain control.  If we do not rearrange the media, the behavior does not occur.

This is reproducible on different machines, with both Windows 10 and Windows 11.

### To Reproduce

1. Open M3
2. Click on **'Media Controller Button'** to present media for the meeting date.
3. Click on **'Sort Media items'** on the top right
4. Change the order of any media, picture or video to a different location.  **Save Order** by clicking on **'Sort Media items'** again.
5. Attempt to play any video, the selected video will play however the M3 interface will grey out all media including the video selected.  Removes the stop button with just a greyed out play button that is unresponsive.  All media is unplayable and the M3 application becomes unresponsive without a complete forced exit of the program.

### What did you expect to happen?

Expected behaviour is for the media to be sorted manually according to the meetings needs, then to save the sort order.  Then be able to play any videos normally without the buttons greying out and preventing the need to restart M3 during the meeting.

### Version

V23.4.0

### What platform are you seeing the problem on?

Windows

### Screenshots

Unable to provide screenshots at this time.  Will grab some captures tonight at the meeting.

**Comment by sircharlo** [comment]
I also **cannot** reproduce this at all.

**Comment by sircharlo** [comment]
Video showing bug found in https://github.com/sircharlo/meeting-media-manager/issues/1783#issue-1664854399

**Comment by alanfermtz** [comment]
Note: The bug I uploaded, does not make the m3 unusable, just need another click at play button to fix it.

**Comment by Supamav** [comment]
My apologies for not coming back sooner.  Appreciate all your help very much, look forward to the update.

Thank you!
