### ISSUE TITLE
[Bug]: Zoom integration: Start meeting actions, disable unmute fails

### ISSUE THREAD

**Issue by wifilogo** [sircharlo/meeting-media-manager#1820]
### What happened?

If i click the _Start Zoom meeting_ button, the option disable for participants to unmute themselves fail the first time.
The second time it works fine.

### To Reproduce

1. Click the _Start Zoom meeting_ button
2. Open mics participant

### What did you expect to happen?

If i click the _Start Zoom meeting_ button, the option disable for participants to unmute themselves works the first time.

### Version

v23.4.1

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Windows 11
```

### Screenshots

![M3-Zoom Integration](https://user-images.githubusercontent.com/11198837/236608941-fa445ce6-d31b-4bc8-8459-af825dc91d22.jpg)

### Additional context

https://user-images.githubusercontent.com/11198837/236609270-cccc6576-ff9f-4c9d-9099-5c3df9cf6c38.mp4

**Comment by mtdvlpr** [comment]
Hi @wifilogo, I'm aware of the issue. However, it's not something that can be fixed easily, since we're depending on an external Socket to be available. Zoom's way of providing that Socket is different on each occasion. There's also a timing issue where there is a window between the Socket being available and M3 finding the Socket.

That's partly why the Zoom integration is still a BETA feature and you should always double check every action.

**Comment by wifilogo** [comment]
Ok.
Thanks!

**Comment by makeitso4u** [comment]
Pity this will not be fixed makes the addition of Zoom interaction not worth having , it was a good project up to this point, rest in peace as this is now like any other Kingdom Hall project for assisting with AV.

**Comment by mtdvlpr** [comment]
@makeitso4u, all other Zoom automation actions work cosistently (mic, camera, spotlight, etc.). This might be better fixable in the next major refactor that's upcoming. For now, at least, it's not fixable unfortunately.

**Comment by makeitso4u** [comment]
That's the problem with the big providers API structures sometimes they make life difficult. The hard work is appreciated to all the dev team improve what's there the mute / unmute is not the end of the world ...

**Comment by mtdvlpr** [comment]
Bump
