### ISSUE TITLE
[App][Bug]: <Pausing to Cue Video>

### ISSUE THREAD

**Issue by rosebuddoug** [sircharlo/meeting-media-manager#1835]
### What happened?

During hybrid meetings, our habit has been to play and pause a video in M3, cued, ready to share. Then set up the Zoom share window. When prompted we would click "Play" on M3  and then immediately click "Share" on Zoom. There is a slight delay on M3 which provided a smooth transition on Zoom.

In recent months, maybe as a result of an update (not sure) it has become more difficult to do this. On certain occasions, if the media operator does not click "Pause" IMMEDIATELY when the pause button turns yellow, the media starts playing on the Hall monitors.  (maybe the lead-in time to the video starting to play has recently been reduced a bit)

If you click "Pause" at this point, click on the blue dot, and try to rewind the video to the start (and this is the actual problem) it is as if the mouse will not disengage, as if you have kept your finger on the mouse button. As a result, as you try to restart the video, the mouse continues to drag the video timeline backwards and forwards. This all plays out on the Hall monitors, which is very distracting. (we initially thought the mouse was faulty, but subsequently recreated this on other machines, even using this latest beta version at home)

One way to stop this process is to close the app, and restart.

Another way is to drag the video back to it's start point, and using the mouse, click on the small yellow vertical line at the far left border. (or anywhere on the far left side of the media window) When you drag the video back to the start, the app is waiting for one more mouse click to disengage. One click disengages the mouse and allows you to then click "Play"

![Yellow Bar](https://github.com/sircharlo/meeting-media-manager/assets/132870136/a3dc56f6-4778-4f6e-932b-a81abb77b266)

This behaviour does not occur at any other point in the video timeline. You can pause and move the video to any point. The mouse immediately disengages, and you can click play from that point. The only exception is when you drag the video back to the beginning. 

Currently, as a work around, we have decided to reverse the process. Set up the Zoom share screen first. Hit "Share" on Zoom and only then click "Play" for the M3 video. 

This method could look a bit clunky for the Zoom viewers since it may momentarily throw up the Yeartext just prior to the video starting (depending on how quick the operator is). But we believe this is the only foolproof way to operate at the moment.

This is not an urgent matter, since we can still work around it.

My thought is that it would help to have a fraction more time (even 2 seconds), after the "Pause" button turns yellow, before the video starts playing. From my point of view, this would fix the problem to a large extent. Others may operate differently, and may complain that it takes too long for the video to start playing :-)

Many thanks again for your great work.

Kind regards, Doug

### To Reproduce

3. Do '....'

See above

### What did you expect to happen?

I expected to play and pause the video, cued, ready to share

### Version

v23.4.2-beta.15

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
{}
```

### Additional context

Windows_NT 10.0.19045 x64
### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": false,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": false,
    "autoStartSync": false,
    "betaUpdates": false,
    "congregationName": "Rosebud",
    "customCachePath": null,
    "disableAutoUpdate": false,
    "disableHardwareAcceleration": false,
    "localAppLang": "en",
    "localOutputPath": "***",
    "obs": {
      "enable": false,
      "port": null,
      "password": null,
      "mediaScene": null,
      "imageScene": null,
      "cameraScene": null,
      "zoomScene": null,
      "useV4": false
    },
    "offline": false,
    "outputFolderDateFormat": "YYYY-MM-DD",
    "theme": "system",
    "zoom": {
      "enable": false,
      "name": null,
      "id": null,
      "password": null,
      "spotlight": false,
      "hideComponent": false,
      "autoRename": "***",
      "autoStartMeeting": false,
      "autoStartTime": 1
    }
  },
  "cong": {
    "server": null,
    "port": null,
    "user": null,
    "password": null,
    "dir": null
  },
  "media": {
    "autoPlayFirst": false,
    "autoPlayFirstTime": 5,
    "enableMediaDisplayButton": true,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableSubtitles": false,
    "enableVlcPlaylistCreation": false,
    "excludeLffImages": true,
    "excludeTh": true,
    "hideMediaLogo": false,
    "hideWinAfterMedia": false,
    "includePrinted": false,
    "keepOriginalsAfterConversion": false,
    "lang": "E",
    "langFallback": null,
    "langSubs": null,
    "langUpdatedLast": "2023-05-11T02:13:02.596Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": null,
    "ppForward": null,
    "preferredOutput": "window",
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "autoStartMusic": false,
    "enableMusicButton": true,
    "enableMusicFadeOut": false,
    "coWeek": null,
    "musicFadeOutTime": 5,
    "musicFadeOutType": "smart",
    "musicVolume": 100,
    "mwDay": 2,
    "mwStartTime": "19:00",
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 6,
    "weStartTime": "10:00"
  },
  "__internal__": {
    "migrations": {
      "version": "23.4.2-beta.15"
    }
  }
}
```

**Comment by mtdvlpr** [comment]
Hi @rosebuddoug, thanks for reporting this! I'll look into it. 

Have you considered using the OBS integration? It takes some time to set up, but (in my opinion) greatly simplifies the a/v operators job. Media will automatically be shown/hidden to Zoom through a virtual camera, so no need to use the Zoom share option. You can also extend this integration with camera control to easily switch between stage, speaker, demonstration view.

[See our documentation](https://sircharlo.github.io/meeting-media-manager/en/#present-media) for more information and feel free to ask questions.

**Comment by rosebuddoug** [comment]
Thanks for the tip. I'll certainly look into it. Cheers

**Comment by mtdvlpr** [comment]
@rosebuddoug, I've looked into it and I think it's a bug with the UI package that we use (if it's a bug). It's because your mouse leaves the application while holding the slider. It doesn't know what to do with it anymore. We're working on a refactor that includes the new major version of said UI package, so for now there's nothing I can do, but it might be fixed in the next upcoming major release.

**Comment by rosebuddoug** [comment]
Thanks for the feedback Manoah. As I mentioned, it's not an urgent issue.
Thanks again for your work.

Kind regards, Doug
