### ISSUE TITLE
Circuit Overseer Visit Setting Causes Missing Mid Song and Incorrect Sorting of Media 

### ISSUE THREAD

**Issue by Tdanforth** [sircharlo/meeting-media-manager#1839]
### What happened?

My congregation had the CO visit Tuesday. I used the setting to set the date of the CO visit. When I went into the media controller, I saw that the mid song was missing (song 119). Also, the Are You Prepared for a Disaster? video and it's pictures were in the Apply Yourself To The Field Ministry section instead of the Living as Christians section. I reproduce it on my computer and it did the same as the KH computer.

### To Reproduce

1. Set Next planned visit of circuit overseer to 5-9 
2. Set computer date manually to 5-9
3. Reopen M3
4. Update media folder
5. Go to media controller

### What did you expect to happen?

To have midsong and the media sorted correctly (Are You Prepared for a Disaster?)

### Version

v23.4.1

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
{}
```

### Screenshots

![image](https://github.com/sircharlo/meeting-media-manager/assets/51468761/7f3247ed-5423-4dcc-8269-e16890b51d1a)

### Additional context

Windows_NT 10.0.19043 x64
### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": false,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": false,
    "autoStartSync": false,
    "betaUpdates": true,
    "congregationName": "West Hills",
    "customCachePath": null,
    "disableAutoUpdate": true,
    "disableHardwareAcceleration": false,
    "localAppLang": "en",
    "localOutputPath": "***",
    "obs": {
      "enable": false,
      "port": "4444",
      "password": "***",
      "mediaScene": "Scene 3",
      "cameraScene": "Space",
      "useV4": true,
      "zoomScene": null,
      "imageScene": null
    },
    "offline": false,
    "outputFolderDateFormat": "YYYY-MM-DD",
    "theme": "dark",
    "zoom": {
      "enable": false,
      "name": "Video",
      "id": "***",
      "password": "***",
      "spotlight": true,
      "hideComponent": true,
      "autoRename": "***",
      "autoStartMeeting": true,
      "autoStartTime": 1
    }
  },
  "cong": {
    "server": null,
    "port": null,
    "user": null,
    "password": null,
    "dir": null,
    "enable": false,
    "username": null
  },
  "media": {
    "autoPlayFirst": false,
    "autoPlayFirstTime": 5,
    "enableMediaDisplayButton": true,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableSubtitles": false,
    "enableVlcPlaylistCreation": false,
    "excludeLffImages": true,
    "excludeTh": true,
    "hideMediaLogo": false,
    "hideWinAfterMedia": false,
    "includePrinted": false,
    "keepOriginalsAfterConversion": false,
    "lang": "E",
    "langFallback": null,
    "langSubs": null,
    "langUpdatedLast": "2023-03-24T02:39:59.745Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": null,
    "ppForward": null,
    "preferredOutput": "2779098405",
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "autoStartMusic": false,
    "enableMusicButton": true,
    "enableMusicFadeOut": true,
    "coWeek": "2023-05-09",
    "musicFadeOutTime": 5,
    "musicFadeOutType": "smart",
    "musicVolume": 1,
    "mwDay": 3,
    "mwStartTime": "07:30",
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 6,
    "weStartTime": "10:00"
  },
  "__internal__": {
    "migrations": {
      "version": "23.4.1"
    }
  }
}
```

**Comment by sircharlo** [comment]
Adressed [here](https://github.com/mtdvlpr/meeting-media-manager/commit/73ca666e76be44cb1b3a545af9c86bfeac3c7d65). It has to do with the fact that the last song wasn't from the usual _sjjm_ series, as per usual. 

Won't happen in the future, as now we identify the last song without checking if it's from _sjjm_. The fix will be released along with the upcoming refactor.
