### ISSUE TITLE
[Feature]: Option to exclude Watchtower study videos located in footnotes

### ISSUE THREAD

**Issue by Tdanforth** [sircharlo/meeting-media-manager#1908]
### Is your feature request related to a problem?

In today's Watchtower study, there were 5 different videos in the media list from the footnotes (plus 2 more that were duplicate). These videos are not played. It's always possible in the future that a video is directed to be played (like that one time years ago).

### Describe the solution you'd like

A option to exclude the Watchtower study footnote videos. That way the media list is cleared up and the actual media to be played/shown is clearly identified.

### Describe alternatives you've considered

None

### Additional context

![image](https://github.com/sircharlo/meeting-media-manager/assets/51468761/92948619-a7a7-4dba-83da-5cebb310cc63)

**Comment by sircharlo** [comment]
Sort of related: https://github.com/sircharlo/meeting-media-manager/commit/8d8b5d9f604b3fa7a100073b8d3fe0646dcd31b2#commitcomment-117850754

**Comment by sircharlo** [comment]
> Yeah it was confusing
> 
> off topic but kind of related
> 
> I don't know if I have already commented on this, but from a computer security perspective, it is always better to have a white list of things, in the case of the current options, a black list is used. Example:
> 
> ![imagen](https://user-images.githubusercontent.com/43801184/246891084-31808598-d989-4351-a9f5-839cc5ebe790.png)
> 
> question for everyone: wouldn't it be better to change this to an include instead of exclude?
> 
> We have the options as in the image and I don't know if we are missing something or doing something wrong, in the sense that we don't really use those options.

The thinking is, by default, M³ shows pretty much the same media as JWL:

![image](https://github.com/sircharlo/meeting-media-manager/assets/1275666/cce1706b-bda6-4fee-bd25-4aea2a2e8732)

(Notice that the _th_ brochure is there.)

---

The option is there, but since this deviates from what might be considered standard (or "normal/expected") behavior, it's an "exclude" option rather than an "include".

**Comment by alanfermtz** [comment]
Oh I understand now the logic about that.
But by that logic, why you do not include all the videos and images for Enjoy Life of the entire chapter?

**Comment by sircharlo** [comment]
Hm. I suppose I could add an "exclude media that will not be considered during the meeting" toggle (to be rephrased 😄) that, when enabled, would enable the same behavior as M³ currently has (only include 'relevant' media), and when disabled would have the same behavior as JWL (include all media from the chapter, no matter if that part will be studied or not.)

**Comment by alanfermtz** [comment]
Not really interested in that, im just really curious about how work things haha sorry if i sound rude. The way it works now its perfect (btw i support the idea to exclude the footnotes)

**Comment by sircharlo** [comment]
> Not really interested in that, im just really curious about how work things haha sorry if i sound rude. 

You don't sound rude :)

---

> The way it works now its perfect (btw i support the idea to exclude the footnotes)

Yeah, this is what it's going to look like in the future:

![image](https://github.com/sircharlo/meeting-media-manager/assets/1275666/c00c32e0-c2b5-4e0f-a3ee-f6398620892f)

We'll perhaps add a toggle in the future to show/hide media that isn't referenced in a paragraph (ie, in the footnotes).
