### ISSUE TITLE
[Feature]: Support for M4V video file playback

### ISSUE THREAD

**Issue by vangquan** [sircharlo/meeting-media-manager#1935]
### Is your feature request related to a problem?

Yes, the current problem is that the Meeting Media Manager app does not support the playback of M4V video files. This limitation restricts accessibility for users who rely on content provided in this format.

### Describe the solution you'd like

The ideal solution would be the addition of support for M4V video files within the Meeting Media Manager app. This would enable users to play important resources such as the American Sign Language (ASL) versions of various books and brochures, which are currently provided in the M4V format.

### Describe alternatives you've considered

An alternative solution could be converting the M4V video files to a format currently supported by the Meeting Media Manager app. However, this would involve an additional conversion step for the user and may potentially compromise the quality of the content.

### Additional context

The importance of this feature is highlighted by the fact that the ASL versions of Genesis, Deuteronomy, Daniel, and 1 Corinthians, as well as the 'igw' brochure, are all provided as M4V files. The links to these resources are as follows:

[Genesis, Deuteronomy, Daniel, 1 Corinthians](https://www.jw.org/finder?wtlocale=ASL&pub=nwt&srcid=share)
['igw' brochure](https://www.jw.org/finder?wtlocale=ASL&pub=igw&srcid=share)
The addition of M4V support would significantly enhance the app's accessibility and usability for ASL content consumers.

**Comment by mtdvlpr** [comment]
Hi @vangquan, sorry about that! I've created the fix and it will be in the next release. I can make a beta release for you to test. To automatically receive this bete release, go to settings and turn on the 'enable beta updates [...]' option. Look out for `v23.5.1-beta.1`.

**Comment by vangquan** [comment]
Thank you so much!
