### ISSUE TITLE
[Feature]: Import/Export JW Library Playlists

### ISSUE THREAD

**Issue by vangquan** [sircharlo/meeting-media-manager#2003]
### Is your feature request related to a problem?

No, the feature request is not related to a problem but rather an enhancement to improve the functionality and interoperability of Meeting Media Manager with JW Library's new Playlist feature.

### Describe the solution you'd like

With the release of JW Library 14, a new feature known as Playlists has been introduced. Each playlist, which can contain images and videos, can be exported as a .jwlplaylist file. I propose we add a feature to import .jwlplaylist files into Meeting Media Manager. Additionally, I suggest implementing a corresponding feature that allows the export of Meeting Media Manager content to .jwlplaylist files.

### Describe alternatives you've considered

As an alternative, we could consider building a separate tool to convert between .jwlplaylist files and Meeting Media Manager files, but integrating this feature directly into Meeting Media Manager would provide a more seamless user experience.

### Additional context

The playlist feature in JW Library 14 seems to be designed with broad utility across different Kingdom Halls/Assembly Halls in mind. Incorporating the ability to import/export .jwlplaylist files into Meeting Media Manager could significantly enhance the flexibility and interoperability of our media management.

**Comment by mtdvlpr** [comment]
Hi @vangquan, I agree! We'll definitely look into this. Any help with figuring out how to read a `.jwlplaylist` is welcome.

**Comment by sircharlo** [comment]
> Hi @vangquan, I agree! We'll definitely look into this. Any help with figuring out how to read a `.jwlplaylist` is welcome.

Nothing complicated; it's essentially a zip file. Contents include a database and any pictures. Videos are referenced in the database so they can be downloaded by API on each client.

**Comment by mtdvlpr** [comment]
> Nothing complicated; it's essentially a zip file. Contents include a database and any pictures. Videos are referenced in the database so they can be downloaded by API on each client.

Oh, so just like a jwpub file, then. Could've known...

**Comment by mtdvlpr** [comment]
@sircharlo, do you also happen to know already how we could export to a playlist file?

**Comment by sircharlo** [comment]
> @sircharlo, do you also happen to know already how we could export to a playlist file?

We would just have to create a database based on the contents of the media list. Doesn't seem to be too complicated to reverse-engineer. I'm just wondering when an export from M³ would be useful...

I can see an import feature being useful, definitely. But export? What scenarios would that be used for?

**Comment by mtdvlpr** [comment]
> I can see an import feature being useful, definitely. But export? What scenarios would that be used for?

That would be for the scenario where M3 is only used to fetch media and maybe sync media between brothers, but JW Library is used during meetings. Same as the export to VLC I'd say.

**Comment by sircharlo** [comment]
> That would be for the scenario where M3 is only used to fetch media and maybe sync media between brothers, but JW Library is used during meetings. Same scenario as for the export to VLC I'd say.

Hm. Seeing as the main use of M³ is for media playback at the Kingdom Hall, I feel that the import feature should be prioritized over export. I foresee visiting speakers using this feature extensively.

**Comment by mtdvlpr** [comment]
@sircharlo, definitely! Import is a must, export is a nice to have.
