### ISSUE TITLE
[Feature]: Button for Media in Public Talks

### ISSUE THREAD

**Issue by danielengels** [sircharlo/meeting-media-manager#2051]
### Is your feature request related to a problem?

There is a jwpub with all the pictures for the public talks. It is in our JW Libary but many of us forget where we safe the original jwpub that we can use in mmm.

### Describe the solution you'd like

A button next to the "music +" button, where the jwpub for the public talk is saved and when you click you get the selection for the public talks and can add the pictures to the media. Like the Music-Button

### Describe alternatives you've considered

not sure. Maybe some other way to supply the jwpub with the public talks.

**Comment by mtdvlpr** [comment]
Hi @danielengels, the JWPUB file you are referring to is not publicly available, and therefore, we can't make it publicly available in M3. That's why you have to supply the JWPUB yourself, which can then be read and the images can be extracted.

**Comment by danielengels** [comment]
Hi @mtdvlpr, 
yeah, i dont want, that mmm download it. But it would be nice, to have a setting, where I can save the file inside mmm and then everyone can use it again on the computer. Because they always dont know where to find the jwpup even if we safe it on the computer extra for this.

**Comment by e-Feitosa** [comment]
@mtdvlpr, would it be possible in the settings to indicate in which folder (path) on the PC the JWPUB files would be located and by clicking to add a JWPUB the M3 would open that folder (path) first? Similar to what we do in settings (CDP) to configure the media folder / cache folder. Of course, if that's possible, it would be something optional.

**Comment by sircharlo** [comment]
> Hi @mtdvlpr, yeah, i dont want, that mmm download it. But it would be nice, to have a setting, where I can save the file inside mmm and then everyone can use it again on the computer. Because they always dont know where to find the jwpup even if we safe it on the computer extra for this.

Perhaps a menu item could show up if the public talk media playlist JWPUB has previously been imported; that would mean saving JWPUB files in the cache before loading media from them. 

I'm not against that, actually I kind of like the idea.

Possible media types would be:
- **Kingdom Song**
- **S-34mp** (would appear only if it has been previously imported by the user)
- **Publication**
- **Video from JW.org**

If **Publication** is chosen, there could be two options:
- Downloaded publications (to allow getting media from already cached publications)
- Publications from JW.org (choosing a publication from here would download and cache it automatically)

**Comment by sircharlo** [comment]
> @mtdvlpr, would it be possible in the settings to indicate in which folder (path) on the PC the JWPUB files would be located and by clicking to add a JWPUB the M3 would open that folder (path) first? Similar to what we do in settings (CDP) to configure the media folder / cache folder. Of course, if that's possible, it would be something optional.

I don't see any benefit from this. I'd prefer going the GUI way, as described in my above comment.

**Comment by danielengels** [comment]
I was also thinking about maybe an alternative way. As you now can create playlists now from jw libary now. 
@sircharlo I am not sure what it should look like? You mean something like the jw.org-video tab? But even if i could not imagine now how it could look like, sounds like a good idea way to make it easier for a lot of persons.

**Comment by e-Feitosa** [comment]
> > Hi @mtdvlpr, yeah, i dont want, that mmm download it. But it would be nice, to have a setting, where I can save the file inside mmm and then everyone can use it again on the computer. Because they always dont know where to find the jwpup even if we safe it on the computer extra for this.
> 
> Perhaps a menu item could show up if the public talk media playlist JWPUB has previously been imported; that would mean saving JWPUB files in the cache before loading media from them.
> 
> I'm not against that, actually I kind of like the idea.
> 
> Possible media types would be:
> 
> * **Kingdom Song**
> * **S-34mp** (would appear only if it has been previously imported by the user)
> * **Publication**
> * **Video from JW.org**
> * **Media from this computer**
> 
> If **Publication** is chosen, there could be two options:
> 
> * Downloaded publications (to allow getting media from already cached publications)
> * Publications from JW.org (choosing a publication from here would download and cache it automatically)


**Your idea is brilliant, nothing like talking to someone who understands the subject.**

**Comment by mtdvlpr** [comment]
@sircharlo, I would put this enhancement on the list for the refactor, since it's not urgent. What do you think?
