### ISSUE TITLE
[Feature]: Enhancement for optional media scene

### ISSUE THREAD

**Issue by danielengels** [sircharlo/meeting-media-manager#2052]
### Is your feature request related to a problem?

We now have the in germany suggested PTZ camera in our kingdom hall. 
So I tried the optional media scene for pictures. 
I really like the idea that you have both, the video of the camera and the picture. But not always. Something it would be good to show first a Fullscreen-Image and then change to the picture in picture image.

### Describe the solution you'd like

It would be nice to be able to have multiple media scenes, where you can choose from, like you could choose which scene you want to have for normal camera view.
At the moment, I can choose through the normal OBS scenes where the camera should be pointed to and the scene change will cause a change of the cameras ptz position.
I think it could be nice, to have multiple media scence for pictures like the scenes for the camera to descide if i want to have the media in fullscreen or different placed picture in picture media scenes.

### Describe alternatives you've considered

I create an aditional media-scene for the picture in picture scene. I dont select this scene as the special media scene for pictures. When I share a picture in fullscreen, i first choose the other media scene with pip in obs. Then I press the button next to the stop button to hide the media in zoom. Then the picture in picture scene will shown in obs.

### Additional context

It is just an idea to imporve the handling - to be honest. I am not even sure, if we should switch so many times between scenes - at the moment it seems to be nice to could do this but I am not sure, if it is worth doing.

**Comment by mtdvlpr** [comment]
@danielengels, I see your point, but I'm afraid that if we were to implement this (media scene selector besides camera scene selector) it would overcomplicate things significantly without a big improvement. @sircharlo, what do you think?

**Comment by sircharlo** [comment]
> @danielengels, I see your point, but I'm afraid that if we were to implement this (media scene selector besides camera scene selector) it would overcomplicate things significantly without a big improvement. @sircharlo, what do you think?

I agree. @danielengels has a good and functional workaround for power users, but I feel as if simpler is better in this case. 🙂
