### ISSUE TITLE
[Bug]: Drag and Drop for jwlplaylist not working

### ISSUE THREAD

**Issue by danielengels** [sircharlo/meeting-media-manager#2059]
### What happened?

You can't import a jwlplaylist with drag and drop in the mange media option

### To Reproduce

1. Go to "manage media" view from presentation-mode or from main view 
2. Drag and drop a jwlplaylist file
3. The files inside the media will now show up only the jwlplaylist appear on the list

### What did you expect to happen?

if you d&d a jwlplaylist it should do the same like you click on the jwlplaylist-tab and choose the file from the file picker.

### Version

v23.6.1

### What platform are you seeing the problem on?

Windows

**Comment by sircharlo** [comment]
Yes, you're right!

**Comment by mtdvlpr** [comment]
Fixed and will be in the next release :)
