### ISSUE TITLE
Visit week

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#2092]
### What happened?

When he puts the date of the superintendent's visit in M3, he excludes the media that will not be used etc, but the media that are recurring he also excludes, that is, I use 3 recurring media, and when I added the date of the visit, M3 deleted recurring media

### To Reproduce

If you use a recurring average, add the date of the sc visit, see that the recurring averages are not downloaded during the week or on the weekend

### What did you expect to happen?

Make recurring media available

### Version

v23.6.2 beta 4

### What platform are you seeing the problem on?

Windows

____
2)
Taking advantage of this issue of recurring media, I see that when I add a recurring average, m3 creates a folder with the media for every day of the week, the question is, would it be possible for m3 to create only the two folders referring to the two meetings (kind of weekdays and weekends)?

**Comment by alanfermtz** [comment]
Curiosity: What recurring media do you use?

**Comment by e-Feitosa** [comment]
We use a ¹stopwatch and the ²year text display
