### ISSUE TITLE
[Bug]: Changing OBS scene while sharing picture

### ISSUE THREAD

**Issue by danielengels** [sircharlo/meeting-media-manager#2093]
### What happened?

There is the button to share a picture in the kingdom hall, but don't share it in zoom:
![WhatsApp Bild 2023-08-10 um 19 17 12](https://github.com/sircharlo/meeting-media-manager/assets/6145739/e3e2d608-c98f-40fc-bc3d-3445e9a489e7)
When you change the zoom scene before pressing this button, the scene will change - what is good. But then it is not possible to change the obs scene again, even if the picture is not shown in zoom.

### To Reproduce

1. Show a picture
2. Press the "hide/show in zoom"-button
3. Change the obs scene in mmm

### What did you expect to happen?

When the hide in zoom status is active, you should be able to change the obs scene like when you would not share media in mmm.

### Version

v23.6.1

### What platform are you seeing the problem on?

Windows

### Additional context

Why this could be a bug or interesting to fix: Maybe you remember my last feature request for more detailed scene picture selection, to choose if you want a picture in picture or a full screen picture.
When you change the picture in picture scene before you press the show/hide in zoom button everything is okay, but when you forget this you can't change the obs in mmm anymore.

**Comment by alanfermtz** [comment]
i dont understand what is wrong or what are you trying to said, can you detail more or a video?
