### ISSUE TITLE
[Bug]: Incomplete retrieval of media for week of August 21, 2023

### ISSUE THREAD

**Issue by skimark1** [sircharlo/meeting-media-manager#2107]
### What happened?

I tried to pull media for the week beginning 8/21 and for some reason, the CBS media and the final song were not extracted and also the final song for next weekends WT study wasn't extracted either. I've never seen this before.

### To Reproduce

3. Do '....'
Pull media for the upcoming week

### What did you expect to happen?

All media should show up

### Version

23.6.1 (23.6.1)

### What platform are you seeing the problem on?

MacOS

### Screenshots

<img width="1702" alt="Screenshot 2023-08-19 at 8 46 47 AM" src="https://github.com/sircharlo/meeting-media-manager/assets/128306908/86bbcc4b-8081-43b2-a0a2-171e6f4bf436">

**Comment by mtdvlpr** [comment]
Hi @skimark1, could you check settings > meeting setup > CO week? When setting the week that the Circuit Overseer visits, that week will skip cbs media and the last song automatically.

**Comment by skimark1** [comment]
Hello,

Wow, don’t remember setting that up! That makes total sense. Thanks for all you do & for a wonderfully helpful piece of software. Sorry for crying wolf. Should I delete the post?

Thanks,
Mark Cillis
***@***.***

**Comment by sircharlo** [comment]
> Hello, Wow, don’t remember setting that up! That makes total sense. Thanks for all you do & for a wonderfully helpful piece of software. Sorry for crying wolf. Should I delete the post? Thanks, Mark Cillis ***@***.***
> […](#)

Not necessary :) we'll just close it!

**Comment by skimark1** [comment]
Thanks,
Mark Cillis
***@***.***
