### ISSUE TITLE
Stop button not working

### ISSUE THREAD

**Issue by TheTiger72** [sircharlo/meeting-media-manager#2127]
### What happened?

Hello, there's a bug in the latest version (23.8.1).
When an image is projected, the button to stop the image projection appears and then disappears, so it's impossible to stop the image projection and you have to either press Alt + Z or restart M3.
Thanks

### To Reproduce

Launch M3 in last version 
Start a picture

### What did you expect to happen?

Stop the picture

### Version

23.8.1

### What platform are you seeing the problem on?

Windows

**Comment by sircharlo** [comment]
Would you have a screenshot of this issue?

**Comment by TheTiger72** [comment]
> Would you have a screenshot of this issue?

No, but to put it simply, when I launch an image, the stop button only appears for 2 seconds, then disappears, and it's impossible to remove the image.

**Comment by sircharlo** [comment]
Is the setting to convert all files to MP4 enabled by any chance?

**Comment by TheTiger72** [comment]
Yes, the parameter is activated, but I didn't have this problem in the old version. So I reinstalled the old version while waiting for a fix.

**Comment by sircharlo** [comment]
> Yes, the parameter is activated, but I didn't have this problem in the old version. So I reinstalled the old version while waiting for a fix.

Is this for use at a KH?

**Comment by TheTiger72** [comment]
> > Yes, the parameter is activated, but I didn't have this problem in the old version. So I reinstalled the old version while waiting for a fix.
> 
> 
> 
> Is this for use at a KH?

Yes

**Comment by sircharlo** [comment]
> > > Yes, the parameter is activated, but I didn't have this problem in the old version. So I reinstalled the old version while waiting for a fix.
> > 
> > 
> > Is this for use at a KH?
> 
> Yes

That setting is not officially supported for use at KH. 😄 
There is no planned use case for that setting, except for when meetings are 100% remote.

**Comment by TheTiger72** [comment]
> > > > Yes, the parameter is activated, but I didn't have this problem in the old version. So I reinstalled the old version while waiting for a fix.
> 
> > > 
> 
> > > 
> 
> > > Is this for use at a KH?
> 
> > 
> 
> > Yes
> 
> 
> 
> That setting is not officially supported for use at KH. 😄 
> 
> There is no planned use case for that setting, except for when meetings are 100% remote.

Oh right, I didn't know, I'll disable it and see if it works.

**Comment by TheTiger72** [comment]
I just tested it and it works again! Thanks

**Comment by sircharlo** [comment]
> I just tested it and it works again! Thanks

Beautiful!
