### ISSUE TITLE
[Feature]: Add Volume Boost Slider

### ISSUE THREAD

**Issue by alanfermtz** [sircharlo/meeting-media-manager#2141]
### Is your feature request related to a problem?

It will be nice to add a feature that we can add some kind of boost to the audio?
Like the most of players out there have

I need to make some testing and I will be posting here, but I have a sensation that Jw library app has more volume boost than m3

Off topic: which player are you using to play videos?

### Describe the solution you'd like

An advanced feature of audio boost

### Describe alternatives you've considered

n/a

**Comment by alanfermtz** [comment]
I think the real problem may be our uca 222, that send low volume, we install equalizer apo to increase db gain and works for us
You can close this, thanks anyways

**Comment by sircharlo** [comment]
Perfect! Good news 😉
