### ISSUE TITLE
[Bug]: <Microphone Permission on macOS Sonoma>

### ISSUE THREAD

**Issue by SquareCircle99** [sircharlo/meeting-media-manager#2178]
### What happened?

Hello all again!
I'm actually not certain if this bug is the fault of macOS itself or if it has to do with M3, but I figured I'd ask.
Whenever we play a piece of media that has audio on M3 and then share the screen through Zoom, macOS will display a popup stating "Meeting Media Manager would like to access your microphone."
![IMG-20231003-WA0005](https://github.com/sircharlo/meeting-media-manager/assets/111548982/33688263-1cdf-4ee6-a885-de610757f6fc)
We click OK but the popup keeps coming back every time we share something despite the fact that the application has already been whitelisted as can be seen on the picture
![PXL_20231004_230034181](https://github.com/sircharlo/meeting-media-manager/assets/111548982/01d17538-1077-4695-8c40-15bf0be98796)
I tested the same scenario (sharing a piece of media with audio through Zoom) with JWL instead of M3 and the popup never appeared. 
To makes matters a little more bothersome, the popup prevents media playback until it has been dismissed; which requires clicking "OK" several times for some reason.
Any ideas would be greatly appreciated!

### To Reproduce

1. Play a piece of media that has audio (video, song, etc) on M3
2. Share the screen through Zoom, click "share audio" checkbox

### What did you expect to happen?

For the popup to not appear.

### Version

v23.8.1

### What platform are you seeing the problem on?

MacOS

**Comment by mtdvlpr** [comment]
Hi @SquareCircle99, that's a weird one! I'm also not sure who's to blame for this.

**Comment by mtdvlpr** [comment]
This might be related: https://github.com/jitsi/jitsi-meet-electron/issues/611

**Comment by mtdvlpr** [comment]
Or this one: https://stackoverflow.com/questions/60736250/mac-application-asking-for-accessibility-permission-repeatedly

**Comment by sircharlo** [comment]
So in other words, try this:
- quit M³
- remove the microphone permission completely
- relaunch M³

If that doesn't fix the issue, try this:
- open Terminal
- run the following command: `codesign --force --deep --sign - /Applications/Meeting Media Manager.app` (make sure to use the correct path)

**Comment by SquareCircle99** [comment]
Thanks guys!


> So in other words, try this:
> 
>     * quit M³
> 
>     * remove the microphone permission completely
> 
>     * relaunch M³
> 
> 
> If that doesn't fix the issue, try this:
> 
>     * open Terminal
> 
>     * run the following command: `codesign --force --deep --sign - /Applications/Meeting Media Manager.app` (make sure to use the correct path)

I'll give this a shot and report back.

**Comment by SquareCircle99** [comment]
Forcing things via the Terminal worked!! The popup only came up once and then disappeared for good as it's supposed to. 
In order to get the command to work however I actually had to rename M3 to something else as running it as "Meeting Media Manager.app" kept giving me the "no such file in directory" error message.

**Comment by sircharlo** [comment]
I wonder if this is only an issue with Sonoma 🤔 If so, it might be worth it to add a note to the installation docs.

**Comment by sircharlo** [comment]
Docs updated.

**Comment by heymenshan** [comment]
The terminal command solved my issue. Thanks!
