### ISSUE TITLE
Warning Unable to fetch media for the following publication: 1_0

### ISSUE THREAD

**Issue by iiasceri** [sircharlo/meeting-media-manager#2179]
### What happened?

<img width="359" alt="Screenshot 2023-10-07 at 08 53 18" src="https://github.com/sircharlo/meeting-media-manager/assets/34134411/0a0b477e-b3f3-43f7-a979-8dd95d2264da">

### To Reproduce

Use romanian language tuesday 6PM saturday 6PM and try to do download it on macOS if you have a mac and you might get same warning I think it's watchtower missing because I see .title file after WT name.

### What did you expect to happen?

.

### Version

latest

### What platform are you seeing the problem on?

MacOS

### Relevant log output

```shell
❯ /Applications/Meeting\ Media\ Manager.app/Contents/MacOS/Meeting\ Media\ Manager ; exit;
2023-10-07 08:53:45.788 Meeting Media Manager[18887:992777] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Checking for update
Update for version 23.8.1 is not available (latest version: 23.8.1, downgrade is disallowed).
```

**Comment by sircharlo** [comment]
Thanks for reporting this! Fixed [here](https://github.com/sircharlo/meeting-media-manager/commit/571de1ef4883d261568875966afd09611e6a72d1), and will be released in next version. 

It has to do with the media referenced in the footnote. It isn't really critical however, since that media is not played at the meeting.

**Comment by iiasceri** [comment]
Yes you are right I see, MepsDocumentId

**Comment by iiasceri** [comment]
By the way since you are dev and JW checkout my modified JW library app it allows you to close an image with back gesture (btn), and it is modified to my liking but if you want to have a look, look at it
