### ISSUE TITLE
[Bug]: Sort order isn't retained after exiting and returning to presentation mode

### ISSUE THREAD

**Issue by boscolod** [sircharlo/meeting-media-manager#2238]
### What happened?

Issue with saving sorting in presenter mode.

I'm not sure whether this is functioning as designed or whether this is potentially of a feature request. 

### To Reproduce

1. added a new media file and then go into present mode.
2. In present mode I sort the media so that the video is in the correct spot. 
3. I then hit the 'save order' button 
4. i exit presenter mode 
5. Return to presenter mode and then return, all my sorting reverts back to original.

### What did you expect to happen?

I would expect that once i save the order in particular the position for media i have added should be persistant

### Version

v23.10.0

### What platform are you seeing the problem on?

Windows

**Comment by mtdvlpr** [comment]
Bump

**Comment by mtdvlpr** [comment]
Hi @boscolod, this is working as intended. Persisting the sorting order would be a feature request which we probably will implement in the next major update.

**Comment by boscolod** [comment]
Thank you. Looking forward to the next release.
You guys do a great job, thank you.
👍

Regards,
David Boscolo
