### ISSUE TITLE
[Bug]: JWLPlaylist not importing a image

### ISSUE THREAD

**Issue by alanfermtz** [sircharlo/meeting-media-manager#2284]
### What happened?

Using the provided jwlplaylist, the 2nd image does not show up in the presentation mode

### To Reproduce

Use this jwlplaylist
[S-34_9.zip](https://github.com/sircharlo/meeting-media-manager/files/13493981/S-34_9.zip)

### What did you expect to happen?

To extract the 3 images

### Version

23.11.0

### What platform are you seeing the problem on?

Windows

**Comment by mtdvlpr** [comment]
Hi @alanfermtz, the problem is that the file type (`.jpg`) couldn't be found because of the `.`'s in the filename. #2286 fixes this. For now, you can manually add the `.jpg` to the filename and it will work.
