### ISSUE TITLE
[Bug]: Second display overlay blinks after opening JW.ORG in the app

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2353]
### What happened?

The second display image flashes quite randomly. Only M³ was opened on the computer. We turned off OBS, and Zoom but this did not help at all. Restarting the M³ didn't help either.

### To Reproduce

1. Go to 'M³'
2. Click on 'Presentation mode (blue button)'
3. Do 'Open JW.ORG' (not sure that it causes the issue)
4. Close it
5. Wait for random blinks to appear

### What did you expect to happen?

The year text overlay will appear and disappear without any predictable behavior

### Version

latest stable version

### What platform are you seeing the problem on?

Windows

### Video

https://github.com/sircharlo/meeting-media-manager/assets/80993061/2a60013d-ea10-4429-b026-ad11603ea192

### Additional context

Not yet tried to restart the computer, but will do in a few hours. 

**Update:** on the next meeting the issue was gone.

**Comment by ux-git** [comment]
**Update 2:** Sometimes during the meeting the year text overlay may disappear for a few seconds. I have a feeling that it's only when no media has been presented for quite some time.

**Comment by mtdvlpr** [comment]
Hi @ux-git, I haven't been able to reproduce this unfortunately

**Comment by ux-git** [comment]
Hmm, that's weird. This happened a few times already. Can't say for sure what exactly causes it, but I had only M3 app open, so that's why I'm reporting.

**Comment by ux-git** [comment]
Update: Today we got the song on the second display went off for 5 seconds. We've touched nothing, did everything as always. 

Which apps were open: M³, Zoom, OBS, Microsoft Edge.

What helped: To hover over the M³ icon in the windows taskbar, and click on the M³ window with the song once again.
