### ISSUE TITLE
Update to allow for dynamic maximum number of meeting songs

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#2424]
I'm away from my computer right now, but this line would need to be updated:

https://github.com/sircharlo/meeting-media-manager/blob/e6315e3d045d96a63eaf5b3189ecabc75aadf504/src/renderer/constants/general.ts#L49

Instead of a hardcoded `151`, we should dynamically get the highest available `sjjm` track where the track number is less than `500` (the cutoff for songs with audio descriptions). The correct number is `158` as of today, but this is bound to change in the future.

**Comment by mtdvlpr** [comment]
@sircharlo, should have a fix ready now :)
