### ISSUE TITLE
[Bug]: Songs randomly pause

### ISSUE THREAD

**Issue by davidpeele** [sircharlo/meeting-media-manager#2479]
### What happened?

Often and randomly a song video will stop playing. It seems to be most frequent when playing the first song of a meeting. In the playlist, the song that is playing will still show the pause button as if the video is still playing. To resume playing you must click pause then click play and the video will continue. 

### To Reproduce

It is random

### What did you expect to happen?

The video should continue to play until the end

### Version

V24.4.0

### What platform are you seeing the problem on?

Windows

**Comment by sircharlo** [comment]
> ### What happened?
> Often and randomly a song video will stop playing. It seems to be most frequent when playing the first song of a meeting. In the playlist, the song that is playing will still show the pause button as if the video is still playing. To resume playing you must click pause then click play and the video will continue.
> 
> ### To Reproduce
> It is random
> 
> ### What did you expect to happen?
> The video should continue to play until the end
> 
> ### Version
> V24.4.0
> 
> ### What platform are you seeing the problem on?
> Windows
> 
> ### Relevant log output
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_

Hi @davidpeele ! 
Sorry I took so long to answer. We're busy working on the new version on M³, so this version is on maintenance mode for now. 
Keep your eyes peeled for the newest version, which will take care of all these bugs along with making managing media much, much easier and intuitive. 
Thanks for your patience!

**Comment by sircharlo** [comment]
Bump

**Comment by mtdvlpr** [comment]
Bump

**Comment by sircharlo** [comment]
Closed with https://github.com/sircharlo/meeting-media-manager/discussions/2753
