### ISSUE TITLE
[Bug]: <It keeps asking for microphone permission when the Zoom screen sharing starts>

### ISSUE THREAD

**Issue by heymenshan** [sircharlo/meeting-media-manager#2497]
### What happened?

It keeps asking for microphone permission when the Zoom screen sharing starts.

### To Reproduce

1. Go to 'Zoom'
2. Click on 'Share Screen'
3. Do 'Sharing'

### What did you expect to happen?

It keeps asking for microphone permission when the Zoom screen sharing starts.

### Version

24.4.0 (24.4.0)

### What platform are you seeing the problem on?

MacOS

**Comment by mtdvlpr** [comment]
Hi, please see #2178 for possible solutions

**Comment by sircharlo** [comment]
Solved with workaround, as per https://github.com/sircharlo/meeting-media-manager/issues/2178#issuecomment-2160331374
