### ISSUE TITLE
[Bug]: <The media screen is changed to full screen>

### ISSUE THREAD

**Issue by heymenshan** [sircharlo/meeting-media-manager#2504]
### What happened?

The media screen is changed to full screen randomly. In "Show media presentation window in" settings, I set it to display the media in a "movable window". But it keeps changing into full screen randomly. I could not reproduce the error.

### To Reproduce

3. Do '....'

### What did you expect to happen?

n/a

### Version

24.4.0 (24.4.0)

### What platform are you seeing the problem on?

MacOS

**Comment by sircharlo** [comment]
Hi @heymenshan ! 
Sorry I took so long to answer. We're busy working on the new version on M³, so this version is on maintenance mode for now. 
Keep your eyes peeled for the newest version, which will take care of all these bugs along with making managing media much, much easier and intuitive. 
Thanks for your patience!

**Comment by sircharlo** [comment]
Bump

**Comment by sircharlo** [comment]
Closed with https://github.com/sircharlo/meeting-media-manager/discussions/2753
