### ISSUE TITLE
[Bug]: <titolo>Condivisione contenuti multimediali su Zoom

### ISSUE THREAD

**Issue by R4ff05** [sircharlo/meeting-media-manager#2568]
### What happened?

Uso un Mac con M1. Quando condivido un video continua a chiedermi di dare i permessi audio anche dopo aver dato tutti i permessi nelle impostazioni. Me lo chiede ripetutamente. 

### To Reproduce

3. Do '....'

### What did you expect to happen?

Dopo aver dato i permessi non dovrebbe più chiederlo

### Version

24.4.1 (24.4.1)

### What platform are you seeing the problem on?

MacOS

### Screenshots

[
<img width="291" alt="Screenshot 2024-08-23 alle 13 56 28" src="https://github.com/user-attachments/assets/d508c12d-b587-4bf5-9e07-0dca4d920f35">
](url)

**Comment by mtdvlpr** [comment]
Hi, please see #2178 for possible solutions.

**Comment by mtdvlpr** [comment]
https://github.com/sircharlo/meeting-media-manager/issues/2178#issuecomment-2160331374
