### ISSUE TITLE
[Feature]: Hiding Mouse in Media Window option

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#2571]
### Is your feature request related to a problem?

It's distracting to see the mouse when someone else is sharing and just forgets to move it outside. 

### Describe the solution you'd like

Create an option whether to hide it completely in that window 

### Describe alternatives you've considered

Also maybe try hide it after a certain time. There is a feature in VLC called Hide cursor and fullscreen controller after X milliseconds.

**Comment by sircharlo** [comment]
Hi there! I've been looking into this; there doesn't seem to be a good way to do this for now in Electron unfortunately. 
I'll keep it on my radar though.
Thanks for the suggestion!

**Comment by mtdvlpr** [comment]
@sircharlo 

https://stackoverflow.com/questions/1071356/is-it-possible-to-hide-the-cursor-in-a-webpage-using-css-or-javascript

**Comment by mtdvlpr** [comment]
Seems to be as simple as a css property: `{ cursor:none; }`

**Comment by sircharlo** [comment]
> Seems to be as simple as a css property: `{ cursor:none; }`

Not so simple with Electron + inactive window though...

**Comment by mtdvlpr** [comment]
On the roadmap of #2781

**Comment by sircharlo** [comment]
I don't think this is feasible unless we get rid of the frameless option. For some reason, frameless windows don't respect mouse events and cursor styles.

**Comment by sircharlo** [comment]
I'm closing this for now, as unfortunately Electron makes this impossible. If ever we add the frame back to the media window, maybe we could revisit.
