### ISSUE TITLE
[Feature]: <title> Disable Update

### ISSUE THREAD

**Issue by heymenshan** [sircharlo/meeting-media-manager#2736]
### Is your feature request related to a problem?

The app tries to update without my permission

### Describe the solution you'd like

In some territories, Github is blocked and not accesible without VPN or other circumvention methods. And every time the app starts it looks for new update, which could lead to suspision. 

### Describe alternatives you've considered

No workaround.

**Comment by mtdvlpr** [comment]
You can already disable auto updates in settings. You would still get notifications when a new update is available, but it won't be installed. Version `24.4.8` includes an extra option to `disable checking for updates`, which will also disable the call to GitHub for checking whether there's a new version.

> [!IMPORTANT]
> This is probably the last release before the big update (see #2503). The big update won't have this option available for now.

**Comment by heymenshan** [comment]
Hope you can enable this feature for the new update as well in the future.

**Comment by mtdvlpr** [comment]
You can safely stay on this version (`24.4.x`) until you are ready to update again. All current features will be considered in due time, but it probably won't be in the initial big release. The option to disable auto updates has not been implemented yet either. So keep your eyes out for upcoming releases or create a new issue when you suspect we've forgotten.

**Comment by mtdvlpr** [comment]
But keep in mind that once the big initial release has officially been rolled out, this current version won't be able to receive any maintenance anymore (for example, when a new publication is going to be studied at the Congregation Bibly Study).

**Comment by mtdvlpr** [comment]
`24.4.8` is ready to be installed :)

**Comment by sircharlo** [comment]
Great catch! Thanks to @mtdvlpr for adding this option in the legacy version.
I've added this possibility in the new version as well in https://github.com/sircharlo/mmm-refactor/commit/1eddfd289387c8ddcba26f0db665c065204f18bd.

**Comment by mtdvlpr** [comment]
Hi @heymenshan, turns out there was a bug in the logic to disable checking for updates. It should be fixed in the patched version of [v24.4.8](https://github.com/sircharlo/meeting-media-manager/releases/tag/v24.4.8).
