### ISSUE TITLE
[suggestion] move the badges with paragraphs and songs to the thumbnail

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#2760]
(with a background, so it could be visible) I have this issue because I use a very small window and the numbers are taking so much space there

![image](https://github.com/user-attachments/assets/c3f49099-e389-4b54-94e0-428141a99da7)

**Comment by dagandrew** [comment]
Sorry, it will go to discussions

**Comment by mtdvlpr** [comment]
Duplicate of #2765
