### ISSUE TITLE
[Feature]: Persist background image

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#2761]
If you set a new background once it should be saved forever I think

**Comment by mtdvlpr** [comment]
This is intended behavior. The background image feature is intended for special use cases. For example, during the memorial when the yeartext needs to temporarily be replaced with another image.

@sircharlo, correct me if I'm wrong.

**Comment by sircharlo** [comment]
That's correct; the background image is always the yeartext, unless a special event like the Memorial requires a different one.
@dagandrew Are there cases where the yeartext would not be displayed on a regular basis?

**Comment by dagandrew** [comment]
I don't think so, but previously it was there forever

**Comment by sircharlo** [comment]
It would be good to add feedback for the user. I'll add a notification that the image will reset when the app is closed so users aren't surprised

**Comment by sircharlo** [comment]
Feedback implemented in de42068863057f7e5aaf61568c009593cb688260.
