### ISSUE TITLE
[Bug]: M3 not remembering window size anymore

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#2762]
I think the playlist window remember its size and position, the Mediat Window could remember its position but it can't remember its size and I need to do it manually every time

**Comment by dagandrew** [comment]
Sorry, it will go to discussions

**Comment by sircharlo** [comment]
@dagandrew Out of curiosity, do you use the media window fullscreen or windowed?

**Comment by sircharlo** [comment]
Initial implementation of this is 9a84f5a83ee0f9848b70c2929805e169ccc2fee2.

**Comment by dagandrew** [comment]
> @dagandrew Out of curiosity, do you use the media window fullscreen or windowed?

@sircharlo I used it windowed for Zoom meetings

**Comment by dagandrew** [comment]
@sircharlo now in version 24.10.10 on Windows 11 the main video doesn't remember its size and position. It always opens in the center of the screen

**Comment by mtdvlpr** [comment]
@dagandrew, fixed again in e6aa170f968aae1d0ca5061b24f172604eb6e0a9

**Comment by dagandrew** [comment]
thank you, it works perfectly!
