### ISSUE TITLE
[Bug]: macOS - JW.org share not working

### ISSUE THREAD

**Issue by yarko-w** [sircharlo/meeting-media-manager#2768]
<img width="529" alt="Screenshot" src="https://github.com/user-attachments/assets/ad3f0431-02d0-40c7-8805-86bfc8bea7af">

Unable to use the jw.org share feature on MacOS Sequoia. Each time it asks for screen and audio recording which is already enabled but media window only returns a black screen. Restarting software and laptop didn't resolve. 

Not posting to complain, LOVE the new update guys! Makes me want to buy a mac to run at our hall 😄

**Comment by ux-git** [comment]
The same issue on my end on macOS Sonoma. 

Browser controls (back, reload, zooming) do work, but the second display is black (the year text disappears btw).

**Comment by sircharlo** [comment]
This is surprising to me, considering I thought I had disabled this feature for macOS completely. 😆 
This feature needs some work to be functional in macOS.

**Comment by sircharlo** [comment]
Would any of you be willing to try out a test build?

**Comment by ux-git** [comment]
@sircharlo sure thing 😀

**Comment by sircharlo** [comment]
Thanks!

https://we.tl/t-VF3B4ji3J4

Two versions to try in there.

**Comment by ux-git** [comment]
Neither solution worked for me. I’ve tried installing both versions and launching them, but each time the app still prompts for screen recording permissions, even though I’ve already granted them. The media window turns black and fails to mirror the website.

**Comment by mtdvlpr** [comment]
Hi,

I've got another version for you guys to test. If M3 asks for permission, please verify if the message that's shown is a custom message or the default one.

https://we.tl/t-vD5od06juZ

**Comment by mtdvlpr** [comment]
Here's another one that might do the trick:

https://we.tl/t-sHtHWmbqyh

**Comment by ux-git** [comment]
@mtdvlpr neither worked for me unfortunately. The latest build displays even the original jw.org window quite broken:

<img width="1392" alt="Screenshot 2024-11-04 at 21 18 07" src="https://github.com/user-attachments/assets/5a6620ce-d407-424c-af70-04f6e9c31873">

@yarko-w what about you?

**Comment by sircharlo** [comment]
> @mtdvlpr neither worked for me unfortunately. The latest build displays even the original jw.org window quite broken:

Yeah, the mirroring is broken due to some invalid CSP configuration I believe. Same on Windows for now.

**Comment by mtdvlpr** [comment]
> > @mtdvlpr neither worked for me unfortunately. The latest build displays even the original jw.org window quite broken:
> 
> Yeah, the mirroring is broken due to some invalid CSP configuration I believe. Same on Windows for now.

Oops, sorry about that. Should be fixed now. If not, we'll just remove the csp altogether.

**Comment by mtdvlpr** [comment]
> @mtdvlpr neither worked for me unfortunately. The latest build displays even the original jw.org window quite broken:
> <img alt="Screenshot 2024-11-04 at 21 18 07" width="1392" src="https://private-user-images.githubusercontent.com/80993061/382906377-5a6620ce-d407-424c-af70-04f6e9c31873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTUxNTEsIm5iZiI6MTczMDc1NDg1MSwicGF0aCI6Ii84MDk5MzA2MS8zODI5MDYzNzctNWE2NjIwY2UtZDQwNy00MjRjLWFmNzAtMDRmNmU5YzMxODczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDIxMTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZTEyY2FhNTU5YTE3NzM5ZjgzNTdlZTdiMDYyMDQ0NzBkZDIwOTdkZmVmODRkNDNhNzhlZTA3NWIzNWE5MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3OrXWbsVZVKjDtH6Mr7L6VK8zDwL9vfaKXknAlOa_CE">
> 
> @yarko-w what about you?

Thanks for testing! Did you get the permission request though? If so, did it show the custom message or a default message?

**Comment by ux-git** [comment]
@mtdvlpr sorry, forgot to mention this. Yes, the message was new, asking for the camera access.

**Comment by mtdvlpr** [comment]
@ux-git, alright, thanks! This helps. I've fixed the security issues preventing both macOS and Windows from presenting the website. Could you try this one for me?

https://we.tl/t-gBFioDEr4t

**Comment by ux-git** [comment]
@mtdvlpr both last versions:
<img width="372" alt="Screenshot 2024-11-05 at 10 41 52" src="https://github.com/user-attachments/assets/4bae8990-9164-4102-a2c0-01c007dd26b3">

**Comment by mtdvlpr** [comment]
Or try downloading it as a zip file with the installer inside:

https://we.tl/t-qUTjjzmx0J

**Comment by mtdvlpr** [comment]
Are you able to download it directly from GitHub?

https://github.com/sircharlo/meeting-media-manager/actions/runs/11681584905

**Comment by ux-git** [comment]
@mtdvlpr literally every version (both Wetransfer, Wetransfer archive, and GitHub latest) are "damaged or incomplete". I managed to install only the normal package-macos-13 version, which also won't demonstrate the website.

**Comment by mtdvlpr** [comment]
@ux-git, ah, I see the problem. It's not damaged, it's just not trusted by the system. You can fix this yourself:

https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

**Comment by mtdvlpr** [comment]
@ux-git, please see if the latest build fixes things (after applying above fix for installing the app):

https://github.com/sircharlo/meeting-media-manager/actions/runs/11683212325

**Comment by mtdvlpr** [comment]
> @ux-git, ah, I see the problem. It's not damaged, it's just not trusted by the system. You can fix this yourself:
> 
> https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

This has been added to the documentation website: https://sircharlo.github.io/meeting-media-manager/using-at-a-kingdom-hall#additional-steps-for-macos-users

**Comment by mtdvlpr** [comment]
Awesome! Those black bars are probably because of some ratio calculation difference between Windows and mMacOS. I think we can solve it with some extra user testing.

Thank you all for the help with testing this!

**Comment by sircharlo** [comment]
Wow this is great! Finally!! Thanks so much to @mtdvlpr

**Comment by mtdvlpr** [comment]
> [!IMPORTANT]
> You might have to install the new version manually instead of automatically, due to a bug that's been fixed for upcoming releases.

**Comment by ux-git** [comment]
I have no idea why, but on the latest version released yesterday, the website sharing doesn't work anymore... 

All the camera and mic accesses are given, but it keep asking for the screen access, even thought it's permitted. While testing the [pre-release build ](https://github.com/sircharlo/meeting-media-manager/issues/2768#issuecomment-2456745298), I had to grant screen access and it immediately started working. Now not anymore, the same black screen and constant screen recording request: 

<img width="573" alt="Screenshot 2024-11-07 at 15 35 59" src="https://github.com/user-attachments/assets/768c8ba3-3252-4705-bd93-9c7367854082">

**Comment by mtdvlpr** [comment]
@ux-git, hmm. Nothing of interest has been changed between those versions. Could you please check if the latest dev build works?

https://github.com/sircharlo/meeting-media-manager/actions/runs/11725203194

**Comment by mtdvlpr** [comment]
@sircharlo 

https://github.com/sircharlo/meeting-media-manager/compare/528d720a6b6541e64c8359e20332bba4f3adfc5f...v24.11.0

**Comment by ux-git** [comment]
So seems like the issue, even though it a bit complicated, it controllable instead of being random or unpredictable.

**Comment by mtdvlpr** [comment]
> Little update:
> 
> After upgrading 24.11.0 to 24.11.1, the website presenting stopped working once again. It asked me for the new cam/min permissions, and after that the window was black anyway. A quick workaround that helped me without re-installing anything:
> 
> Remove the M3 from the permissions list, and re-add it manually. Then it instantly works: <img alt="Bildschirmfoto 2024-11-13 um 12 50 06" width="564" src="https://private-user-images.githubusercontent.com/80993061/385748277-80bc2d58-f084-4661-ab1c-bb815681e9a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTk5MTcsIm5iZiI6MTczMTQ5OTYxNywicGF0aCI6Ii84MDk5MzA2MS8zODU3NDgyNzctODBiYzJkNTgtZjA4NC00NjYxLWFiMWMtYmI4MTU2ODFlOWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEyMDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOTI4NmM3YjdkZTJiMDYzMTc1ZjgxNmNkNjk1ODM3Y2M3MzQzZTc3MjFiN2UzNWZiNDA2YTFlMjgyYjQ5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ViWNUpMOXjFbg7MdBu01_P-3M0bTxK3T3lmVCTFHehY">

@sircharlo, this does seem like something for the docs. It seems MacOS users have to perform this action after EVERY update.

**Comment by sircharlo** [comment]
Makes "perfect" sense, because each app update has a unique signature on macOS, and permissions are granted on a per-signature basis. 

I guess we can add your workaround to the docs for users that are updating on macOS.
