### ISSUE TITLE
[Bug]: Documentation title mistake

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2787]
### What happened?

On the new docs website the 'Baclground music' is not in English, I suppose Dutch or something similar

### To Reproduce

Go to the home page

### What did you expect to happen?

To have it in English

### Version

Current

### What platform are you seeing the problem on?

Windows

### Screenshots

[
![Screenshot_20241018-180710](https://github.com/user-attachments/assets/2467d715-b576-4426-a7c9-2a446093d0a1)
](url)

**Comment by mtdvlpr** [comment]
Can you check the url? It works correctly for me. I think you've automatically been redirected to the german version.

**Comment by mtdvlpr** [comment]
We added a script that automatically redirects to the preferred locale of the browser.

**Comment by sircharlo** [comment]
Feels like this is fixed now; I'll close unless there's another report of a similar issue.
