### ISSUE TITLE
[Bug]: No default state for navigation sidebar

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2793]
### What happened?

Once the app is opened, the nav sidebar has no tab pre-selected, even though it's displaying the Meeting media page

### To Reproduce

Open the app

### What did you expect to happen?

The Meeting media tab should should have a selected state

### Version

24.10.6

### What platform are you seeing the problem on?

MacOS

### Screenshots

<img width="936" alt="Screenshot 2024-10-18 at 23 08 56" src="https://github.com/user-attachments/assets/cdef3701-1fad-4313-940a-7b62443c1a34">

**Comment by sircharlo** [comment]
Nice. Fixed in 46ba9385969afc6a7f9ba556b372cfd9fcf56926.
