### ISSUE TITLE
[Feature]: Update the 'Where to find your app's version' description

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2794]
### Is your feature request related to a problem?

The version is now inside of "About the app" window.

![photo_2024-10-18 23 17 10](https://github.com/user-attachments/assets/712a93d1-7546-426f-9524-965ccc32f5d2)

### Describe the solution you'd like

To find your app's version, simply click on the M³ logo in the top left corner of the app window.

### Describe alternatives you've considered

-

**Comment by mtdvlpr** [comment]
Well spotted! This is fixed now.
