### ISSUE TITLE
[Bug]: Can't directly switch to another external display

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2796]
### What happened?

The display selection won't happen unless user selects another window type.

https://github.com/user-attachments/assets/7350cdfe-685c-4bdc-b6ea-ac26089aec4f

### To Reproduce

0. You must use at least 3 displays
1. Open the Media display settings
2. Click on another external display. It won't switch instantly
3. Change the window type to Windowed and then back to Full screen.
4. Now the display is switched to another one (if you previously clicked on it)

### What did you expect to happen?

The buttons should directly switch the media presenting monitors

### Version

v24.10.6

### What platform are you seeing the problem on?

MacOS

**Comment by ux-git** [comment]
@sircharlo already fixed

**Comment by sircharlo** [comment]
> The display selection won't happen unless user selects another window type.

But I didn't do anything! 🤣

**Comment by ux-git** [comment]
Then I need to double check the functionality, perhaps I mixed something up 🙃

**Comment by ux-git** [comment]
Double checked... Reopening the issue 😶‍🌫️

**Comment by sircharlo** [comment]
I think this is fixed as of https://github.com/sircharlo/meeting-media-manager/commit/e7d603d71c166f05b38e573d3cfdd729490f6eb9. Let me know...
