### ISSUE TITLE
[Bug]: Can't paste text into the app

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2797]
### What happened?

Can't paste any copied text into the app – neither into settings fields (crucial for copying OBS WebSocket password) nor even while editing an image name.

Seems like Cmd+A hotkeys doesn't work neither. Can be a shortcut issue.

### To Reproduce

Try to paste any copied text into any existing editable field on macOS

### What did you expect to happen?

Simple text pasting

### Version

v24.10.6

### What platform are you seeing the problem on?

MacOS

**Comment by mtdvlpr** [comment]
I think it should be fixed as of 0b9605612574f9ceb4c67eaa5ead20bb7844d8a0. 

@sircharlo, I believe when we unset the default menu, we also unset the default accelerators (see [reference](https://pracucci.com/atom-electron-enable-copy-and-paste.html))

**Comment by sircharlo** [comment]
Nice. Also tweaked a bit in 8e62283ddb568f3ffd1dd8ddf624b4ec51dec2e5.
