### ISSUE TITLE
[Feature]: OBS integration status indicator in the settings

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2798]
### Is your feature request related to a problem?

Currently, it's not instantly obvious if the OBS Studio integration connection is established while setting it up.

<img width="1209" alt="Screenshot 2024-10-19 at 00 11 08" src="https://github.com/user-attachments/assets/ebb19568-7e09-412c-9627-99dcae0d2d44">

### Describe the solution you'd like

**Proposal:** Adding a green outline around the password field (and possibly the port field too, your thoughts guys?) as soon as the connection is established will provide instant feedback that both the password and port are correct. Conversely, if the connection fails, both fields could be highlighted with a red border.

**Consideration:** One downside to this approach is that it may not be possible to verify whether either the port or password is correct before the connection is established. Let me know if that's actually possible. For example, if the user enters a password first, the field will remain red until a correct port is provided, which could lead to confusion, making it seem like the password is incorrect.

**Alternative Idea:** Instead of red for failure, we could use yellow to draw attention to these fields without implying an error. This approach would alert users to the need for data/correction while avoiding unnecessary anxiety about mistakes.

### Describe alternatives you've considered

Viewing the status in the blue action island, but I know that I should look there. Not sure if most of users will be able to quickly get this idea while they're focused on the settings fields.

**Comment by sircharlo** [comment]
Nice one. Implemented in 84b6fc48f1b503f8d1484ef93e755e194e521e4b; looking forward to your feedback.
