### ISSUE TITLE
[Bug]: OBS Scene button alignment with long titles

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2799]
### What happened?

With too long scene titles the button's text is not aligned to the middle.

<img width="694" alt="Screenshot 2024-10-19 at 00 41 36" src="https://github.com/user-attachments/assets/bf795db9-5088-49e0-bfe3-300aa084a1fc">

### To Reproduce

-

### What did you expect to happen?

Align

### Version

v24.10.6

### What platform are you seeing the problem on?

MacOS

**Comment by sircharlo** [comment]
Truncate long titles as of 69ff8278bebe52948dd7bb837dd5705cbf5188f0.
