### ISSUE TITLE
M3 to detect upon opening that there is only one congregation

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#2801]
### Describe the solution you'd like

**Português:** Seria possível o M3 detectar na abertura que existe somente uma congregação e já abrir na tela de apresentação as mídias? A ideia é tornar ainda mais prático, ou seja, quando existir apenas uma congregação que usa o salão (KH), o M3 identifica e abre direto a tela de apresentação das mídias, no caso, a tela abaixo.

**Inglês:** Would it be possible for M3 to detect upon opening that there is only one congregation and immediately open the presentation screen with the media? The idea is to make it even more practical, that is, when there is only one congregation using the hall (KH), the M3 identifies this and directly opens the media presentation screen, in this case, the screen below.

![image](https://github.com/user-attachments/assets/efc7aaf4-1e72-430d-815a-ac31e2ba205e)

**Comment by sircharlo** [comment]
In my case this is actually what happens.
To be clear, you only have one congregation profile, yet when you open the app it takes you to the congregation selection screen?

**Comment by e-Feitosa** [comment]
**Português: Resolvido!** _Removi o M3, fiz uma nova instalação e o comportamento esperado acontece. Também testei o seguinte, numa atualização com o M3 já existente, acessei as configurações e revisei as informações e o comportamento esperado começou a funcionar. Testei algumas vezes e está funcionando como esperado, o M3 quando existe apenas um profile abre sem passar para a tela acima indo direto para a tela das mídias. **Obrigado pela sua atenção**._

**Inglês: Issue resolved!** _I uninstalled the M3, did a fresh installation, and the expected behavior is now occurring. I also tested the following: during an update with the existing M3, I accessed the settings, reviewed the information, and the expected behavior started working. I tested it a few times, and it’s functioning as expected. When there's only one profile, the M3 opens directly to the media screen without passing through the previous screen. **Thank you for your attention**._
