### ISSUE TITLE
[Bug]: v24.10.6 to v24.10.7 broke profile

### ISSUE THREAD

**Issue by alanfermtz** [sircharlo/meeting-media-manager#2810]
### What happened?

Automatic Update broke the profile

### To Reproduce

Message of new update...
Close, and open again 

windows 10

### What did you expect to happen?

n/a

### Version

v24.10.7

### What platform are you seeing the problem on?

Windows

### Screenshots

![image](https://github.com/user-attachments/assets/2f9f3357-5e41-4fdd-bd09-9a59153319dd)

**Comment by alanfermtz** [comment]
I downgraded to .6 and all still there.

**Comment by sircharlo** [comment]
Thanks for letting me know! I'll look into it before re-releasing this version

**Comment by e-Feitosa** [comment]
@sircharlo, Maybe it would be interesting to return the option of having the beta test version as happened in the previous version, and in advanced settings have that warning not to use in KH

**Comment by sircharlo** [comment]
> @sircharlo, Maybe it would be interesting to return the option of having the beta test version as happened in the previous version, and in advanced settings have that warning not to use in KH

Not a bad idea. Could you add a discussion about this?

**Comment by sircharlo** [comment]
@alanfermtz Thanks again so much for reporting this. It's fixed now; it was a glaring oversight due to the switchover to a new framework with the refactor, 
New version to be released tomorrow with the fix!
