### ISSUE TITLE
[Bug]: Progress bar and song number badge color change on clicked media item

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2811]
### What happened?

When a media item is in a clicked state, the right (upcoming) part of the progress bar currently has the same color, which can cause confusion. Could you update the progress bar (right side) and the song number badge to change to a different color token when an item is clicked? This can be either one step up or down in color tokens list to maintain visual clarity and contrast.

### To Reproduce

Click on any media items

### What did you expect to happen?

More visible UI elements

### Version

v24.10.6

### What platform are you seeing the problem on?

MacOS

### Screenshots

![photo_2024-10-19 21 42 56](https://github.com/user-attachments/assets/25fe3131-abb3-46af-bd55-f4f20fb866bf)

**Comment by sircharlo** [comment]
Implemented in 9777f23c7c2c620df9c4db50c3f579ad060603a8.
