### ISSUE TITLE
[Feature]: Move Caching Songbook Video Files to Main Media Playback Settings

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2812]
### Is your feature request related to a problem?

I suggest moving the "Caching songbook video files" option to the main Media Playback settings category. 

### Describe the solution you'd like

Downloading all the songs once and for all is not only convenient but also reduces potential stress for users. Since most of users won't touch the Advanced setting, moving it to the Media Playback Settings will make this feature easier to discover and use for those who need it.

### Describe alternatives you've considered

-

### Additional context

![photo_2024-10-19 21 46 38](https://github.com/user-attachments/assets/f9fc7cde-9137-4402-ad8c-92a6b1d7a32c)

**Comment by sircharlo** [comment]
Implemented in 2bfe4f8459f6b03dd4643f3de84c59cde83cd9e7!
