### ISSUE TITLE
[Feature]: <title> Volume control

### ISSUE THREAD

**Issue by heymenshan** [sircharlo/meeting-media-manager#2821]
### Is your feature request related to a problem?

I find most of the videos from JW Stream seem to be having lower volume than other videos.

### Describe the solution you'd like

It would be great if M3 can increase the volume to more than 100% of the original volume.

### Describe alternatives you've considered

There is no easy way.

**Comment by mtdvlpr** [comment]
M3 doesn't change the volume of videos. Can't you play with computer volume or audio setup of the Kingdom Hall?

**Comment by heymenshan** [comment]
I can’t. I’m not using it at a KH. That is the reason why I asked for a new
feature.

**Comment by mtdvlpr** [comment]
What about the volume of your device?

**Comment by heymenshan** [comment]
If that is the case, I can always use VLC instead of M3.

**Comment by mtdvlpr** [comment]
I don't think we can increase the volume. We're using the HTML5 video element, which has the volume set to 100 by default, and it can't be set higher than that.

**Comment by heymenshan** [comment]
No worries. Thank you for your explanation.

I can use VLC instead.

Thanks you so much for your time.

**Comment by e-Feitosa** [comment]
@heymenshan,  see if this **FxSound** app resolves for you. Or the **EarTrumpet** app
