### ISSUE TITLE
[Bug]: The language of the M³ documentation changes to English without request.

### ISSUE THREAD

**Issue by cong862023** [sircharlo/meeting-media-manager#2829]
### What happened?

Hello Brothers!
I use the language pt-PT, so at the link: https://sircharlo.github.io/meeting-media-manager/pt-pt/.
When opening the M³ documentation (which is already fully translated into pt-PT) when clicking anywhere, instead of the language remaining in pt-PT, it ends up changing to English. 
This forces someone who needs help—who may not be very comfortable with the tool—to search for where to change the language. This will cause unnecessary inconvenience.
I don’t know if this is a bug common to all languages, but at least in pt-PT, it exists.

### To Reproduce

1. Go to 'https://sircharlo.github.io/meeting-media-manager/pt-pt/'
2. Click on any submenu or section.
3. See error

### What did you expect to happen?

Keep the computer language consistent across all pages and subpages.

### Version

v24.10.7

### What platform are you seeing the problem on?

Windows

### Screenshots

The images describe a bit of what happens.
![image 1](https://github.com/user-attachments/assets/d05560c4-08da-4760-9052-70398c039a51)
**Example (Incorrect URL):**
![image 2](https://github.com/user-attachments/assets/9400b161-6272-453a-a02f-f71625064d0b)
**URL Correct:**![image 3](https://github.com/user-attachments/assets/e17da136-df36-4c28-baa2-6e020e886a84)
_**Thank you for your excellent work!**_

**Comment by joaochris** [comment]
The same thing happens here.

**Comment by mtdvlpr** [comment]
Fixed now. I forgot to "translate" the links through Crowdin. I hid those strings, so that translators don't accidentally translate the english words of the url.
