### ISSUE TITLE
M³ not starting

### ISSUE THREAD

**Issue by lebereen** [sircharlo/meeting-media-manager#283]
Each time i want to start JWMMF i see this
![Image1](https://user-images.githubusercontent.com/105050485/167115212-fc3cee5c-9e92-431a-adf0-67395fe7d23f.png)

It doesn't go further.

**Comment by sircharlo** [comment]
Could you hit Ctrl-Shift-I on that screen please and post the contents of the console tab?

**Comment by lebereen** [comment]
![image](https://user-images.githubusercontent.com/105050485/167297689-4f019129-335a-49b3-9c35-afe4c03861f4.png)

**Comment by sircharlo** [comment]
Please try with the latest update, will be released in about 15 minutes

**Comment by lebereen** [comment]
It doesn't work. In fact, when i install on another session on my pc it works perfectly well. On my session I can't delete the profile of my assembly. JWMMF doens't ask me to create a profile. All the informations are already filled. Where can I delete them to make a clean installation ?

**Comment by sircharlo** [comment]
Delete the `%appdata%\jw-meeting-media-fetcher\` folder (something like `C:\Users\USERNAME\AppData\Roaming\jw-meeting-media-fetcher`).

Is this user account an admin user or a normal user?

**Comment by sircharlo** [comment]
Also, if you check and see if the error is exactly the same or if it changed, please, I'd appreciate!

**Comment by sircharlo** [comment]
Electron just released an update. Could you try again by downloading the latest installer please @lebereen ?

**Comment by joaochris** [comment]
@sircharlo A brother had the same problem:

 ![photo_2022-05-21_13-13-54](https://user-images.githubusercontent.com/76891864/169660761-97724179-685b-4d1a-b7b4-8195fde7b808.jpg)


The solution is what you already said :D
Delete the folder: `C:\Users\USERNAME\AppData\Roaming\meeting-media-manager`

**Comment by lebereen** [comment]
Perfect solution 👍

Envoyé de mon iPad

Le 21 mai 2022 à 18:29, joaochris ***@***.******@***.***>> a écrit :


@sircharlo<https://github.com/sircharlo> A brother had the same problem:

[photo_2022-05-21_13-13-54]<https://user-images.githubusercontent.com/76891864/169660761-97724179-685b-4d1a-b7b4-8195fde7b808.jpg>

The solution is what you already said :D
Delete the folder: C:\Users\USERNAME\AppData\Roaming\meeting-media-manager
