### ISSUE TITLE
[Feature]: Add screenshots to Crowdin

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#2849]
In order to better assist the translators, we want to add screenshots of all parts of the app and its documentation. This will help provide a clear context of where and how a certain string is used and how it should be translated.

# Progress

- [x] Documention Website
- [x] Shared layout components (nav, header, about)
- [x] Setup Wizard (missing OBS -> media scene)
- [x] Settings
- [x] Present website
- [x] Media Calendar
- [x] Congregation Select

**Comment by ux-git** [comment]
@mtdvlpr I can help if needed

**Comment by mtdvlpr** [comment]
Thanks for the offer! If you could provide the different screenshots, that would be very helpful. 

I try to capture as many strings as possible in one image. The image doesn't have to capture the entire window, but enough to be able to see the context of the strings. For example, a dialog can be captured without the blurred background.

In the setup wizard, I still need to capture the OBS media scene step, because I couldn't establish a real obs connection at that moment.

On the media calendar page, I captured the first page when no date has been selected yet.

**Comment by mtdvlpr** [comment]
@ux-git, do you have access to our Crowdin project

**Comment by ux-git** [comment]
@mtdvlpr yeah I do, but only as a translator/proofreader. I already have experience uploading and tagging screenshots on Crowdin.

**Comment by mtdvlpr** [comment]
Under which name? I don't see a `ux-git`...

**Comment by ux-git** [comment]
@mtdvlpr https://crowdin.com/profile/vlad-organized

**Comment by mtdvlpr** [comment]
You should have the necessary permissions now. Thanks for the assistance!

**Comment by ux-git** [comment]
Yes, thanks, I noticed that. I'll follow this approach

**Comment by ux-git** [comment]
@mtdvlpr I guess 99-ish % of the screenshots are added, unless I forgot something. Please take a look and let me know!

**Comment by mtdvlpr** [comment]
@ux-git, awesome work! I've added some extra screenshots and there are still a few strings left, but some of them are old and not being used in the app anymore. I'll clean them up and get back to you.

**Comment by ux-git** [comment]
@mtdvlpr I've added a few more screenshots, including those for info messages and hidden under sub-settings. It seems like the vast majority of strings now have screenshots.

**Comment by sircharlo** [comment]
Great work, guys!

**Comment by mtdvlpr** [comment]
@ux-git, thank you very much for your help! I removed all unused strings and we only have 23 strings left without a screenshot now. You can easily [find these strings on Crowdin](https://crowdin.com/editor/meeting-media-manager/94/en-de?view=comfortable&filter=advanced&value=12&verbal_expression_scope=translations&screenshots=without_screenshots) using the Advanced Filter. Some are edge cases that will almost never be shown to the user and others are not possible to take a screenshot of.

I'll mark this as completed :)

**Comment by ux-git** [comment]
@mtdvlpr awesome, my pleasure!
