### ISSUE TITLE
[Bug]: Page title and action buttons conflict

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2856]
### What happened?

With long translations, the page title(s) gets overlapped by the action buttons on the right while resizing the app's window.

### To Reproduce

1. Open Meeting Media page
2. Change the app's width

### What did you expect to happen?

You can either crop the title with an ellipsis (...) for a cleaner look, or consider minimizing the other buttons by removing the text and just showing icons. 

### Version

v24.10.8

### What platform are you seeing the problem on?

MacOS

### Screenshots

https://github.com/user-attachments/assets/abdb5205-a8ec-4086-9125-e1d90a482a76

**Comment by sircharlo** [comment]
Fixed in 0306819e12c724a23557ae9576474bb05172542d.
