### ISSUE TITLE
[Bug]: Yellow border (came back)

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2859]
### What happened?

While clicking on a meeting media item with a Shift pressed, the yellow outline appears again

### To Reproduce

1. Open meeting media
2. Hold shift
3. Click on any media

### What did you expect to happen?

Remove the outline

### Version

v24.10.8

### What platform are you seeing the problem on?

MacOS

### Screenshots

<img width="1132" alt="Screenshot 2024-10-21 at 23 13 17" src="https://github.com/user-attachments/assets/5266acf2-4184-42bc-976d-a5758aecc7d8">

**Comment by sircharlo** [comment]
😆 
d57c0451218cf9426aff86711b521ef43ebc8c9a
