### ISSUE TITLE
[Feature]: "Stop the media presentation first" info message

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#2860]
### Is your feature request related to a problem?

Currently, the app won't let you switch the page if you're presenting a video or an image. There's no issue with this, but adding some clarity for users would be awesome.

### Describe the solution you'd like

If media is being presented and user attempts to open another page, after the click I propose to add a tooltip or a snackbar saying "Stop the media presentation first to open another page". This will add some prediactability, since currently if the presented media is outside of the visible content area, it's hard to connect this issue (page won't open) with a potential solution (stop presenting).

### Describe alternatives you've considered

Do this a few times and guess the logic 🙃

### Additional context

<img width="889" alt="Screenshot 2024-10-21 at 23 18 45" src="https://github.com/user-attachments/assets/ea7b4544-6598-4451-a8df-84048d5892db">

**Comment by sircharlo** [comment]
Added in https://github.com/sircharlo/meeting-media-manager/commit/d2988dd84a51240bde3a1245f398bea5cdca2a7c.
