### ISSUE TITLE
[Bug] Can't select media window on Zoom on macOS when fullscreen

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#2916]
Hello, on the Mac version when sharing on zoom if the media display window is full screen on the second display zoom does not pick it up as an available app window to be shared. We can only share via zoom with it in windowed mode. Any fix?

_Originally posted by @Danreynolds124 in https://github.com/sircharlo/meeting-media-manager/discussions/2753#discussioncomment-11023054_

**Comment by sircharlo** [comment]
@danreynolds124 there you go 😄

**Comment by mtdvlpr** [comment]
Regression of #382

**Comment by sircharlo** [comment]
> Regression of #382?

Seems like it...

@Danreynolds124 Please let me know if v24.10.10 fixes the issue once it's out!
