### ISSUE TITLE
[Bug]: After clearing cache media is not fetched again

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#2918]
### What happened?

I cleared all cache files using the option in settings > tools. I restarted M3 and got an error about fetching media for 2 dates and the media window did not display the yeartext anymore. It does display the JW logo.

### To Reproduce

1. Go to 'Settings'
2. Click on 'Tools'
3. Do 'Remove all files from cache'
4. Restart M3
5. See errors

### What did you expect to happen?

M3 should know that the cache has been cleared and re-fetch all necessary files again.

### Version

v24.10.9

### What platform are you seeing the problem on?

Windows

### Screenshots

![image](https://github.com/user-attachments/assets/491ccfab-e566-4abf-bbca-fca24362af30)

![image](https://github.com/user-attachments/assets/4fc7d966-7830-42a2-a876-add4938aa249)

### Additional context

I suspect that the store data remained, so the store state thinks that everything is fetched already. I would expect the store data to be updated after clearing all cache.

**Comment by mtdvlpr** [comment]
Nevermind, I forgot that I cleared the media language and maximum resolution in the settings...

Those should not be clearable though, but that's a different issue.

**Comment by sircharlo** [comment]
"layer 8" lol
