### ISSUE TITLE
Atalho do M3 após atualização

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#2931]
### What happened?

_**Português:**  Um problema que tem ocorrido algumas vezes é o atalho sumir ou ao clicar não achar o .EXE do M3. Isso não ocorre sempre e nem em todos os computadores, hoje por exemplo, atualizei o M3 na minha máquina o ocorreu tudo bem. Já no KH, após atualizar o M3, o atalho da área de trabalho não achava o M3. E para resolver isso, somente reinstalando o programa M3. Não sei se tem acontecido com outros. Em outras congregações já ocorreu isso algumas vezes, e hoje, ocorreu novamente nessa nova versão. **Existe algo que possa fazer para não acontecer esse problema quando o M3 atualiza o atalho para de funcionar?**_

**English:** An issue that has occurred a few times is the shortcut disappearing or not finding the M3 .EXE when clicked. This does not happen all the time nor on all computers. For example, today I updated the M3 on my machine and everything went well. However, at the KH, after updating the M3, the desktop shortcut couldn't find the M3. To resolve this, I had to reinstall the M3 program. I don't know if this has happened to others. In other congregations, this has happened a few times, and today it occurred again with this new version. **Is there anything that can be done to prevent this issue when the M3 updates and the shortcut stops working?**

### Version

v24.10.9

### What platform are you seeing the problem on?

Windows 11

**Comment by sircharlo** [comment]
Should be resolved as of bbf3eb76f43ad2445be3c1dbdc3b35651364f587. Let me know if 24.10.10 fixes it for you!
