### ISSUE TITLE
Best display screen adjustment

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#2937]
### Is your feature request related to a problem?

Yes

### Describe the solution you'd like

Layout of the screen
It was commented in another post about this screen, another suggestion for the best use of the screen, especially on smaller monitors, is that the writing is below the number of the song and/ or paragraph, similar to what happens with the images of the note. 

## On small monitors, the screen looks like this:
![image](https://github.com/user-attachments/assets/235e7ce4-c75c-4bc5-abb8-18d97ae63edf)

## Adjusting, it would look like +/- like this:**
![image](https://github.com/user-attachments/assets/bf594fba-8c24-4f33-b5a4-74c01392724a)

## The other suggestion already mentioned was to move the paragraph number up the thumbnail
![image](https://github.com/user-attachments/assets/79cb4303-5cc6-4ce4-9748-23ca23e2ac16)

**Comment by ux-git** [comment]
@sircharlo if I had to choose, I’d pick the second suggested option. It cleverly uses the available vertical space and won’t create any conflicts with other UI elements, such as zoom controls, etc.

**Comment by mtdvlpr** [comment]
@ux-git, I'm confused. You say you'd pick the second option, but your reasoning sound like the first option. Do you want a new line after the badge or do you want to move the badge to the preview box?

**Comment by ux-git** [comment]
@mtdvlpr Ah, sorry about that! I meant the first option – I mixed up the second screenshot with the second option 🙃

**Comment by sircharlo** [comment]
Initial implementation of this in 0a51f2c969dd2a4cb5351112e0ed6e651a1a46cb.
I'll be looking forward to your feedback!
