### ISSUE TITLE
Name of OBS Studio scenes

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#2938]
### Describe the solution you'd like

M3, puts the name of the main SCENE as SPEAKER, we always use the word STAGE to indicate the general stage (whole scene). However, it has caused confusion in the operators because the MAIN SCENE on the M3 is called SPEAKER and not STAGE. We use the camera cutouts and in the SCENES we get two SCENES with the same name (Speaker), generating confusion. Ideally, the MAIN SCENE should be called STAGE to avoid this confusion.
![image](https://github.com/user-attachments/assets/47d3f7a8-1944-4f35-ac74-3a1675f5b7ef)

**Comment by sircharlo** [comment]
Nice catch.
Fixed in a9180eb4edd4c3e7a49b387f884bf4b6a7e8685e.
