### ISSUE TITLE
M3 cannot detect a video cut in a JW Playlist file.

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#2949]
### What happened?

When using the video trimming feature in JW Library and exporting the playlist, then importing it into M3, the video appears in full, without the cut made in JW Library.

### To Reproduce

Add a video to a JW Library playlist, use the video trimming feature, export the playlist, and import it into M3.

### What did you expect to happen?

So that the same video cut made in JW Library remains in M3.

### Version

Latest Version

### What platform are you seeing the problem on?

Windows

### Screenshots

![IMG_20241024_175816_520](https://github.com/user-attachments/assets/8024ff3e-75e7-4458-8dd3-afd4878bd79c)
![IMG_20241024_175820_398](https://github.com/user-attachments/assets/db87fe53-d5e8-4ff5-ae82-9b5fd247ae8d)

https://github.com/user-attachments/assets/79e214bd-d1b9-4c7f-939a-9f1351ba0f64

**Comment by sircharlo** [comment]
Not gonna lie, I had forgotten that this was a feature of those playlist files.
Implemented in edf2e2b3fe39590d0a1d837ffa37f845cdbcd68b; will be released with v24.10.10!
