### ISSUE TITLE
Media during the week of the visit

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#2980]
### What happened?
I really liked that the Tuesday media during the week of the visit are already added on site. Now, during the weekend, the opening song and the public talk images are added correctly (just a note: Sometimes when I extract the media from S-34, both from S34mp or the outline, they are not in the same order as in the outline, i.e., they are in descending order rather than ascending). I expected the weekend media after the W study to be added after the W study, but this is not happening; the media is being added before the W study, that is, during the public talk.

### To Reproduce

![image](https://github.com/user-attachments/assets/ec31fda2-1606-4c6f-b05b-f97e1c7fcc10)

### What did you expect to happen?

I expected the weekend media after the W study to be added after the W study, but this is not happening; the media is being added before the W study, that is, during the public talk.
![image](https://github.com/user-attachments/assets/9981efbd-8672-41c3-bfd4-17442dc44f90)

### Version

v24.10.9

**Comment by sircharlo** [comment]
This is tricky. How could M³ know if the media you're importing is for the final talk and not the public talk? Unless I'm mistake, this media is added in exactly the same way. 
We simply dragged and dropped the media and final song into place.

**Comment by mtdvlpr** [comment]
The only way I can think of, is if each section would have its own import button which would automatically put the imported files in their section. 

I'm not sure if it would be useful enough to actually implement though. Given how easy it is to simply drag them to the correct section.

**Comment by e-Feitosa** [comment]
As suggested by @mtdvlpr , I found the option of separation by Import Buttons for each section during the week of the visit interesting. This way, there would be a specific function to handle imports for each section during the visit week, which could simplify the process by ensuring that media is added to the correct location. This would prevent confusion about where the imported media should be allocated. As mentioned, the idea is to simplify.

**Comment by mtdvlpr** [comment]
@sircharlo, what do you think?

**Comment by ux-git** [comment]
I can imagine the CO talk sections to have their own "Add media" text buttons. This will make it a bit easier to batch import, even though I find the normal sorting now that difficult either.

<img width="1143" alt="Screenshot 2024-11-05 at 22 27 03" src="https://github.com/user-attachments/assets/cd728c2a-f4b5-4950-9b6d-d3cad40f3018">

But in this case I think we need to permanently display two 'Circuit overseer' sections. Thankfully, the meeting structure is unified and always the same, so it shouldn't be a problem. I would only specify the 'Public talk by circuit overseer' and the second area to be 'Service talk by circuit overseer'. That's the standard meeting parts, so it might work fine for all users I hope.

Aaand, in such case, the "Don't forget to add media" message can be removed, and the opening and closing song selection buttons can be combines within one message: "Don't forget to add an opening and closing songs", and then 'Select an opening song' + 'Select a closing song' buttons.

Your thoughts @mtdvlpr, @sircharlo?

**Comment by sircharlo** [comment]
To keep things consistent with the usual Sunday meetings, I'd recommend not having two sections that are different from the usual ones. The Sunday meeting should look as normal as possible, with the public talk section staying the same. This avoids extra customization and helps everyone navigate the layout more intuitively, without needing a specific 'Public talk by circuit overseer' label.

This being said, having the Add missing media button actually add media to the relevant section would be a convenient addition. I liked having two separate banners because they're for two seperate actions.

That's just my two cents though. I'm open to other ideas.

**Comment by ux-git** [comment]
If you’d like, I can design both options and post them in a new discussion poll to gather input from others who haven't even seen this issue page.

**Comment by mtdvlpr** [comment]
I agree with @ux-git. I think having the regular public talk section and an extra service talk section during the co visit. You'll always have at least the closing song to put in that section, so it's never unnecessary.

**Comment by sircharlo** [comment]
What would be the logic for doing that for CO weeks, but not having the public talk section show up by default (although empty!) for normal weekend meetings? 
Would it be more consistent the to show the public talk section all the time, as it's expected to be filled for all weekend meetings anyway?

**Comment by sircharlo** [comment]
To clarify, in my vision, a normal weekend meeting would look like this:

![image](https://github.com/user-attachments/assets/8543d840-7411-43e6-8b99-04cd7085af0a)

A CO weekend meeting would look the same, with the added (initially empty) final CO section as well.

**Comment by mtdvlpr** [comment]
@sircharlo, agreed. The public talk section is always visible and the service talk section is visible (albeit empty) during co week.

**Comment by sircharlo** [comment]
Done.

**Comment by ux-git** [comment]
@sircharlo exactly, well done. The only question is why wouldn't we add the opening song notification (or simply an "Add opening song" button) right into the corresponding public talk section? 

This will be also useful for CO visit week for the closing song. This way the UI can be simplified and focused on meeting parts instead of having the permanent purple info message (during the visit week even two).

The right-hand side on the empty talk section has a lot of available space, where the button can be easily fit. It can even be purple to match the color and attract more attention. Plus it can feature the song icon. This way the whole info message purpose and approach can be moved right inside of the public talk card, making the layout cleaner can putting the opening song in its natural habitat.

**Comment by ux-git** [comment]
@mtdvlpr awesome! Looks exactly like we discussed, I really like it! 🤝

**Comment by ux-git** [comment]
I just noticed that two talk areas have different texts. What about unified "Don't forget to add the song and/or additional media" without mentioning the talk and song types. This way a single text string will work for 1. normal talks, 2. CO public talk, and 3. CO service talk.

**Comment by sircharlo** [comment]
Maybe something even simpler, like "Don't forget to add any missing media or songs."

**Comment by sircharlo** [comment]
Why the "Add extra media" in the LAC section?

**Comment by mtdvlpr** [comment]
> Why the "Add extra media" in the LAC section?

As a convenience shortcut. Instead of adding media and dragging it to the LAC section you can add it directly. This would be convenient when a Local Needs part is replaced with an update or has extra media for example.

**Comment by sircharlo** [comment]
> As a convenience shortcut. Instead of adding media and dragging it to the LAC section you can add it directly. This would be convenient when a Local Needs part is replaced with an update or has extra media for example.

Very nice!!
