### ISSUE TITLE
[Feature]: <Specific resources for conventions and assemblies.>

### ISSUE THREAD

**Issue by cong862023** [sircharlo/meeting-media-manager#2983]
### Is your feature request related to a problem?

It’s not specifically related to a problem, but it is about **some resources that don’t currently exist and that would be essential** for this excellent program to potentially be used **in conventions and assemblies** in the near future. 
I know that the focus right now is on implementing and consolidating resources primarily for our meetings, but regardless, I would like to share my suggestions for specific and essential resources for a convention and/or assembly :

### Describe the solution you'd like

**(SUGESTION 1)** 
_As is quite common, before an assembly, there is a video that is repeated several times, such as the text of the assembly or something similar._ 
->Therefore, it would be useful to have **a loop function** or a repeat function, meaning a video can be played continuously until it is manually stopped. (This could also be helpful for our meetings, for example, on special occasions like the Memorial.)

**(SUGESTION 2)** 
_In conventions and assemblies, there are morning and afternoon sessions. Besides these two main divisions, we must also remember the many symposiums and speeches with different names and various multimedia items._ 
->My suggestion is that it **should be possible to insert and rename new sections** (for speech names, symposiums, and introductory videos) within the **two main sections** (morning and afternoon), instead of just 'imported media'.

**(SUGESTION 3)**
_The least important._
->Would be to change the name "Meeting Media" at the top to something like the app's own name, "Meeting Media Manager," or simply "Media Manager" instead of associating it with our meetings.
 
**This would be a significant step forward for this program to become a potential tool for these events as well.**

### Describe alternatives you've considered

The image below shows a suggestion with two main sections, morning and afternoon, labeled as numbers 2 and 3, respectively. There is also a introductory video, labeled as number 1 (with loop function) . Additionally, there are songs within the morning and afternoon sections. Finally, there are images and videos related to specific speeches, labeled as numbers 4 and 5.
![convenction](https://github.com/user-attachments/assets/7a390463-afdc-4332-9631-07de05a8e5f0)

### Additional context

**Thank you for your hard work!**
Greetings from Portugal!

**Comment by mtdvlpr** [comment]
Hi, thank you for your request! I personally think conventions and assemblies should be kept out of scope. They're special and have their own special requirements that JW Library can all do with jwl playlists.

**Comment by mtdvlpr** [comment]
@sircharlo, what do you think? You have the final say😉

**Comment by mtdvlpr** [comment]
I'm going to close this for now. If it's requested more often, we could revisit.

**Comment by sircharlo** [comment]
> @sircharlo, what do you think? You have the final say😉

Sorry, I missed this. Yes let's keep this focused on meetings for now.

**Comment by mtdvlpr** [comment]
Hi @cong862023, suggestion 1 has been implemented in #3378
