### ISSUE TITLE
[Feature]: Add FAQ tab to the Docs website

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3001]
### Is your feature request related to a problem?

There's no link to the FAQs from the home page

### Describe the solution you'd like

Add FAQ as one of the rounded buttons

### Describe alternatives you've considered

-

### Additional context

<img width="1356" alt="Screenshot 2024-10-27 at 15 37 32" src="https://github.com/user-attachments/assets/14746145-7c3c-44a0-a9a9-b570a74459ea">

**Comment by mtdvlpr** [comment]
Fixed in dc5512b5beeebd4def5d178c5bacff923f3cb4c4

I added FAQ to the top navigation and shortened the install button text (the buttons already overlapped the logo on smaller screens)
