### ISSUE TITLE
[Feature]: Ability to stop playing media using prev/next shortcuts

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#3035]
@sircharlo Works great! thanks. I've noticed that previously Next media button switched to the next media if the main backroung was shown and if they video or image was playing, it stopped it and switched to the background. Now it only switches and does nothing when they video is playing (although it switches when the picture is shown). Can you do either create a new shortcut for stopping the video or picture or like in the previous version keep the same button for that?

_Originally posted by @dagandrew in https://github.com/sircharlo/meeting-media-manager/discussions/2766#discussioncomment-11086261_

**Comment by sircharlo** [comment]
I've added a shortcut to stop and one to pause/resume in 436b41222f54cc1adfcc9916f5607abffc5d44f2.
Will be released in the next update!

**Comment by dagandrew** [comment]
Great! it works well.
I'm having a small issue though - when I press my keyboard shortcut for stopping a video, it shows me a prompt 'are you sure you want to stop the video?' and it's not very convenient to quickly switch between. Maybe you could leave the alert when the stop button was clicked by mouse, but when the keyboard shortcut was used just do the action without an alert?

**Comment by sircharlo** [comment]
To prevent accidentally hitting the shortcut during a cong for example, I won't be removing the prompt for now.

**Comment by dagandrew** [comment]
> Tip: the prompt can be dismissed with the same shortcut. So for example, if the shortcut is Ctrl+M, hit it once, get the warning, hit it again, video stops.

This works for me, thank you
