### ISSUE TITLE
[Feature]: Update notification

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#3054]
Currently the app does not show any notification that there is an update or a button to install the update. From what I've seen it occurs silently, when I close and open the application again it goes into the updated version.

Could you implement buttons like it was in the previous version before refactoring for this? This way it's clearer to know when there's an update :)

**Comment by sircharlo** [comment]
In keeping with the idea that this refactored app is simple and plug-and-play, what would be the advantage of notifying the user or showing action buttons when an update is available?
