### ISSUE TITLE
[Bug]: Command+Q is globally processed by MMM rather than the focused application

### ISSUE THREAD

**Issue by sbscomp** [sircharlo/meeting-media-manager#3108]
### What happened?

When focused on another window, such as Safari, when the user uses the Command + Q keyboard shortcut to exit the current application, MMM intercepts and processes the quit request instead, leading to MMM exiting rather than the currently focused application 

### To Reproduce

1. Run MMM
2. Run another application and focus on that application
3. Type command+Q on the keyboard

### What did you expect to happen?

The other application which is currently focused (e.g. Safari) exits, not MMM.

### Version

v24.10.10

### What platform are you seeing the problem on?

MacOS

**Comment by mtdvlpr** [comment]
This has been fixed and will be in the next release!

**Comment by mtdvlpr** [comment]
> [!IMPORTANT]
> You might have to install the new version manually instead of automatically, due to a bug that's been fixed for upcoming releases.
