### ISSUE TITLE
[Bug]: <title> When sharing to zoom OSX is asking for microphone permissions 4 times. 

### ISSUE THREAD

**Issue by Danreynolds124** [sircharlo/meeting-media-manager#3111]
### What happened?

When we share zoom the app asks for microphone permissions and then it does this multiple times. It may have something to do with it being an unsigned app? We grant the permissions but it does not seem to be storing them. 

### To Reproduce

3. Do '....'
 Share to zoom, permissions windows pop up

### What did you expect to happen?

We expect m3 to save the permissions for microphones so we don’t have to do this each time we share. 

### Version

V24.10.10

### What platform are you seeing the problem on?

MacOS

**Comment by mtdvlpr** [comment]
Hi, please see #2178 for possible solutions

**Comment by mtdvlpr** [comment]
@sircharlo, should we mention this problem in the docs again?

**Comment by Jiang-TJ** [comment]
> Hi, please see #2178 for possible solutions

This solution worked great for me!

**Comment by sircharlo** [comment]
> > Hi, please see #2178 for possible solutions
> 
> This solution worked great for me!

Thanks for the feedback @Jiang-TJ ! We'll be sure to update the docs with this information.

**Comment by sircharlo** [comment]
Docs updated!
