### ISSUE TITLE
[Feature]: Rename "add/import/extra media" button

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3137]
### Is your feature request related to a problem?

Since it's an action button, it's better to give it a verb in the name to make it clearer.

### Describe the solution you'd like

What about "Add media"? It's both short, clear and works well with the icon.

### Describe alternatives you've considered

It used to be "import", now it's "extra"

### Additional context

<img width="331" alt="Screenshot 2024-11-04 at 21 31 56" src="https://github.com/user-attachments/assets/9764a7a1-beba-47ce-8a8f-f797552cc8c9">

**Comment by sircharlo** [comment]
I like it.
8df22d4f2ed96d26c2757b104285d8316d513ead
