### ISSUE TITLE
[Bug]: Long names styling error (OBS scene buttons)

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3142]
### What happened?

The button's text is unaligned

### To Reproduce

Open the OBS menu in the action island, and take a look on a scene with a long name.

### What did you expect to happen?

Text aligned to the middle

### Version

v24.10.10

### What platform are you seeing the problem on?

MacOS

### Screenshots

<img width="533" alt="Screenshot 2024-11-04 at 22 31 56" src="https://github.com/user-attachments/assets/2a4bb23c-f199-4226-938d-f8bb5ce30413">

**Comment by mtdvlpr** [comment]
This has been fixed in the new OBS popup design
