### ISSUE TITLE
JW Library playlists not importing v24.10.10 Intel Mac

### ISSUE THREAD

**Issue by Jiang-TJ** [sircharlo/meeting-media-manager#3166]
### What happened?

When using the Extra Media feature on intel macs jwlplaylists are not importing. There are no errors, simply nothing happens.  Video files import correctly just not JW Library playlist files.

### To Reproduce

1. Go to 'Meeting Media'
2. Click on the date to reveal the "Extra Media" button
3. Select "JW Library playlist" and browse to a playlist you'd like to import 
4. The import window closes but no media is imported

### What did you expect to happen?

I expected the Meeting Media list to be populated with media from the .jwlplaylist file.

### Version

v24.10.10

### What platform are you seeing the problem on?

MacOS

**Comment by Jiang-TJ** [comment]
Sure! I compressed it to make it uploadable. Thanks so much!
[ZhouMo.jwlplaylist.zip](https://github.com/user-attachments/files/17648510/ZhouMo.jwlplaylist.zip)

**Comment by sircharlo** [comment]
Works for me.. I dragged and dropped it:

![image](https://github.com/user-attachments/assets/57edd524-cace-4ba6-b193-9141a476ae05)

**Comment by sircharlo** [comment]
(Note that I installed the latest update just released, version 24.11.0. Maybe try that?)

**Comment by mtdvlpr** [comment]
It worked for me in both `v24.10.10` and `v24.11.0`

**Comment by Jiang-TJ** [comment]
Thanks I'll give it a try. For reference, I'm using a Macbook Air 2017 i5 running Monterey. I've tried downgrading v24.10.10, 10.9,  10.8 all with no success... I'll try the latest version and see how it goes. Thanks so so much!

**Comment by Jiang-TJ** [comment]
Happy to confirm v24.11.0 works perfectly! The playlists we create in JWL import nicely. Thanks again friends, your work is really, really appreciated!

**Comment by sircharlo** [comment]
Glad to hear it! The UI will be improved a bit for displaying a loading bar for playlists too in the next version. 
Thanks for your feedback!
