### ISSUE TITLE
[Bug]: Quit and Reopen won't reopen the app

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3190]
### What happened?

After granting screen recording access, the macOS asks to quit and reopen the app.

### To Reproduce

Grant the permission, click "Quit and reopen". The app is theoretically quit (no active windows), but the icon in Dock is active, and I have to manually quit it.

<img width="103" alt="Screenshot 2024-11-07 at 15 41 19" src="https://github.com/user-attachments/assets/9afa77de-0cbd-44b1-a7d8-9e097bacf806">

The app won't re-open either.

### What did you expect to happen?

Should quit and reopen as promised 😆

### Version

24.11.0

### What platform are you seeing the problem on?

MacOS

**Comment by mtdvlpr** [comment]
This bug has been fixed and will be in the next release
