### ISSUE TITLE
[Bug]: Remove Song/Paragraph badge click animation

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3196]
### What happened?

Even though it looks nice, it creates false feeling that something should've happened

### To Reproduce

Click on any badge

### What did you expect to happen?

No animation/interaction at all

### Version

v24.11.0

### What platform are you seeing the problem on?

MacOS

### Screenshots

https://github.com/user-attachments/assets/90eeccaf-3623-403c-b940-28017973c0da

**Comment by sircharlo** [comment]
Done! 😄 
https://github.com/sircharlo/meeting-media-manager/commit/646cda792b6c0ad7d4bc33c255eb4098ec1a0ae3.
