### ISSUE TITLE
Mirroring the JW Site

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#3206]
### What happened?

Currently, it is not working when there is more than one SCENE created in OBS Studio.

### To Reproduce

After clicking on mirroring, only the site appears on the KH TV, and the current selected scene remains on Zoom. 

### What did you expect to happen?

I expected the M3 to behave as before. When clicking on mirroring, the JW site screen would be displayed on the TV / Big Screen and Zoom meeting. This only happens if there is one SCENE for the camera and another scene for the media in OBS Studio. If there are more scenes, the M3 does not change the Zoom meeting image scene, keeping the current camera.

And then, I tried to show the JW site by clicking on the footer to show the DONATIONS option, and this error from the screenshot below happens.
![image](https://github.com/user-attachments/assets/840d125f-5e4a-42ef-81b4-bca2ac08e8a1)

### Version

v2024.11.0

### What platform are you seeing the problem on?

Windows

**Comment by mtdvlpr** [comment]
Fixed the OBS scene not changing in b658a18

**Comment by mtdvlpr** [comment]
I couldn't replicate the donations error. Does it happen consistently on every try?

**Comment by e-Feitosa** [comment]
> Não consegui replicar o erro de doações. Isso acontece de forma consistente em todas as tentativas?

To play the error: Mirror the JW site, slide down to find the DONATIONS option. Clicking this option will bring up the next error window. 

![image](https://github.com/user-attachments/assets/344f901d-d742-4dd3-aef6-2344b6dc2d73)

Message> Warning: Could not complete request. Please try again later. And after a certain time, the page stops searching for the site to load it.

![image](https://github.com/user-attachments/assets/b097092c-daaa-42da-a175-60b658c3d5a8)

**Comment by mtdvlpr** [comment]
@e-Feitosa, thanks! I managed to find the bug and fix it. It will be in the next release :)

**Comment by mtdvlpr** [comment]
Fixed in 517af9d4f6011a2ef7c53206c01b7805e2c413fa
