### ISSUE TITLE
[Bug]: Video does not end at 0s

### ISSUE THREAD

**Issue by Tdanforth** [sircharlo/meeting-media-manager#3207]
### What happened?

When a video plays and reaches the end, it does not stop after it fades to black. The screen remains black and the year text does not show, like it's stuck on 0:00s. The stop button has to be clicked. 

### To Reproduce

Not sure if this is on every system but we just press the play button on the video and the issue occurs. Seems to happen every meeting. It didn't happen on the opening song. But when we did the second song, the issue occurred. And the video after that. 

### What did you expect to happen?

For the year text to appear after the video fades to black.

### Version

24.10.10

### What platform are you seeing the problem on?

Windows

**Comment by sircharlo** [comment]
Hi @Tdanforth ! 
Could you try the latest version please? V24.11.0
Thanks!

**Comment by Tdanforth** [comment]
Sure. Will update on Saturday morning for our weekend meeting and
report back.
