### ISSUE TITLE
[Bug]: Unable to Replace S-34mp Media File

### ISSUE THREAD

**Issue by edssan-13** [sircharlo/meeting-media-manager#3208]
### What happened?

Dear brother, thank you for your wonderful efforts in creating this program.

While doing some tests to add S-34mp media, I ended up putting in an incorrect media. After that, I was unable to replace it with another correct media.

### To Reproduce

1 - Meeting Media
2 - Add Media
3 - Public Speaking Media
4 - Add Media other than S-34mp
5 - Replace Media with S-34mp File
6 - Incorrect file is not replaced

### What did you expect to happen?

First, I expected that it would not be possible to add a media other than the S34mp file. And if it is not possible to put a block, it would be possible to replace it easily.

### Version

v2024.11.0

### What platform are you seeing the problem on?

Windows

### Screenshots

![midia nao sai](https://github.com/user-attachments/assets/5c83c503-2710-4af9-8db7-399e808d2bc5)

![midia nao sai 0](https://github.com/user-attachments/assets/06c707ef-3fbc-4dc3-87fc-1e051c0e368b)

**Comment by mtdvlpr** [comment]
Thanks for reporting! This has been fixed in dd52036e6ffd08f13f1a47b1b531acbde540e94e.
