### ISSUE TITLE
[Feature]: Change transition when displaying media

### ISSUE THREAD

**Issue by kentestaccount** [sircharlo/meeting-media-manager#3213]
### Is your feature request related to a problem?

When comparing JW Library and M3, JW Library's media transitions fade to black and take longer, matching the fading transitions in our videos. M3, however, feels more responsive as it plays media immediately, but it uses cuts instead of fading.

### Describe the solution you'd like

Implement JW Library's fade-to-black transition when displaying media. Based on further testing, old versions of M3 actually handled transitions even better than JW Library. When exiting mid-video in JW Library, the video cuts to black then fades into Yeartext. In old M3, even mid-video, the image fades to black then fades into Yeartext.
https://github.com/user-attachments/assets/1846550f-afd4-4ab2-9f93-009cabacc3c9
(in the video, i might have replicated issue #3207)

### Describe alternatives you've considered

I guess I could use JW Library, but M3 makes managing hybrid meetings easier.

**Comment by kentestaccount** [comment]
after more testing, old versions seem to nail the transition, sometimes even better than jw library (when exiting mid-video in jw library, the video cuts to black then fades into yeartext. with old m3, even mid-video, the image fades to black then fades into yeartext)
https://drive.google.com/file/d/1qEm-Gig9hlmqO989ArOZdbPdyR56AMGA/view?usp=drive_link

**Comment by ux-git** [comment]
Maybe a slightly longer fade-out transition for both video and audio would do the trick to make it a bit more smooth? Personally, I don't see the practical benefits of fading out to a black screen first and then to the yeartext afterwards. 

Manually stopping the video usually means it needs to be stopped quickly, and that's where M³'s speed comes into play.

**Comment by mtdvlpr** [comment]
I believe the transition is longer with the (currently broken) auto stop feature. Like @ux-git, when manually stopping the video, you generally want it to be gone right away (because you clicked on the wrong video for example).

**Comment by sircharlo** [comment]
To be fair, the transition between two pictures is a bit jarring. I tweaked the transition a bit. Looking forward to your feedback for v24.11.1!

**Comment by kentestaccount** [comment]
Hello brothers!

I've found a solution to the transition issue I previously reported. It turns out that the problem was caused by turning off animations in Windows settings.

To fix this, you can:

    Turn On Animations:

        Go to Settings > Accessibility > Visual effects.

        Make sure the "Animation effects" toggle is turned on.

This should make the media transitions smoother, similar to the fade-to-black effect in JW Library. My issue might be an edge case, but I wanted to share it just in case anyone else encounters the same problem.

I noticed a video in this discussion (https://github.com/sircharlo/meeting-media-manager/discussions/3813#discussioncomment-11623123) where the transition didn’t look like mine. I automatically turn off animations on my Windows devices (both personal and at the Kingdom Hall), which is why I didn’t notice the difference earlier.

Additionally, it might be helpful to include a reminder about this setting in the installation instructions or the FAQ section.
