### ISSUE TITLE
[Feature]: Bring back old m3 scene picker functionality

### ISSUE THREAD

**Issue by kentestaccount** [sircharlo/meeting-media-manager#3214]
### Is your feature request related to a problem?

In the old version of M3, I used to have a separate scene with just a photo of the yeartext as a fallback in case something happened onstage. During the opening and closing songs, I would also click on the Yeartext scene because I wanted that scene to appear after the song for the prayer. When I clicked on that scene in the old M3, the media would continue to play, and the scene would only switch to the Yeartext after the media ended.

Here's a link to a video demonstrating this behavior: https://drive.google.com/file/d/16ezSopQnWVRRvcmzTWYkENYKBsjuxFQM/view?usp=drive_link)

However, in the new version of M3, when I click on the Yeartext in the instant scene picker, it immediately switches to that scene.

### Describe the solution you'd like

Bring back the old M3 scene picker function where, when clicking on scenes while media is playing, the media is prioritized, and the scene only appears after the media ends playing.

### Describe alternatives you've considered

Since I only need this functionality during prayers, I’ve tried waiting for the media to stop playing and then manually clicking 'Yeartext.' This ensures the media finishes before switching scenes. However, if I click 'Yeartext' before the media ends, it switches to the wide stage view after the media ends, which defeats the purpose of displaying the yeartext during prayer. https://drive.google.com/file/d/11XAgU4PthAuMeECMza-Ttn1lOdC46XCG/view?usp=sharing

**Comment by mtdvlpr** [comment]
The current behavior allows for full control of the current scene from inside M3. This means you never have to go to OBS to override the scene. Implementing the previous behavior of blocking a scene change when media is playing would remove that full control.

I think the current behavior is better. Maybe @sircharlo disagrees?

Another possible alternative is to select the yeartext scene before pressing play. Then when you press play and the media stops, M3 will revert the scene to the yeartext scene. This wouldn't be disruptive, because it makes sense to see the yeartext before seeing the media.

**Comment by ux-git** [comment]
As an alternative, I suggest setting up OBS hotkeys. They work even when the app is running in the background. For us, numpad keys are a fast and reliable solution – foe example, 1 for the main scene, 2 for the image, and 3 for the speaker + image. From our experience, it's even faster than clicking with a mouse, and they're always at your fingertips.

This workaround works quite well for those who want more flexibility, and it shouldn't (hopefully) interfere with the new advanced behavior.

**Comment by sircharlo** [comment]
Interesting use case!

The current direction doesn't specifically mention not showing what happens on stage during prayers, just that a stage wide shot should be sufficient at all times. 

I agree with the workarounds suggested for your desired end result, specifically either activating your custom year text scene before starting the first and last songs, or using OBS keyboard shortcuts. 

I don't think we'll regress this behaviour, as the OBS controller works better for most cases as it stands right now.
