### ISSUE TITLE
[Bug]: Present website on MacOS broken (again)

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#3217]
I have no idea why, but on the latest version released yesterday, the website sharing doesn't work anymore... I updated manually a few mins ago, entered the terminal commands.

All the camera and mic accesses are given, but it keep asking for the screen access, even thought it's permitted. While testing the [pre-release build ](https://github.com/sircharlo/meeting-media-manager/issues/2768#issuecomment-2456745298), I had to grant screen access and it immediately started working. Now not anymore, the same black screen and constant screen recording request: 

<img width="573" alt="Screenshot 2024-11-07 at 15 35 59" src="https://github.com/user-attachments/assets/768c8ba3-3252-4705-bd93-9c7367854082">

_Originally posted by @ux-git in https://github.com/sircharlo/meeting-media-manager/issues/2768#issuecomment-2462402307_

**Comment by skimark1** [comment]
I can't say that I've ever seen this screen. I'm running Seqouia 15.1 on both an Intel i9 iMac from 2019 and a 2023 MacBook Pro running 15.1. I'll keep an eye out for it.

**Comment by skimark1** [comment]
My suggestion on 3190 is related to what I had said earlier about when you click on the red ball, it doesn't quit M3. I've also got 24.3.8 on my Intel Mac and when I click the red ball it quits M3. Otherwise in newer versions it stays running in the dock with no available media window showing. It might be that the box to make close and restart isn't working and M3 is just sitting in the dock ignoring what's going on on the Mac.

**Comment by mtdvlpr** [comment]
@skimark1, could you install the test version `24.11.1` from:

https://github.com/sircharlo/meeting-media-manager/actions/runs/11742722479

This test version should have a fix for the issue you're describing is described in #3190. Could you test if the bug is fixed in the test version and report back?

**Comment by mtdvlpr** [comment]
@skimark1, about the download link. If you run an Intel mac, please download the `macos-13` zip file and install the dmg file from that download.

**Comment by skimark1** [comment]
24.11.1 still has the same behavior. Click the red ball and M3 continues to run with no accessible control window displayed. There is no option to bring the window back onscreen and the only thing you can do is manually quit M3 and relaunch to get a new console.

**Comment by mtdvlpr** [comment]
@skimark1, thank you for testing! Could you test this version as well? Again `macos-13` is for Intel Macs.

https://github.com/sircharlo/meeting-media-manager/actions/runs/11744421023

**Comment by skimark1** [comment]
Same behavior on intel Mac. Click the ball windows closes, M3 still running. Also the .dmg installer is still being challenged by privacy and security

**Comment by skimark1** [comment]
Also, the link to the versions doesn't allow download on my MacBook Pro M2 laptop. No links show up on the page.
<img width="1675" alt="Screenshot 2024-11-08 at 9 27 07 AM" src="https://github.com/user-attachments/assets/0fdd5e45-2169-4ece-b88d-5c2c8d526a55">

**Comment by mtdvlpr** [comment]
@skimark1, in the screenshot, you're not logged in to github (notice the sign in to view logs button in the top right corner). You have to log in to be able to download the artifacts.

**Comment by sircharlo** [comment]
> I downloaded it on my intel Mac and can't get past the Privacy and Security lock. Only option is to move to trash. It never gives me the option to allow it in the security window Sorry I missed the login, I tried again logged into GitHub account and went directly to MBP but still no ability to install it. Privacy and Security not giving option to install

Did you follow the steps from the documentation website?

https://sircharlo.github.io/meeting-media-manager/using-at-a-kingdom-hall#additional-steps-for-macos-users

**Comment by skimark1** [comment]
I followed the instructions and added the code to terminal. Still no success in installing on M2 MBP. And no option to install anyway in Security & Privacy

Thanks,
Mark Cillis
***@***.***

**Comment by skimark1** [comment]
I had the old version of M3 in Applications and the terminal script was applying to it. I got rid of the old one and have only the new one in there and it now launches. Still same behavior with clicking the ball closing the window but leaving M3 running with no way to bring window back without manual  quit and relaunch

**Comment by ux-git** [comment]
@skimark1 that's actually the expected behaviour on macOS. Even native Apple apps won't fully close after you click the red button. To fully close a macOS app you need to use Cmd+Q.

**Comment by ux-git** [comment]
> I followed the instructions and added the code to terminal. Still no success in installing on M2 MBP. And no option to install anyway in Security & Privacy

@skimark1 did you 1. install the app first (moved the app into Applications folder), not just opening the app from the install window? 2. use two terminal comments one after another (not both copied and pasted together)?

**Comment by skimark1** [comment]
The version before this newest one does close when you click the ball.

Thanks,
Mark Cillis
***@***.***

**Comment by ux-git** [comment]
My opinion is the app should follow the system's approach in such common user patterns. If all apps won't close by clicking the red button, but M3 does, that's something wrong with the M3 app 😄
