### ISSUE TITLE
[Feature]: Add playback timeline tooltip

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3218]
### Is your feature request related to a problem?

M3 won't allow to drag the video timeline while a video is presented, but it doesn't explain why. Currently, it might look like a bug.

### Describe the solution you'd like

When user tries to drag the playhead, the app can say something like "You can rewind the video only when it's paused"

### Describe alternatives you've considered

I tried explaining this to every brother, but that's an infinite process :lau

**Comment by mtdvlpr** [comment]
What do you think about this solution? When playing, the slider thumb is hidden so that it's more like a loading bar.
 
![image](https://github.com/user-attachments/assets/aec02caf-601c-49e4-9e2a-878775df6e51)

**Comment by mtdvlpr** [comment]
Implemented in 448ab40ea45d693309ab61dbfc53a03a9b9ed40b

**Comment by ux-git** [comment]
It's OK, but in most cases users won't even aware that there's the slider thumb for some rare cases. And when such rare case happens, the stress level won't allow to discover new ways to find it.

This way we're hiding the fact that user can rewind the video in my opinion. I guess it would be better to provide the tool, but also explain how it works. Unless you don't want to allow the rewind.

**Comment by mtdvlpr** [comment]
I think it's just as "hidden" as any other feature (custom durations, zoom picture, rename media, hide media). They're hidden until the right conditions apply (hovering, right-clicking, etc).

I don't think the rewind feature is so important and used so often that we explicitly need to reference it. It's just there when you can use it and hidden when you can't use it.

**Comment by sircharlo** [comment]
Another possible alternative would be to have the tooltip say "To rewind or fast forward, pause the media first" instead of the current media time when the user tries to interact with the timebar while media is playing.

**Comment by sircharlo** [comment]
Tweaked in https://github.com/sircharlo/meeting-media-manager/commit/586a0d797c7e7b1acc356a29783f15b949de82e7. Awaiting your feedback after the next update!

**Comment by ux-git** [comment]
@sircharlo sounds good! The media time badge is currently broken on the latest version by the way:

<img width="109" alt="Screenshot 2024-11-08 at 19 14 36" src="https://github.com/user-attachments/assets/52632e1b-4430-4061-8e53-f724d90ab025">
