### ISSUE TITLE
Public Talk Outlines (S-34*.jwpub)

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#3248]
### What happened?

I’m with the following error here, some public talk outlines (S-34*.jwpub) that have media (image/videos), the M3 is not able to extract the media from the file. For example, N.o 71 updated in 6/21 or N.72 and all these have media and opens normally in JWL. I downloaded again from the site, and did not extract in M3. In JWL the media appear normally. I tested other public talk outlines, and some actually have images and do not extract in M3.

### To Reproduce

Drag and drop or locate the JWPUB file from outline 71 and 72 and try to import the media into M3

### What did you expect to happen?

Expected media to be extracted for outlines that contain media. It is so that if you try to extract media from a sketch that has no media, a message appears that does not have. but for the cited outline (71 and 72 for example), no error message appears.

### Version

v2024.11.1

### What platform are you seeing the problem on?

Windows

**Comment by mtdvlpr** [comment]
Thanks for reporting! Fixed in 9d21311154745a10472701f864adfd28fb6c90cd and will be in the next release :)

**Comment by e-Feitosa** [comment]
Excellent solution. 
_As it was detected yesterday and a few minutes to start the meeting, the solution was to open in JWL and generate a playlist to import into M3._
