### ISSUE TITLE
Media window shows website window title bar

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#3256]
Awesome! Also wondering if it would be helpful to remove the window frame (title bar) around the share window since it doesn't have controls enabled anyways and it is shown to the media window. Not sure if this is possible or helpful?

_Originally posted by @yarko-w in https://github.com/sircharlo/meeting-media-manager/discussions/3222#discussioncomment-11218734_

<img width="1917" alt="Screenshot 2024-11-11 at 20 39 53" src="https://github.com/user-attachments/assets/ca1b2495-a968-4e68-8a32-1fa72fd9a540">

**Comment by mtdvlpr** [comment]
@ux-git, @yarko-w, does that title bar also show when the yeartext is shown?

**Comment by mtdvlpr** [comment]
> @mtdvlpr no, only during the jw.org mirroring. And after switching to the "camera mirroring mode". Before it was only the black screen and the main controlling window had close/minimize/maximize colorful buttons. After changing the method, there's no controls on the window itself and the new "camera" badge appeared in the top left corner (you can see it on the screenshot as well)

Alright. And how would you currently close the presentation mode then? Through the "stop mirroring" button in the main window?

**Comment by mtdvlpr** [comment]
@ux-git, the black bars come from the official website. If you were to zoom in or make the window smaller, you'll see the black bars become smaller until they disappear completely. 

As long as the media window is an exact copy of the website controller window, it's correct behavior. If there is more empty space on the media window than there is on the website controller window, it's a bug. Looking at the image, I think it's correct behavior (apart from the title bar).

**Comment by mtdvlpr** [comment]
As for the title bar, I think this is being forced by MacOS when you're capturing the window as a video stream. 

I found [this](https://www.electronjs.org/docs/latest/api/web-contents#contentsgetmediasourceidrequestwebcontents), which should theoretically solve it, by only capturing the webContents of the window instead of the entire window (including the title bar). But unfortunately, I haven't been able to correctly implement this and can't find any resources about it.

A possible hacky workaround would be to clip the received video feed somehow, but because we directly pass the stream to a HTML5 video element, I don't see a way to do that.

I'm afraid we'll just have to accept this as is...

**Comment by ux-git** [comment]
@mtdvlpr the bars are shrinking, but just a little bit. The aspect ratio of the mirroring window stays the same, I've tried to make it 16:9 to stretch the image on the secondary screens, but it doesn't work as I expected.

Perhaps the top title bar plays a role here as well. But maybe the presented area aspect ratio could be adjusted in accordance to this, to make 16:9 the **whole window** instead of the content area?

https://github.com/user-attachments/assets/c5cbcdc1-35df-4d80-a00d-dc1b8eb61f46

**Comment by mtdvlpr** [comment]
@ux-git, ah, now I see the problem. The media window has **extra** black bars on the sides that are not present on the website controller window. Yes, that is definitely an aspect ratio problem. We have a custom script to calculate the aspect ratio without the top bar, but that script should be adjusted for MacOS it seems.

**Comment by mtdvlpr** [comment]
@ux-git, could you test the build below?

https://github.com/sircharlo/meeting-media-manager/actions/runs/11816898358

**Comment by ux-git** [comment]
@mtdvlpr even the original mirroring window lacks around 90px of horizontal space when scaled up to 100% of possible size:

<img width="1920" alt="Bildschirmfoto 2024-11-13 um 17 16 21" src="https://github.com/user-attachments/assets/d99b9b01-19b5-4945-b1b2-673fa1a9cb83">

Therefore the black bars are still present: 

<img width="1392" alt="Bildschirmfoto 2024-11-13 um 17 15 20" src="https://github.com/user-attachments/assets/cd572e7e-5bed-4c69-9d42-827001814f56">

**Comment by mtdvlpr** [comment]
@ux-git, alright. I've got another one for you :)

https://github.com/sircharlo/meeting-media-manager/actions/runs/11821689717

**Comment by ux-git** [comment]
It feel pretty much the same as before, here's how much space is still available on the right:

<img width="1920" alt="Screenshot 2024-11-14 at 12 45 25" src="https://github.com/user-attachments/assets/b3d4846d-66e0-470f-8475-aef237d6132f">

The window is approximately 1827px pixels wide out of 1920px.

**Comment by mtdvlpr** [comment]
@ux-git, that is not the problem I'm trying to solve. Look at the menu bar. It fills the whole width. That is jw.org behavior. The content has a max width of 1140px.

What I'm trying to solve is the black space to the sides of the media window (it might be better visible if you switch to light theme):

![image](https://github.com/user-attachments/assets/991b31fa-03c1-4e06-93d0-81042c727d31)

**Comment by ux-git** [comment]
> that is not the problem I'm trying to solve. Look at the menu bar. It fills the whole width. That is jw.org behavior. The content has a max width of 1140px.

Hehe, maybe I didn't make myself clear enough. What I'm trying to point out is when the mirroring window is maxed out at 100% (!) it still won't cover the whole 1920x1080 screen size. That shows that the whole window's aspect ratio is still not 16:9. And this aspect ratio is transferred to another screen, making it also impossible to fill the 16:9 display ratio. Take a look at the red marked area:

<img width="1920" alt="Screenshot 2024-11-14 at 12 45 25" src="https://github.com/user-attachments/assets/f29f0191-941f-49a6-b31a-3559f5f401f4">

Or am I still missing something?

**Comment by ux-git** [comment]
So if you basically divide the empty area on the right by two, you'll get the size of black bars on the right and left at the secondary screen. 

1920 (fullscreen) - 1827 (current size of the window) = 93 px (of missing space) / 2 = ±46 px (per black bar)

**Comment by mtdvlpr** [comment]
Ah, I see. In the next test version I've completely removed the aspect ratio restriction for MacOS:

https://github.com/sircharlo/meeting-media-manager/actions/runs/11837102877

P.S. this test version should also fix #3314 (let me know if it doesn't)

**Comment by ux-git** [comment]
https://github.com/user-attachments/assets/08303cbd-c14f-44ca-814d-70f12bfc02a5

**Comment by mtdvlpr** [comment]
Okay, I think we have to use the `extraSize` parameter of the `setAspectRatio` function (see [docs](https://www.electronjs.org/docs/latest/api/browser-window#winsetaspectratioaspectratio-extrasize)).

**Comment by mtdvlpr** [comment]
How about this one?

https://github.com/sircharlo/meeting-media-manager/actions/runs/11838394346

**Comment by ux-git** [comment]
@mtdvlpr it's literally perfect! Thank you a lot 🤝

**Comment by mtdvlpr** [comment]
> @mtdvlpr it's literally perfect! Thank you a lot 🤝

Awesome! This will be in the next release 🚀
