### ISSUE TITLE
[BUG] "Open folder" button not opening folder

### ISSUE THREAD

**Issue by djnpinho** [sircharlo/meeting-media-manager#326]
![jw media](https://user-images.githubusercontent.com/103318556/168445188-7e4de986-332e-4607-9de0-46f962ca7bd4.jpg)
Botão sem Ação. Qual a finalidade do Botão?

**Comment by joaochris** [comment]
Esse botão serve para abrir a pasta do dia selecionado. No teclado aperte CTRL + SHIFT + I, tira um print do console e coloca esse print aqui ;)

**Comment by sircharlo** [comment]
Just to be clear, pressing that button should open the media folder in the file explorer. Is that not happening?

**Comment by djnpinho** [comment]
Exatamente Mano. Esse botão não está abrindo a pasta de Mídia.

**Comment by sircharlo** [comment]
Probably fixed [here](https://github.com/sircharlo/meeting-media-manager/commit/13fd620eefb7ddc1d5adde93522faddf104c80da#diff-d79af92b5cabad1e91c6c81c560d2151b37e3b2810d5a384e46964dc0cf51761R2765).

**Comment by djnpinho** [comment]
Muito obrigado pelo esforço e prontidão. Vou aguardar a atualização.

**Comment by sircharlo** [comment]
Released. Please reopen if issue persists.
