### ISSUE TITLE
[Bug]: Multiple Monitor Management Regression

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#3280]
### What happened?

It seems that (on three-monitor systems at least) there has been a regression:

- The fullscreen media window no longer "flees" the main window
- The fullscreen media window moves to the first monitor whenever the main window is moved, even if monitor 3 is selected in the display popup
- The fullscreen media window no longer remembers which monitor it was on during the last run
- The main window refuses to return to the first monitor if it was there during the last run. Instead, the media window goes to the first monitor and the main window goes to the second screen. 

I wonder if the issue is related to a conflict between the screenpreferences we persist, and the window-states that we also persist. 

### To Reproduce

Open M³ on a multiple monitor system. 

### What did you expect to happen?

Windows should remember their size and monitor between app starts. 

### Version

v24.11.1

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by alanfermtz** [comment]
I confirm the behaviour.
Windows 10
3 screens

also, i notice that the numeration is wrong based on system > display from windows

**Comment by mtdvlpr** [comment]
Fixed in ca9457ffd1fc71bd7e22a62ca3b3281b173eed34

**Comment by mtdvlpr** [comment]
> I confirm the behaviour. Windows 10 3 screens
> 
> also, i notice that the numeration is wrong based on system > display from windows

The numeration is not meant to correspond to the system display numeration. It corresponds to the position of the screens relative to each other. The numbers represent the order the screens from top-left to bottom-right. We don't have access to the system display numbers.

**Comment by sircharlo** [comment]
Works great on Windows again!
