### ISSUE TITLE
[Bug]: Files Moved to End of Watchtower Section Reorder Incorrectly, Requiring Multiple Moves

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3282]
### What happened?

I was trying to resort files from a public talk to the end of the Watchtower (for example a speaker could be late and Watchtower must be conducted first). First file moved okay, but when I moved the second one, the first bumped into first place of the Watchtower section, and it kept happenning with all the files that I needed to move. So I needed to move them twice

### To Reproduce

1. Move files from the Public Talk Section to Watchtower
2. Try to move the second one

### What did you expect to happen?

To keep the first file in its place

### Version

24.11.1

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Thanks for reporting! This has been fixed in 8b6113623c503c0038a0a7f1110c7e3ede7af0aa and will be in the next release :)
