### ISSUE TITLE
Error downloading media for meeting

### ISSUE THREAD

**Issue by HananiasSQ** [sircharlo/meeting-media-manager#3304]
### What happened?

Updated to the latest and ever since... I get the error downloading media for meeting.
So now I can't access the meeting media. As you can see tonight's meeting is the weekday meeting, but MMM says "Watchtower Study", even though, you can clearly see the images are from "Treasures from Gods word" ... something got mixed up in my MMM and I don't know how to fix. Any help would be amazing! 
I can add videos, but I can't add opening songs on the weekend meeting. 

![Screenshot 2024-11-14 121805](https://github.com/user-attachments/assets/40b0fd76-6ecb-4fdd-9d5e-7e1fb37012f8)

### To Reproduce

3. Do '....'

### What did you expect to happen?

I really just want to update the media automatically and have access to meeting media. 

### Version

24.11.1

### What platform are you seeing the problem on?

Windows

### Screenshots

![Screenshot 2024-11-14 121805](https://github.com/user-attachments/assets/08875803-6afb-42cc-b0f3-6fa1f9090e54)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Hi @HananiasSQ, could you please verify some settings for me:

- Verify that the meeting days are correctly configured under Congregation meetings
- Verify that the website address is correctly configured under Advanced > Danger zone

**Comment by mtdvlpr** [comment]
The website address should be "jw.org" in almost all cases. Unless jwmorg is blocked in your region for example. Then you can fill in an alternative address that points to the homepage of our website.

**Comment by sircharlo** [comment]
I think I'll add some more validation to the baseUrl field. If not a valid two part URL, go to settings and highlight the field. 

⛔️ www.site.com
⛔️ site.com/subdomain
⛔️ s.c
✅ site.com

**Comment by mtdvlpr** [comment]
> I think I'll add some more validation to the baseUrl field. If not a valid two part URL, go to settings and highlight the field.
> 
> ⛔️ [www.site.com](http://www.site.com) ⛔️ site.com/subdomain ⛔️ s.c ⛔️ [empty] ✅ site.com

I wouldn't add too much validation. A proxy server could live on a subdomain for example. This is basically fixed already in the next release:
https://github.com/sircharlo/meeting-media-manager/blob/ac14620b30652b9e42792c572218d9d39caa316c/src/stores/current-state.ts#L97

**Comment by mtdvlpr** [comment]
And this has been improved further with:

https://github.com/sircharlo/meeting-media-manager/blob/ac14620b30652b9e42792c572218d9d39caa316c/src/pages/SettingsPage.vue#L175-L181

**Comment by sircharlo** [comment]
Fair points.

**Comment by sircharlo** [comment]
Possibly fixed by https://github.com/sircharlo/meeting-media-manager/pull/3318.
Please let me know once v24.11.3 is released.

**Comment by sircharlo** [comment]
Please re-open this issue if the problem persists! @HananiasSQ
