### ISSUE TITLE
Enlarge cursor size for jw.org mirroring

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3309]
### Is your feature request related to a problem?

Previous old version of the app had yellow circle around the cursor to make it easier to find and follow for brothers and sisters in the hall

### Describe the solution you'd like

Make the cursor ±2x larger if possible. If not, a similar yellow circle would be also fine.

### Describe alternatives you've considered

Zooming in, but the cursor is still small

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
The old version used a hacky way to simulate a mirror. The mouse events were captured and copied. The mouse on the media window was not a real mouse.

The current version is a real mirror, so there's no way to change something only on the media window.

In short, we could add this (I think), but it would mean that the circle or enlarged mouse is also present on thr website controllet window which you interact with.

**Comment by ux-git** [comment]
I guess it's not a huge deal is brothers will also have the cursor enlarged/highlighted

**Comment by mtdvlpr** [comment]
Implemented in ba6105533088a6da9fc0120ce11743f1c48bb940 and will be in the next release!
