### ISSUE TITLE
Import audio Bible reading

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3317]
### Is your feature request related to a problem?

Use case: Congregation Bible study. A few years ago we have been heavily reliant on audio recordings during this meeting part, but today sometimes A/V team still gets requests to turn on this or that recording. 

### Describe the solution you'd like

A way to add a specific Bible reading segments with selector of chapter and specific verses. 

### Describe alternatives you've considered

Open WOL to avoid conflicts with JWL, but JWL will also work. It's just important to not forget to close it before playing next media item.

### Additional context

Perhaps it would fit well into the main 'Import – from website' window. I just need to come up with a good UI to select specific Bible passages for importing.

For me, this feature is on par with the Study Bible media import—most of the time, you don’t need it, but when you do... it’s stressful to think of all the possible solutions outside of Meeting Media Manager and how to combine them, especially when you have only 1-2 minutes to solve it. Rare use case, but seems like it's possible to implement. So, including it in M³ would be a great help for some congregations. What are your thoughts on this feature?

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by ux-git** [comment]
@sircharlo @mtdvlpr here's the concept:

1) Select the corresponding "Add media" menu item:

<img width="646" alt="Screenshot 2024-11-15 at 21 38 20" src="https://github.com/user-attachments/assets/c33974d2-9dbf-4922-a0a6-ccd6c8ded902">


2) Select a desired Bible book (books for which audio recording is not available should be clearly indicated):

<img width="497" alt="Screenshot 2024-11-15 at 21 30 01" src="https://github.com/user-attachments/assets/c1d2f9f7-99d7-47e6-b60b-38033f829ee3">

3) And then select specific recording you want to import:

• either Bible passage (starting verse, ending verse. With an ability to import recordings between two or more chapters).
<img width="703" alt="Screenshot 2024-11-15 at 21 31 31" src="https://github.com/user-attachments/assets/2d2429e4-8266-452f-869e-8b671410708d">

• or a single Bible verse. That's a rare case, but still might be useful, especially for single verses coming after a passage, e.g. "Matthew 3:1-5; 8".
<img width="474" alt="Screenshot 2024-11-15 at 21 30 26" src="https://github.com/user-attachments/assets/dfcdeba1-79c2-4bc7-a6ef-c0a5942c00c0">

Your thoughts? Did I miss any use case or technical stuff?

**Comment by sircharlo** [comment]
Could I suggest a slightly different flow?

- Book picker (as in screenshot you posted)
- Type picker (One verse or many verses)
  - One verse: 
    - Chapter picker (grid)
    - Verse picker (grid)
  - Many verses: 
    - Start verse - Chapter picker (grid)
    - Start verse - Verse picker (grid)
    - End verse - Chapter picker (grid)
    - End verse - Verse picker (grid)

I feel the grid pickers are friendlier when dealing with numbered items like verses and chapters; perhaps I'm wrong though.

**Comment by ux-git** [comment]
@sircharlo I agree. After trying different grid options and user flows, seems like the following makes it the easiest for the user:

1. Normal Bible book selector with full-length names (as much as it fits, otherwise clip with ellipsis). Similar to song selector, but with re-styled normal, hover, unavailable states. Those can be used as standard for other parts of the app, like import Study Bible media and Songs, to make the all items less emphasized, while the selected clearly stands out. The unavailable ones can simply be skipped, showing only the available books, but it may make the navigation less effective, since the books will be kinda mixed up.

<img width="554" alt="Screenshot 2024-11-21 at 11 59 44" src="https://github.com/user-attachments/assets/93a07f99-7d6f-4338-bad2-9dcacc94860c">

2. The next step covers all the required user scenarios while being even simpler than previous iteration:
2a. **Quick tab navigation** to easily see and switch to a neighboring books in case of misclick. The currently selected tab additionally acts as a current/selected book indicator.
2b. **Chapter and verse grid selector:** Since they're combines in a vertical way, they both will be always visible and accessible. 
2c. If user needs to play only one verse – **click on one and import**. If user needs to play multiple – **select the starting and ending verses** (just like in the calendar selector) and then import.

When hovering over the selected book, the accent-hover color variable can be used to indicate that it can be clicked once more to deselect

<img width="492" alt="Screenshot 2024-11-21 at 13 35 39" src="https://github.com/user-attachments/assets/014148e3-ad98-479c-bb5f-bc3176c9b2eb">

Important point: This window is wider than others, because of the fixed books/chapters container size. Therefore in order to fit the grid without any extra empty space on the right side, the width can be adjusted.

@sircharlo, @mtdvlpr what do you think?

**Comment by sircharlo** [comment]
Being worked on in #3569
