### ISSUE TITLE
CMD + Q won't fully close the app

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3319]
### What happened?

Seems like the bug is back again. The app fully quits only after the second CMD+Q

### To Reproduce

Click the CMD + Q

### What did you expect to happen?

Fully close, now the app is still active, like after clicking the red button.

### Version

v24.11.2

### What platform are you seeing the problem on?

MacOS

### Screenshots

https://github.com/user-attachments/assets/c5215ffd-6b76-4b2c-9cd0-f84e516c1bab

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by ux-git** [comment]
Yup, the quitting does work perfectly! The only downside is that the app quits instantly without any previous warnings. But honestly, it's hard to tell which scenario is worse 😆  I think it's quite hard to accidentally close the app, especially on macOS where the close button is on the left-hand side which doesn't interfere with any often-used UI elements.

**Comment by sircharlo** [comment]
I suppose we could show the same warning as when the user tries to close the main window when appropriate (during a meeting or when media is playing).

**Comment by ux-git** [comment]
Agree, if this won't conflict with using Cmd+Q to fully close the app (even after second confirmation use).

**Comment by sircharlo** [comment]
Implemented in https://github.com/sircharlo/meeting-media-manager/commit/12297e0583e15e0d5acde14be8eca316397d9e98; will be in the next release. Feel free to re-open if the issue presents itself again!
