### ISSUE TITLE
[Bug]: Bugs in the latest version, v24.11.2

### ISSUE THREAD

**Issue by cong862023** [sircharlo/meeting-media-manager#3320]
### What happened?

**Bug 1 (This bug occurs in all weekend meetings):** 
[Please see video 1] 

When we link a folder to monitor new images and videos from speakers, upon adding any multimedia, the "**Add Initial Song**" button disappears. 
This shouldn't happen, as images will naturally be added before the song is set in the app.

**Bug 2 (This bug only occurs during the week of the circuit visit) :**
[Please see video 2] 

When multimedia is added via the "**Add Extra Multimedia**" button in the _Living as Christians_ section, the multimedia is instead placed in the _Circuit Overseer_ section.

### To Reproduce

Please see the videos.

### What did you expect to happen?

Bug 1: The "Add Initial Song" button should not disappear.

Bug 2: Multimedia should be assigned to the correct section.

### Version

v24.11.2

### What platform are you seeing the problem on?

Windows

### Screenshots

**Video 1:**
https://github.com/user-attachments/assets/69c0a2ca-ab00-4134-ada0-68bb68d36f85

**Video 2:**
https://github.com/user-attachments/assets/ac21cb5c-bd02-49ba-9bfc-9f6ffc28c075

### Additional context

_Thank you for these new features, which are very practical for improving planning and coordination for our meetings!_

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
Bug 1 fixed in 6cae330fe2c62ab3f062aabab71918b0ed8547f9.

**Comment by sircharlo** [comment]
Bug 2 fixed in d777e0679fff87cb04e7a45e9837626b0e4e74c4.
