### ISSUE TITLE
[Bug]: First day of the week – 0

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3321]
### What happened?

Wrong field label

### To Reproduce

Open the settings

### What did you expect to happen?

Normal day name

### Version

v24.11.2

### What platform are you seeing the problem on?

MacOS

### Screenshots

<img width="1237" alt="Screenshot 2024-11-14 at 16 17 55" src="https://github.com/user-attachments/assets/dd09b0a2-c877-4d63-8f0a-8bc446b9fde4">

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
Should be a one-time bug; I fixed how days are handled and this is a result of the old method. Try changing the value; you should never see 0 again.

**Comment by sircharlo** [comment]
I still pushed a cosmetic fix in case anyone else has this: d3eeb35226282b2f0df03cbed5c711428bdb2c39.
