### ISSUE TITLE
Add extra media (The extra media loading screen does not disappear after adding media)

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#3332]
### What happened?

I have already tested it on two machines and the problem persists. When adding media using conventional methods or drag and drop, the loading screen remains visible even though the media has already been added.

![image](https://github.com/user-attachments/assets/783e7b52-11a2-46b3-a627-2b49e559e9fc)

### To Reproduce

1. Try to add any media.
2. Use any method to add.
3. Add a media (image or video).
4. The screen shown above remains visible and does not disappear after the media is added.

### What did you expect to happen?

I expected the add media screen to disappear after the media was imported into m3.

### Version

v24.11.3

### What platform are you seeing the problem on?

Windows

### Additional context

_The issue above was also occurring in version 24.11.2._

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.
- [X] If I am using macOS, I confirm that I have executed the Terminal commands found in the <a href="https://sircharlo.github.io/meeting-media-manager/fr/using-at-a-kingdom-hall#additional-steps-for-macos-users" target="_blank">additional steps for macOS users</a> found on the documentation website before submitting this bug report.

**Comment by sircharlo** [comment]
Fixed in 91b64ad53385a8366754e3dfdc801a38a0956726.
