### ISSUE TITLE
Updating media folders after just having cleaned the cache fails

### ISSUE THREAD

**Issue by mh166** [sircharlo/meeting-media-manager#334]
### Describe the bug
Updating media folders after just having cleaned the cache fails. Only after closing the application and opening the app again, it continues to work as expected.

### To Reproduce
1. Go to settings
2. Click on 'Clean media cache'
3. Go back to home
4. Click on 'Update media folders'
5. See error

### Expected behavior
I should not have to re-open the application after cleaning the cache.

### Screenshots
![Error messages as mentionend above](https://user-images.githubusercontent.com/3167596/168794920-98622461-144a-4fd2-9245-cb08ebaac1c1.png)

### System specs
- Windows_NT 10.0.19044
- JWMMF v22.5.5

### Additional context
N/A

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": null,
  "congServer": null,
  "congServerPass": null,
  "congServerPort": null,
  "congServerUser": null,
  "congregationName": "***",
  "disableHardwareAcceleration": null,
  "enableMediaDisplayButton": null,
  "enableMp4Conversion": true,
  "enableMusicButton": null,
  "enableMusicFadeOut": null,
  "enableObs": null,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": true,
  "excludeLffiImages": true,
  "excludeTh": true,
  "includeTeaching": null,
  "keepOriginalsAfterConversion": true,
  "lang": "X",
  "langUpdatedLast": "2022-05-17T10:33:00.844Z",
  "localAdditionalMediaPrompt": null,
  "localAppLang": "en",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": "5",
  "musicFadeOutType": null,
  "musicVolume": null,
  "mwDay": "2",
  "mwStartTime": "19:00",
  "obsCameraScene": null,
  "obsMediaScene": null,
  "obsPassword": null,
  "obsPort": null,
  "preferredOutput": null,
  "weDay": "6",
  "weStartTime": "09:30"
}
```

**Comment by sircharlo** [comment]
Already fixed, slated for next release. See #320

**Comment by mh166** [comment]
Sorry, forgot to take a look at the already closed issues, as well. Thanks for the fix. 😊

**Comment by sircharlo** [comment]
No apologies necessary ☺️ I hope to have the latest update out sometime this week; stay tuned!
