### ISSUE TITLE
[Feature]: Add repeat media button

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3378]
### Is your feature request related to a problem?

Not really. Today I realised that in some cases, especially special meetings, it would make sense to play a looped media before or after such special meeting.

### Describe the solution you'd like

Add a "Repeat" button on the left near the media controls. I would say that it should appear only while hovering over the media item, not permanently for ALL media.

### Describe alternatives you've considered

Play the media once again manually 

<img width="994" alt="Screenshot 2024-11-17 at 16 39 07" src="https://github.com/user-attachments/assets/26f08989-876a-4a8b-a0d8-3cd18da5c730">

### Additional context

I would say that the button should be without the border, similar to the "Delete" one. Any other thoughts?

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by e-Feitosa** [comment]
Do you remember a feature in the previous M3 that was similar to the one you're asking for? It was possible to schedule the first media to start automatically before the scheduled time. The first video would start 2 minutes or 5 minutes, etc., depending on the time adjusted in the settings. I believe it is still a good tool to use in various special events.

**Comment by sircharlo** [comment]
Not a bad idea; I could see this being used for special events. 
As per direction, this would never be used for congregation meetings, so such a feature would only be available for Other profile types.

**Comment by sircharlo** [comment]
Initial implementation for Other profiles in a76e7a0a10ef37e2638ed44d190248ca7b600283.

**Comment by mtdvlpr** [comment]
@sircharlo, jwl playlists have a repeat action for media items. If we implement this feature, we should probably also take over that action when configured.

**Comment by ux-git** [comment]
@mtdvlpr I do actually have an idea of more flexible playlist/section management. After importing more then 15 playlist for a pioneer school, there's a real issue sorting them in a convenient way.

So basically, some kind of sections initially suggested for convention/assembly would make a lot of sense even for other types of special meetings.

The easiest to imaging use case is the pioneer school:
• Two lectors, each has his own playlist/folder with media
• They're switching multiple times a day based on chapters of the book.
• It's important to clearly see the "section" – where exactly a media sequence belongs to (which lector, which chapter, which day)
• Renaming the section should also be easy and fast, as well as drag-n-dropping an entire section to put in the the correct order.

That's the basic needs that I've recently discovered. I'll try to wrap it up into a design feature proposal, most likely it will be another new tab/feature in order to keep the regular media tab simple and easy to use. But let's see what other solutions we can come up with.

**Comment by ux-git** [comment]
@mtdvlpr totally agree about the focus on regular meeting, since it covers 99+% of use cases.

However, M³ definitely has many advantages compared to JW Library-only approach:
1. It is significantly more stable.
2. It works on macOS, so it can be used by brothers who bring their own computers to the school. Often, these are Macs, on which JW Library is not (yet?) supported.
3. While having all folders and playlists is fine, and importing them into JW Library is OK, having all media items (not just the parent playlists) displayed in a well-organized overview sorted in the right order may be much more beneficial. This avoids navigating through multiple folders and prevents sharing a 'messy' screen compared to a clean second display.
4. M³ also has a zoom-in feature 😀, perfect for examining differences between Bible translations, small footnotes, or details in old handwriting
5. For spontaneous Zoom sharing when someone becomes sick, the workload for the responsible brother immediately doubles. If the brother is also a lector, it becomes even more challenging.
6. I'm 100% sure I missed something else

**Comment by sircharlo** [comment]
> @sircharlo, jwl playlists have a repeat action for media items. If we implement this feature, we should probably also take over that action when configured.

I'll put this in a PR a bit later this week.

**Comment by sircharlo** [comment]
> @sircharlo, jwl playlists have a repeat action for media items. If we implement this feature, we should probably also take over that action when configured.

Done

**Comment by mtdvlpr** [comment]
> @sircharlo @mtdvlpr
> 
> While testing the application, I noticed that the strings explaining the feature are swapped.

Thanks! Fixed in a52877c5fdc9260af5775f962adc880883a5e6b8
