### ISSUE TITLE
[Bug]: Quasar platform detection always detects Windows

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#3408]
@sircharlo, do you remember the reason for below lines of code? I think it's causing the Quasar platform detection to malfunction which is the reason the update banner isn't shown on macOS.

https://github.com/sircharlo/meeting-media-manager/blob/ff91a238704ee904fef2ab780465f5c756162512/src-electron/main/window/window-main.ts#L25-L27

**Comment by mtdvlpr** [comment]
Alright, maybe we can apply the same logic here as we do in the session code:

https://github.com/sircharlo/meeting-media-manager/blob/ff91a238704ee904fef2ab780465f5c756162512/src-electron/main/session.ts#L30-L34

**Comment by sircharlo** [comment]
Fixed in 17b9e779b28917589d13860eec507c0e34564472.
