### ISSUE TITLE
[Feature]: Ability to add missing media from jwpub files

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3427]
### Is your feature request related to a problem?

While importing a jwpub file with unlinked videos (e.g. pioneer school media overview file), there are like 20 errors all together. Even though they go away in next few seconds, when video operator should act quickly, those errors blocking the whole app's view.

@sircharlo @mtdvlpr or is there any other workaround to import such tricky files? 

### Describe the solution you'd like

Add "Close all errors" button

### Describe alternatives you've considered

1. Wait, 2. Close one by one

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
Do you have a screenshot?

**Comment by ux-git** [comment]
@mtdvlpr not the same error. Different 20-ish media can't be imported. Basically, the issue is the same, but the videos are different.

**Comment by ux-git** [comment]
Exactly

**Comment by mtdvlpr** [comment]
In the previous version, we had an extra step that would indicate which files are missing with the option to provide those files from the local system. Similarly to how JW Library handles it, but in bulk. We could probably re-introduce this.

**Comment by mtdvlpr** [comment]
@sircharlo 

![image](https://github.com/user-attachments/assets/99a8ea25-598c-45ba-8580-1a07c3bcff4e)

**Comment by mtdvlpr** [comment]
@ux-git, in my case, there was some duplication. Each error was shown 6 times. Also, some file identifier info was missing (docid). I've fixed that in eb7deef8401c7a6f81569f7817e0cc7b53ae26ac

**Comment by sircharlo** [comment]
> In the previous version, we had an extra step that would indicate which files are missing with the option to provide those files from the local system. Similarly to how JW Library handles it, but in bulk. We could probably re-introduce this.

We could reintroduce the missing files step with a streamlined approach. 

- A non-persistent banner could be displayed for that day's media whenever a JWPUB file is imported that has missing media. 
- This banner would show a reactive list of missing videos that haven't been added yet. 
- Each item in the list could include a "Browse" button, allowing the user to select the missing video manually. 
- Once selected, the video would be added to the correct spot, and the corresponding item would disappear from the list. 
- Alternatively, if the user drags and drops a video matching one of the missing files, it would automatically be removed from the reactive list and placed in the correct location.

**Comment by ux-git** [comment]
> We could reintroduce the missing files step with a streamlined approach.

Sounds nice! This one sounds especially user-friendly:

> Alternatively, if the user drags and drops a video matching one of the missing files, it would automatically be removed from the reactive list and placed in the correct location

Is it also possible to inherit the day/chapter dividers in such files? If speaking about the pioneer school: Chapter 1A, Chapter 1B, 2A, 2B, 3A and so on.

But seems like it's some kind of advanced section management. As mentioned earlier I have an idea for another feature in the sidebar that may make all this organizing more flexible. Stay tuned 😄

**Comment by sircharlo** [comment]
This will be in the next update!


> Is it also possible to inherit the day/chapter dividers in such files? If speaking about the pioneer school: Chapter 1A, Chapter 1B, 2A, 2B, 3A and so on.
> 
> But seems like it's some kind of advanced section management for special events. As mentioned earlier I have an idea for another feature in the sidebar that may make all this organizing more flexible. Stay tuned 😄

Indeed, this would be a bit of a bigger refactor. I'll look for your input on this!
