### ISSUE TITLE
[Feature]: Remove the "Added manually" star for the Other meetings; Add a "More" Icon on hover to indicate context menu

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3441]
### Is your feature request related to a problem?

When everything is highlighted, then nothing is highlighted :) 

### Describe the solution you'd like

Remove the star for the Other meetings, since all media there is imported manually. Therefore each media has a star.

### Describe alternatives you've considered

–

### Additional context

All this stars story I've witnessed today in the Kingdom Hall, but right now on Mac I can't see the same stars on the Other-type profile, and I don't even have the icons on the "More" menu which appears on the right click. So perhaps I did something wrong, but not sure. Are Windows and macOS versions different in this approach?

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
> I don't even have the icons on the "More" menu which appears on the right click

Would you mind sharing a screenshot of this

**Comment by sircharlo** [comment]
In the meantime, https://github.com/sircharlo/meeting-media-manager/commit/4817121118b2850b1b8c405133b9a5d7c47e841b will remove the star from media items if Other profile types.

PS I put these icons as placeholders. If ever you have suggestions or see icons that should be replaced, please don't hesitate to point them out!

**Comment by ux-git** [comment]
> Would you mind sharing a screenshot of this?

<img width="1060" alt="Screenshot 2024-11-20 at 23 19 30" src="https://github.com/user-attachments/assets/325dd3e6-4799-42bd-9d7f-c243b0237953">

**Comment by ux-git** [comment]
> I put these icons as placeholders. 

Wouldn't the delete button be a good custom added media indicator at the same time as being a quickly accessible action button?

Also, while using the app today I felt a need to have some kind of indicator that there is a whole big "More" menu, which is not obvious. Perhaps adding a three dots "More" icon on a hover over a specific media item would do the trick? User could then either still do the right click or use the button. But in this scenario it will be more intuitive and obvious that something is hiding inside of each media item.

**Comment by sircharlo** [comment]
> > Would you mind sharing a screenshot of this?

This is an older version! The bleeding edge version has the new menu icons

![image](https://github.com/user-attachments/assets/849688cd-e78e-41df-bb4f-5247bd9461e4)

**Comment by sircharlo** [comment]
> Wouldn't the delete button be a good custom added media indicator at the same time as being a quickly accessible action button?

I'm torn about this. I feel like I want to hide actions that are disruptive (adding media, removing media, renaming media) behind menus, and only have actions related to playback immediately accessible (play, pause). The idea being to streamline the workflow during meetings. and prevent visual overload. What do you think?
 
> Also, while using the app today I felt a need to have some kind of indicator that there is a whole big "More" menu, which is not obvious. Perhaps adding a three dots "More" icon on a hover over a specific media item would do the trick? User could then either still do the right click or use the button. But in this scenario it will be more intuitive and obvious that something is hiding inside of each media item.

I like this idea alot. Where would you see such a three dots icon on hover?

**Comment by ux-git** [comment]
> What do you think?

Yeah I agree. If a feature is not used every meeting, it can be hidden.

> I like this idea alot. Where would you see such a three dots icon on hover?

Right near the play button, this way all the main actions will be grouped and performed on the right hand side of the app. <img width="820" alt="Screenshot 2024-11-20 at 23 49 54" src="https://github.com/user-attachments/assets/8fcd7b20-3251-4560-881d-7dfca80074c3">

But again, I would add it only while hovering, otherwise it will be too much noise on the page.

**Comment by mtdvlpr** [comment]
> Also, while using the app today I felt a need to have some kind of indicator that there is a whole big "More" menu, which is not obvious. Perhaps adding a three dots "More" icon on a hover over a specific media item would do the trick? User could then either still do the right click or use the button. But in this scenario it will be more intuitive and obvious that something is hiding inside of each media item.

Implemented in 7ea3e1102f6857f25b053871287b7b6ab3c34f9d
