### ISSUE TITLE
[Bug]: Different shades of icon background color during using setup wizard

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3442]
### What happened?

The icons have different background, seems to me.

### To Reproduce

Open the setup wizard

### What did you expect to happen?

All the same colors

### Version

v24.11.5

### What platform are you seeing the problem on?

macOS

### Screenshots

<img width="292" alt="Screenshot 2024-11-20 at 22 33 19" src="https://github.com/user-attachments/assets/9b01076d-28a7-4a14-8034-679c6f4787a1">

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.
- [X] If I am using macOS, I confirm that I have executed the Terminal commands found in the <a href="https://sircharlo.github.io/meeting-media-manager/fr/using-at-a-kingdom-hall#additional-steps-for-macos-users" target="_blank">additional steps for macOS users</a> found on the documentation website before submitting this bug report.

**Comment by sircharlo** [comment]
Lighter gray = disabled, probably because you chose "other"?

**Comment by ux-git** [comment]
Oh, I see... Yes I did. Hm, could the app simply remove the unused steps as soon as user chooses the Other option? The setup process then will look way less overwhelming and more predictable.

**Comment by mtdvlpr** [comment]
Implemented in 00bb34882fcca41a902f04c74c895e6785cfb0dd
