### ISSUE TITLE
[Feature return] Ability to stop background music 10 seconds before the meeting

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3447]
### Is your feature request related to a problem?

Now it stops 1 minute before the meeting and it seems too long a silence before the meeting

### Describe the solution you'd like

Return a slider

### Describe alternatives you've considered

Make an input field with seconds 

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by e-Feitosa** [comment]
This occurs due to the guidelines in _S-261 §. 17 and S-179 §.10_, etc

**Comment by dagandrew** [comment]
I thought from the viewpoint of only-zoom meeting where everyone is already seated and ready when connected

**Comment by mtdvlpr** [comment]
> I thought from the viewpoint of only-zoom meeting where everyone is already seated and ready when connected

The direction mentioned is actually about (only) Zoom meetings.

**Comment by dagandrew** [comment]
I understand now, thank you

**Comment by e-Feitosa** [comment]
> > I thought from the viewpoint of only-zoom meeting where everyone is already seated and ready when connected
> 
> The direction mentioned is actually about (only) Zoom meetings.

**The same instruction is found in _S-261_ to turn off microphones 1 minute before the start of the meeting.**
