### ISSUE TITLE
[Feature]: Add hover state to the import drag-and-drop area

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3449]
### Is your feature request related to a problem?

-

### Describe the solution you'd like

The user experience will be improved when the whole area will be clickable, with something like accent-100/200 background color on hover.

<img width="451" alt="Screenshot 2024-11-21 at 10 19 32" src="https://github.com/user-attachments/assets/4c4f6da1-a1f2-4dd1-a8a7-cb062bc44ecc">

Is it doable?

### Describe alternatives you've considered

Aiming the Browse files button

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
Implemented in 3efc0b2d15d7b2ccf23a05622d82f40027bc1a6d
