### ISSUE TITLE
[Bug]: A thumbnail is created when a video is added to the monitored folder

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#3457]
### What happened?

For example using OneDrive....
https://github.com/user-attachments/assets/1ed5f664-edb9-4fb9-b4a4-a5029330d06f

With the video:

https://github.com/user-attachments/assets/1df29814-de88-4437-9ac2-d864fb1fe330

### Version

Latest Version

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.
- [X] If I am using macOS, I confirm that I have executed the Terminal commands found in the <a href="https://sircharlo.github.io/meeting-media-manager/fr/using-at-a-kingdom-hall#additional-steps-for-macos-users" target="_blank">additional steps for macOS users</a> found on the documentation website before submitting this bug report.

**Comment by sircharlo** [comment]
Thanks for reporting this! Fixed in https://github.com/sircharlo/meeting-media-manager/commit/55520d9a31e3c69c188c968a0445f24b8e3c224a.
