### ISSUE TITLE
[Bug]: Deleting media from the added media in a monitored folder does not work.

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#3458]
### What happened?

When right-clicking on media added from a monitored folder, the delete media button appears. When I click, nothing happens.
![388281997-3a1fc631-d0e7-4866-b80d-b97321e2884a](https://github.com/user-attachments/assets/b1cfeae4-4ab0-49f8-ae2b-418455df11bf)

### Version

Latest version

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.
- [X] If I am using macOS, I confirm that I have executed the Terminal commands found in the <a href="https://sircharlo.github.io/meeting-media-manager/fr/using-at-a-kingdom-hall#additional-steps-for-macos-users" target="_blank">additional steps for macOS users</a> found on the documentation website before submitting this bug report.

**Comment by mtdvlpr** [comment]
You can test the fix with this test build:

https://github.com/sircharlo/meeting-media-manager/actions/runs/11954588695
