### ISSUE TITLE
[BUG] lffi video not in the correct place

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#347]
**Describe the bug**
We discovered an edge case for the midweek meeting of this week (16-23 May). When a lff video is mentioned, both in the bible study and in the congregation bible study, the one for the bible study remains and the one for the congregation bible study is ignored.

**To Reproduce**
1. Go to 'week 16-23 May'
2. Click on 'present media'
3. See 'My search for the True God' video as nr 03-01 instead of 07-04

**Expected behavior**
I expect the 03-01 one to be ignored and the 07-04 to be displayed in the list.

**System specs (please complete the following information):**
 - OS: Windows 10
 - App Version 22.5.5

**Comment by sircharlo** [comment]
Nice catch. Fixed [here](https://github.com/sircharlo/meeting-media-manager/commit/2a2d2142a59db58e29c086bba18dce57bbf8e64c).
