### ISSUE TITLE
[Bug]: Scrubbing styling bug

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3480]
### What happened?

On the very start and end the arrow down below is detached from the message background, probably some tricky custom corner radius animation could save the situation.

### To Reproduce

Start a media and hover over the timeline.

### What did you expect to happen?

There shouldn't be the gap

### Version

v24.11.5

### What platform are you seeing the problem on?

macOS

### Screenshots

<img width="440" alt="Screenshot 2024-11-21 at 23 35 08" src="https://github.com/user-attachments/assets/38fb5d78-6255-437e-a201-0b3b037c53f1">

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.
- [X] If I am using macOS, I confirm that I have executed the Terminal commands found in the <a href="https://sircharlo.github.io/meeting-media-manager/fr/using-at-a-kingdom-hall#additional-steps-for-macos-users" target="_blank">additional steps for macOS users</a> found on the documentation website before submitting this bug report.

**Comment by sircharlo** [comment]
Fixed with f0d2178cf25a84330718677703e59be6e8b60fc7!
