### ISSUE TITLE
[Idea]: Swap the LOOP and MORE buttons

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3482]
### Is your feature request related to a problem?

This jumpy behaviour on hover: 

https://github.com/user-attachments/assets/07fe3b77-b958-4239-b3d5-715172cf2f11

### Describe the solution you'd like

By swapping these two buttons, the MORE button won't push the LOOP button. So placing the MORE always left-most would make a lot of sense.

### Describe alternatives you've considered

–

### Additional context

Also, what about changing its color to blue? Right now it attracts too much attention in my opinion, though it's not an info/error indicator.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
Thanks! Implemented in ea38fa8562818a17e6332dffaf64e5b79f66ed0b

**Comment by joaochris** [comment]
> @joaochris, that is intended behavior. The 3 dots "more" button is only visible on hover.

I'm referring to text wrapping ;D

**Comment by ux-git** [comment]
@mtdvlpr well, the More dots yes, but the jumping text definitely creates issues.

Can we calculate the text max width based on the width of the width minus more button?

**Comment by sircharlo** [comment]
> @mtdvlpr well, the More dots are fine, but the jumping text definitely creates issues.
> 
> Can we calculate the text max based on the width of the width minus more button?

I was also thinking about having the more button always there, position absolute, invisible, visible on hover, background gradient transparent to white.

**Comment by ux-git** [comment]
> the more button always there, position absolute

But it should be kind of dynamic, since there might also be a loop indicator. Or isn't it a problem for the text?

**Comment by mtdvlpr** [comment]
How about this? The button always takes the space it needs, but is only visible on hover.

https://github.com/user-attachments/assets/89f19c15-15c2-4cc8-9b1b-2a33d76067ef

**Comment by mtdvlpr** [comment]
How about this? The button always takes the space it needs, but is only visible on hover. I've made the button a little smaller.

https://github.com/user-attachments/assets/b37ff520-3dca-41a8-a70b-211b5795e6b0

**Comment by mtdvlpr** [comment]
> @mtdvlpr great solution!

Implemented in 964a53c82e7d8a49d976f3144931e7e5abfd3074
