### ISSUE TITLE
[Bug]: Wrong name of the portable app version

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3493]
### What happened?

The app is called wrong in the Task Manager

### To Reproduce

start the app and view how it is called in the task manager

### What did you expect to happen?

Meeting Media Manager

### Version

v24.11.5

### What platform are you seeing the problem on?

Windows

### Screenshots

![PXL_20241121_152546286](https://github.com/user-attachments/assets/ad20f7bc-b9c0-4059-8c69-eccb794bdd8c)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.
- [X] If I am using macOS, I confirm that I have executed the Terminal commands found in the <a href="https://sircharlo.github.io/meeting-media-manager/fr/using-at-a-kingdom-hall#additional-steps-for-macos-users" target="_blank">additional steps for macOS users</a> found on the documentation website before submitting this bug report.

**Comment by ux-git** [comment]
Weird, but okay 😬😄

**Comment by mtdvlpr** [comment]
@sircharlo, what do you think? I don't think the description is used anywhere else, so it should be save to change it to `Meeting Media Manager`.

**Comment by sircharlo** [comment]
Let's keep the description as-is. [This is an Electron bug](https://github.com/electron-userland/electron-builder/issues/8599); the fix will be released in time.
