### ISSUE TITLE
[BUG] version 22.5.6 doesn't work

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#352]
**Describe the bug**
After my JWMMF updated to M3 it now only shows a white blank screen with a control menu at the top for refreshing etc.

**To Reproduce**
1. Go to 'JWMMF'
2. Let it update

**Expected behavior**

**Logs**
My terminal gave me the following error:
[9847:0519/182927.459726:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:9810) UnhandledPromiseRejectionWarning: TypeError: win.setAppDetails is not a function
    at createMainWindow (/tmp/.mount_Meetinz5Fe8W/resources/app.asar/main.js:54:7)
    at /tmp/.mount_Meetinz5Fe8W/resources/app.asar/main.js:268:5
(Use `meeting-media-manager --trace-warnings ...` to show where the warning was created)
(node:9810) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Screenshots**
![Screenshot from 2022-05-19 18-33-20](https://user-images.githubusercontent.com/46671786/169351979-9710b758-2346-42b4-bde0-b49037c3d0d6.png)

**System specs (please complete the following information):**
 - OS: Linux 5.13.0-40-generic
 - App Version 22.5.6

**Additional context**

**Comment by sircharlo** [comment]
I keep forgetting that I have Linux users. Sorry..
Building a release that doesn't run that Windows-specific code now, will be released as 22.5.7....

**Comment by mtdvlpr** [comment]
It is not entirely fixed yet unfortunately. It is not breaking anymore though! The error is now displayed on startup each time and when I close the error message, M3 works as intended. 
![Screenshot from 2022-05-19 19-15-39](https://user-images.githubusercontent.com/46671786/169359366-d182c51b-0e6c-4a44-915c-2bb8e99b6c39.png)

**Comment by mtdvlpr** [comment]
I can test the main branch without the need for an official new release to prevent having to release a new version everytime

**Comment by sircharlo** [comment]
Lol no no
I'm just managing 8 things at once and that's what happens when one is distracted

**Comment by sircharlo** [comment]
I'll re-release 22.5.7 momentarily, this one will work, I promise 😆

**Comment by mtdvlpr** [comment]
Oh, lol, know the feeling...Appreciate the quick action very much!

**Comment by sircharlo** [comment]
Of course lol. Try the [latest installer](https://github.com/sircharlo/meeting-media-manager/releases/latest).

**Comment by mtdvlpr** [comment]
Works like a charm! and I can confirm that it cleanup the JWMFF config folder :)

**Comment by mtdvlpr** [comment]
Hi, sorry to bother you again. Turns out the 2nd media screen still gives the mediaWin.setAppDetails error for me. I usually don't use it at home, so I didn't notice until now.

**Comment by sircharlo** [comment]
Do you have a screenshot? I only use `setAppDetails` in two places, and both those places are supposed to be called only on Windows systems. I'm curious.

**Comment by mtdvlpr** [comment]
![Screenshot from 2022-05-20 12-31-54](https://user-images.githubusercontent.com/46671786/169510059-e384d011-9fc4-4aa1-8bc3-347cfc0d3172.png)

**Comment by mtdvlpr** [comment]
It really is only the media window. When I turn that off, I don't get any error in my terminal or otherwise...

**Comment by sircharlo** [comment]
Could you try cloning the repo and running `npm I; npm start`? I just noticed something weird with my version tags and I'm wondering if the fix for line 220 in main.js was actually skipped in the autobuild.

**Comment by mtdvlpr** [comment]
I think you're on to something. I think, because I downloaded the broken 22.5.7 version and it compared it with the fixed it thought it was already running the latest version.

**Comment by sircharlo** [comment]
Ugh. It's what I get for lazily not incrementing version numbers. 

If you can sit tight, I'm gonna release a bugfix version later for #356 anyways. 22.5.8..

**Comment by mtdvlpr** [comment]
Alright, thank you very much!

**Comment by mtdvlpr** [comment]
I'm not in a rush, luckily

**Comment by mtdvlpr** [comment]
While I'm at it. I can't seem to find any logo that you can now disable for presentation mode...

**Comment by sircharlo** [comment]
![image](https://user-images.githubusercontent.com/1275666/169515048-95a1d0a5-70c5-4aac-80f7-883cb5079433.png)

vs.

![image](https://user-images.githubusercontent.com/1275666/169515128-ef25bc57-ff32-4589-a08b-6278d7fe6422.png)

**Comment by mtdvlpr** [comment]
![Screenshot from 2022-05-20 14-47-54](https://user-images.githubusercontent.com/46671786/169531345-c5652eab-5409-4558-9983-ac5342fe43ec.png)

I'm never seeing the logo on Linux...

**Comment by sircharlo** [comment]
Yup. Cause you're on Linux. Which I hadn't forgotten... again.
The logo is pulled dynamically from files made accessible by JW Library, when installed.
Unfortunately, this only works on Windows systems where JW Library is installed.
I'll make sure that settings toggle is hidden for Linux users!
