### ISSUE TITLE
Images are not being projected in the "zoom meeting"

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#355]
My brother, I'm having a problem with the last update. Images are not being projected in the "zoom meeting". The OBS Studio camera image projects normally, but when I go to play the media, OBS Studio does not switch the scene. In short: No media appears in the zoom meeting using the M³ program.

**Suggest**
Taking advantage of this, I would like to suggest the layout of the SCENES similar to the image below, it's not just a matter of aesthetics, it's to make it easier to visualize the scene better. Thankful for your work.

![image](https://user-images.githubusercontent.com/90984283/169421691-b0bd5dbe-61d4-477f-83de-da378a089c17.png)

### To Reproduce
3. Do '....'

### Screenshots
If possible, add screenshots to help explain your problem.

### System specs
- Windows_NT 10.0.22000
- M³ v22.5.7

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": null,
  "congServer": null,
  "congServerPass": null,
  "congServerPort": null,
  "congServerUser": null,
  "congregationName": "***",
  "disableHardwareAcceleration": null,
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": true,
  "enableMusicButton": null,
  "enableMusicFadeOut": null,
  "enableObs": true,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": null,
  "excludeLffiImages": null,
  "excludeTh": true,
  "hideMediaLogo": null,
  "keepOriginalsAfterConversion": null,
  "lang": "T",
  "langUpdatedLast": "2022-05-19T19:03:33.568Z",
  "localAppLang": "pt",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": "60",
  "musicFadeOutType": "smart",
  "musicVolume": "100",
  "mwDay": "3",
  "mwStartTime": null,
  "obsCameraScene": "PALCO GERAL",
  "obsMediaScene": "MIDIAS",
  "obsPassword": "XXXXXX",
  "obsPort": "4444",
  "outputFolderDateFormat": "DD-MM-YYYY - dddd",
  "preferredOutput": null,
  "weDay": "5",
  "weStartTime": null
}
```

**Comment by sircharlo** [comment]
I just tested, and it works for me.
To be sure: 
- Enable OBS compatibility
- Set the stage scene in MMM settings
- Set the media scene in MMM settings
- Start media presentation mode
- Choose any camera scene from menu in MMM: scene changes in OBS
- Play media in MMM: scene changes to media scene in OBS
- Stop media in MMM: scene goes back in OBS to camera scene selected in MMM

At what stage does this not work for you?

**Comment by e-Feitosa** [comment]
Hello, I believe I found the problem, OBS Studio was in "studio mode", so the program does not find the scenes, it used to work, but I have already disabled this function in OBS Studio and now it is functional. Thank you for your time and work on this excellent project.

**Comment by sircharlo** [comment]
Glad to hear the solution!
