### ISSUE TITLE
M3 doesn't auto update on v24.10.10

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#3556]
### What happened?

Explaining to some about the new features, I noticed that several M3s did not receive the update and are still on version v24.10.10. Today, for example, I accessed three computers to assist with camera setup, and indeed, none were updated. I told other acquaintances to check the new features, and they were still on the old version. Could it be a BUG that they couldn't update even with the automatic update option enabled?

### To Reproduce

Check the current version in other locations that use M3.

### What did you expect to happen?

When opening M3, the update notification should appear, and when closing M3, the program should be updated to the latest version. (Note: I am specifically talking about version 2024.10.10, meaning several KHs have this version because there was no update notification.)

### Version

v24.10.10

### What platform are you seeing the problem on?

Windows

### Screenshots

![image](https://github.com/user-attachments/assets/01dd75f8-56f9-41f3-9b0d-5454c59d05f2)

### Additional context

Is there any way to "force" this type of notification informing about the new update?

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
Yes, this is a bug for v24.10.10 specifically that broke the autoupdater. It has been fixed since.

**Comment by mtdvlpr** [comment]
@e-Feitosa, everyone who has v10.10.10 installed are unable to auto update. Please tell everyone you know to update manually this once. The problem only occurred for that specific version.
