### ISSUE TITLE
Thumbnail does not appear, and cannot be displayed

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#356]
Today, on the notebook we used in KH, the photo thumbnail was not showing, nor could it be displayed. We use the server resource.

![photo_2022-05-19_22-22-17](https://user-images.githubusercontent.com/76891864/169430320-237a6944-e702-4f8a-9ac4-247368068547.jpg)

![photo_2022-05-19_22-22-22](https://user-images.githubusercontent.com/76891864/169430329-465cf148-f3ab-4f48-a20d-3ec6a2226abb.jpg)

**Comment by sircharlo** [comment]
Post your prefs file please.

**Comment by joaochris** [comment]
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": null,
  "congServer": "dav.box.com",
  "congServerDir": "/dav/Reuniões",
  "congServerPass": "***",
  "congServerPort": 443,
  "congServerUser": "***",
  "congregationName": "***",
  "disableHardwareAcceleration": true,
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": null,
  "enableMusicButton": true,
  "enableMusicFadeOut": null,
  "enableObs": null,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": true,
  "excludeLffiImages": true,
  "excludeTh": true,
  "hideMediaLogo": null,
  "keepOriginalsAfterConversion": null,
  "lang": "T",
  "langUpdatedLast": "2022-05-19T17:50:37.057Z",
  "localAppLang": "pt",
  "localOutputPath": "C:\\",
  "maxRes": "720p",
  "musicFadeOutTime": null,
  "musicFadeOutType": null,
  "musicVolume": "100",
  "mwDay": "3",
  "mwStartTime": null,
  "obsCameraScene": null,
  "obsMediaScene": null,
  "obsPassword": null,
  "obsPort": null,
  "outputFolderDateFormat": "DD-MM-YYYY - dddd",
  "preferredOutput": null,
  "weDay": "6",
  "weStartTime": null
}
```

**Comment by sircharlo** [comment]
![image](https://user-images.githubusercontent.com/1275666/169433528-cfd38923-370c-43fa-bf5c-29e3c7b3679a.png)

No issues here.

Was the `07-07` file present in the media folder? If so, please post its full name here. 
For example, mine is: 
`07-07 - Conjunto de imagens Cenas do vídeo Minha procura pelo Deus verdadeiro -  1 - Soten sentada debaixo de uma árvore na floresta olha para o céu e ora ao Deus verdadeiro -  2 - Herold ens.jpg`

Also, please right click on this link and copy/paste it in your comment so I can compare the two:
![image](https://user-images.githubusercontent.com/1275666/169433742-4f841d45-4f16-4988-85ce-57d2171daf75.png)

**Comment by sircharlo** [comment]
Perhaps due to the non-breaking space in the filenames? (`\u00A0` or `&nbsp;`)
My language doesn't have these characters in the filenames for some reason.

Try removing all spaces from name and seeing if it works after. If so, it'll give me a hint of what to do.

**Comment by joaochris** [comment]
On my computer it appears normal too. The path is the same as yours. I found this strange, only in his that got this error. I cleaned up the entire server and folders before.

**Comment by joaochris** [comment]
Unfortunately I won't be able to send you the text of the link, the notebook brother is kind of busy kkk. If you want to close this issue, if it happens again, I'll try to get more data.

**Comment by sircharlo** [comment]
If ever you ca test in the future, try deleting all spaces, notably here:

![image](https://user-images.githubusercontent.com/1275666/169434673-f0cbea2e-d89f-46d0-9aad-55f138c9104b.png)

If that still doesn't work, try removing these accented characters:

![image](https://user-images.githubusercontent.com/1275666/169434783-19edb931-7bcc-40ed-972b-000a11e7f88b.png)

I suspect the computer doesn't like one of those two categories.

**Comment by sircharlo** [comment]
Windows 10 or 7?

**Comment by joaochris** [comment]
It could just be something related to that. Because the media appeared in the folder. It's Windows 10.

**Comment by sircharlo** [comment]
I'll look into removing those "special" spaces anyways. And maybe even accented characters too. Just to be safe.

**Comment by joaochris** [comment]
Thanks! I'll take the opportunity to quote another error, it may happen to someone else. When changing the date format, and clicking on the day, the media was not showing. I had to delete everything and restart the program for it to work.

**Comment by sircharlo** [comment]
> I'll look into removing those "special" spaces anyways. And maybe even accented characters too. Just to be safe.

Removed non-breaking spaces as of [here](https://github.com/sircharlo/meeting-media-manager/commit/774ba7e5af07c91754106e8967e350baecc59038).

**Comment by sircharlo** [comment]
> Thanks! I'll take the opportunity to quote another error, it may happen to someone else. When changing the date format, and clicking on the day, the media was not showing. I had to delete everything and restart the program for it to work.

Addressed as of [here](https://github.com/sircharlo/meeting-media-manager/commit/e47e831fbb4283bca751fcccfb19604d8a0cd05a).
