### ISSUE TITLE
[Change Request] catch file too big error and display warning

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#359]
### Describe the bug
When trying to import a public talk video it gave a generic error.

### To Reproduce
1. Go to 'a meeting day'
3. Do 'upload a file bigger than 2gb'

### Expected behavior
I would expect this ERR_FS_FILE_TOO_LARGE error to be caught and a nice clear warning/error explaining that the file needs to be smaller than 2GB (see error details).

I don't need the maximum to be increased, because this was not an official JW stream file. Those are always 1GB max.

### System specs
- Linux 5.13.0-41-generic
- M³ v22.5.7

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": true,
  "congServer": "***",
  "congServerDir": "***",
  "congServerPass": "***",
  "congServerPort": "***",
  "congServerUser": "***",
  "congregationName": "***",
  "disableHardwareAcceleration": null,
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": null,
  "enableMusicButton": true,
  "enableMusicFadeOut": true,
  "enableObs": null,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": true,
  "excludeLffiImages": true,
  "excludeTh": true,
  "hideMediaLogo": null,
  "keepOriginalsAfterConversion": null,
  "lang": "O",
  "langUpdatedLast": "2022-05-20T10:49:37.740Z",
  "localAppLang": "nl",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": "60",
  "musicFadeOutType": "smart",
  "musicVolume": "100",
  "mwDay": "2",
  "mwStartTime": "19:15",
  "obsCameraScene": null,
  "obsMediaScene": null,
  "obsPassword": null,
  "obsPort": null,
  "outputFolderDateFormat": "DD-MM-YYYY - dddd",
  "preferredOutput": null,
  "weDay": "5",
  "weStartTime": "18:00"
}
```

### Error details
```
{
  "stack": "RangeError: File size (2935394418) is greater than 2 GB\n    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)\n    at new NodeError (node:internal/errors:371:5)\n    at tryCreateBuffer (node:fs:419:13)\n    at Object.readFileSync (node:fs:464:14)\n    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9160)\n    at HTMLButtonElement.<anonymous> (file:///home/manoah/Documents/dev/jw-meeting-media-fetcher/media-updater.js:2973:30)\n    at HTMLButtonElement.dispatch (/home/manoah/Documents/dev/jw-meeting-media-fetcher/node_modules/jquery/dist/jquery.js:5430:27)\n    at HTMLButtonElement.elemData.handle (/home/manoah/Documents/dev/jw-meeting-media-fetcher/node_modules/jquery/dist/jquery.js:5234:28)",
  "message": "File size (2935394418) is greater than 2 GB",
  "code": "ERR_FS_FILE_TOO_LARGE"
}
```

**Comment by mtdvlpr** [comment]
Also, it seems the request help button with the generic error does not fill in the assignee and labels. /assign @sircharlo

**Comment by sircharlo** [comment]
2GB! What kind of talks are you watching over there, 4K? 😆 

You're right though of course, I never implemented upper filesize limits. I never assumed that someone would try to upload a file that big. Quit frankly, I don't like my implementation of WebDAV functions, as they require a significant amount of RAM. The bigger the file, the larger the memory footprint.

I think I might migrate to the excellent `webdav` npm package, as it handles file streams elegantly, which is an excellent way of reading and uploading large files without bogging down an app or RAM.
