### ISSUE TITLE
[Bug]: Unable to download the video (week starting 12/23)

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3591]
### What happened?

it says that the media is missing, but you can download it from the website
![image](https://github.com/user-attachments/assets/0a37d3cc-2ecb-4c70-8fa4-0cbfbe026a6b)
and it shows an error like this
![image](https://github.com/user-attachments/assets/8ba2d135-2b38-428f-951a-be1ae6ab293f)

### To Reproduce

3. Do '....'

### What did you expect to happen?

I thought it was something with jwpub, but when you go to JWL it works okay

### Version

latest

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
This has been fixed in baeb1181d3a6e0ce7f03b3a4d8b95ac9d27ffa23 and will be released in time before the 23rd.

**Comment by ux-git** [comment]
@mtdvlpr btw can the app detect the meeting media that are not yet available for download (like certain videos that are available only one week before the meetings), to label them differently? Just to give users the context that it's not an app's failure, but the video is not yet available at all, but will be automatically downloaded as soon as it becomes available.

**Comment by ux-git** [comment]
@mtdvlpr I guess both. The description will also be useful to update since the video can't be directly imported. Users has just to wait and keep calm :)

**Comment by sircharlo** [comment]
> This has been fixed in [baeb118](https://github.com/sircharlo/meeting-media-manager/commit/baeb1181d3a6e0ce7f03b3a4d8b95ac9d27ffa23) and will be released in time before the 23rd.

Slated for release in the coming week!

**Comment by mtdvlpr** [comment]
> @mtdvlpr I guess both. The description will also be useful to update since the video can't be directly imported. User has just to wait and keep calm :)

I'm not that familiar with the current fetching logic (yet). @sircharlo, if you feel it's worthwhile, could you implement this?

**Comment by sircharlo** [comment]
> > @mtdvlpr I guess both. The description will also be useful to update since the video can't be directly imported. User has just to wait and keep calm :)
> 
> I'm not that familiar with the current fetching logic (yet). @sircharlo, if you feel it's worthwhile, could you implement this?

Without going into too many specifics, I won't be able to do this without significantly complicating the underlying logic and methods used for media extraction. I feel the current approach of showing the slot where the media will go is sufficient to help most media operators troubleshoot the issue. 

Would it be worth it to have a link to open the relevant meeting page in WOL?

**Comment by ux-git** [comment]
@sircharlo well, yeah... Seems like the 5% of improvement with 95% of the effort. 

I think the link to the corresponding program on WOL would make sense with a context of "Please double check the availability of the video on the WOL. If it's currently not available, the app will automatically download it as soon as it becomes available".

**Comment by sircharlo** [comment]
> @sircharlo well, yeah... Seems like the 5% of improvement with 95% of the effort.
> 
> I think the link to the corresponding program on WOL would make sense with a context of "Please double check the availability of the video on the WOL. If it's currently not available, the app will automatically download it as soon as it becomes available".

I'll do some research to see if this is feasible.
