### ISSUE TITLE
[Feature]: Ability to precisily cut longer videos 

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3593]
### Is your feature request related to a problem?

I'm frustrated that you can't cut down to the second the video when it's like 30 minutes, it allows only 7 second increments, and if the video is 1 hour it will be like 14 seconds.

### Describe the solution you'd like

it would be nice if you could click on the time above the slider and turn it into input therefore edit it manually there
![image](https://github.com/user-attachments/assets/889361cd-c3c2-455c-b586-a02cd1e7ff12)

### Describe alternatives you've considered

if you want to use only a slider to cut the video, you could also increase the width of the video cutting frame (so it would be alsmot the size of the main window), so the increments could be smaller, but there would be 2-4 seconds if the video is long enough (not perfect of course, but bearable)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
> Alternatively, the start-end time on the sides of the slider can be converted into input fields to allow manual input that is accessible and relatively intuitive.

I think I like that option!
