### ISSUE TITLE
[Bug]: Next media shortcut don't go to Watchtower section

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3594]
### What happened?

When you you press Next media shortcut when you are on the last item of Public Talk section it goes back to the first item of itself 

### To Reproduce

1. Upload the video to the Public Talk section
2. Play the item
3. Stop it or wait until it stops at the end
4. Press Next Media Item shortcut

### What did you expect to happen?

It should go to the Watchtower first item.

### Version

latest

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
Great catch! Fixed in 717c122f7e2999a60c034c8f3b0a41ca16bb2489.
