### ISSUE TITLE
[Change Request] when importing media, auto adding it to local folder

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#360]
**Describe the bug**
When you import some custom media, it gets uploaded to the congregation server, but afterwards you still need to fetch media and then it will download it from the cloud. This seems redundant since the file is already on the computer

**To Reproduce**
1. Go to 'a meeting day'
2. Click on 'custom'
3. Do 'add some media'
4. Go to media presentation
5. See that the added media is missing

**Expected behavior**
I will love it if the custom media could be added to the local folder immediately during the upload process. This way it is immediately available in the presentation mode and you can't forget to fetch the media again.

**Priority**
Low, it's a nice to have.

**Comment by sircharlo** [comment]
I can see where that could be useful. 
I've pushed a commit that copies the uploaded file to the local folder when appropriate.
