### ISSUE TITLE
[Feature]: Select different path for media cache directory

### ISSUE THREAD

**Issue by adrianodaddiego** [sircharlo/meeting-media-manager#3615]
### Is your feature request related to a problem?

It is currently not possible to specify a custom directory for the media cache. This creates a problem for users who want to store data on a secondary drive, for example, to optimize for space or performance.

### Describe the solution you'd like

Users should be able to define a custom path for the media cache during the initial setup process. This would allow more flexibility for managing storage locations right from the start.

### Describe alternatives you've considered

If there is a workaround is appreciated.  The "extra" folder feature, while useful, does not fully address this need.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
Great idea! @mtdvlpr has implemented this and it is now available in the latest version, v24.12.0!
