### ISSUE TITLE
[Docs]: Add portable version link to the documentation Downloads page

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3639]
### Is your feature request related to a problem?

-

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
Done in c040c1aca6bc3d13a9098e37bb24494db8bb194e
