### ISSUE TITLE
Elapsed and remaining time of a video

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#3651]
### Describe the solution you'd like

Could you return the count of elapsed and remaining time for a video just like it was in the previous version?

![IMG_20241205_202900](https://github.com/user-attachments/assets/7bd3a7e1-7cf3-4f90-b1f7-bb1a29c88f2a)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
Being worked on in https://github.com/sircharlo/meeting-media-manager/pull/3661.
