### ISSUE TITLE
[Bug]: No loading indicator – Study Bible import

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3665]
### What happened?

There's no loading indicator. For slow disk computers and slow internet connection this created a few moments (or like a minute for the first load sometimes, this happened to me on a slow machine too) a confusion 'Are the media loading or not at all?"

### To Reproduce

-

### What did you expect to happen?

A circle loading indicator in the middle would be fine

### Version

v24.12.0

### What platform are you seeing the problem on?

Windows

### Screenshots

![image](https://github.com/user-attachments/assets/0033296a-27d3-4f6c-a9c7-fc452e1b51c4)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Fixed in 7dcfb4d062fde718ea67624e536cd30301366bf3
