### ISSUE TITLE
[Feature]: Unify the Songs and Audio Bible grid styling

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3666]
### Is your feature request related to a problem?

At the moment, two features with similar scenarios have different grid styling:

Songs: All the songs are accent-main, making 'everything in focus' = overwhelming.
![image (2)](https://github.com/user-attachments/assets/950c686b-dee4-40ff-a821-947a5bc8614a)

Audio Bible: All the books have a secondary color applied, which is good (but hover can be improved):

![image (3)](https://github.com/user-attachments/assets/a1f1f599-2ca4-4d90-8d1e-b662b69ca394)

### Describe the solution you'd like

1. Use the Audio Bible styling for the songs too
2. Can you adjust to have the same grey-ish accent for normal state, but apply 'accent-main' for hover state, making it more noticeable on displays with worse picture contrast/quality.
3. I believe there's a question "What hover to use for the selected items, which already accent-main are?". You can try using the alternative darker accent options, as I recall there's even an 'accent-hover' variable available.

### Describe alternatives you've considered

-

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
Let me know what you think after 8cdb64a42ae4d5ce8b039655356807aa456d65e5.
