### ISSUE TITLE
[Bug]: Unable to search the UI languages with the keyboard input

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3669]
### What happened?

The UI selector doesn't support the keyboard input for quicker search

### To Reproduce

1. Create new congregation 
2. As a first step click in the language selector
3. Try to use keyboard to find a other language 

### What did you expect to happen?

Ger/Deu → suggest german
Uk → suggest Ukrainian

Etc

### Version

v24.12.0

### What platform are you seeing the problem on?

Windows

### Additional context

A similar search does already work for the media language during next step(s) as I recall.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
Done! be4602e6d58a64ed9e30dc2ccd1bf8e3ee618911
