### ISSUE TITLE
[Bug]: Can't scroll the Media Downloads list

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3671]
### What happened?

The list can't be scrolled with the mouse wheel. Also, has it always been a horizontal scroll?

### To Reproduce

Open the downloads sync window

### What did you expect to happen?

1. To be able to scroll it with the mouse wheel.
2. Can also be horizontal, is you find it more convenient than vertical.

### Version

v24.12.0

### What platform are you seeing the problem on?

Windows

### Screenshots

![17335960040976297434272314519692](https://github.com/user-attachments/assets/41aa43e5-09ee-4b6e-b349-ae115bdb8586)

### Additional context

On macOS I can do a horizontal scroll with no problem. On Windows I can click the mouse wheel to scroll to the left, but with a normal scrolling (most user expected behaviour) it won't work.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
Fixed in 788a91419a1d1b488cb7fadc593e1a7d4d7f217a.
