### ISSUE TITLE
[Feature]: Less sensitive image zooming speed

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3677]
### Is your feature request related to a problem?

Right now it's quite easy to go too far into the image. It's hard to zoom one step in, the image rather zooms in with 3-4 zooming steps skipped (when I'm trying to move my fingers only by a few millimeters) or way more when zooming naturally.

Here on the video I did my best to zoom in as little as possible. Managed to do that only with the + button though 😆

https://github.com/user-attachments/assets/96d05ec6-b536-4a7f-aaeb-85e71e06091d

### Describe the solution you'd like

Would it be possible to lower the sensitivity of the zooming? Then it will require more scrolls to get it right, but hopefully it will be more harder to accidentally zoom in too much. 

### Describe alternatives you've considered

• Very, VERY slowly and pinch in on trackpad. Sometimes it works. I'm not fully sure about the mouse experience for other users though. Feel free to share your thoughts in the comments down below.
• Use + and - buttons. They work fine, no complaints, but since there's the zooming, perhaps it could be fine-tuned?

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
Should be fixed as of 2aca8f31b47981d3a5da137ded8bb13c9d3a8b66
