### ISSUE TITLE
[Bug]: Smaller 'About the app's icon

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3678]
### What happened?

Nothing critical, just for the a) visual balance, and b) to provide more space for the "Automatic updates" text.

### To Reproduce

Not an error, but easy fix

### What did you expect to happen?

I'm not sure how big the current icon is, but something like 48px or around that number could work well. Something definitely smaller than now, but feel free to adjust as per your visual taste.

### Version

v24.12.0

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Implemented in a6360dabb06b6be4b7ee2132ac79e3afaacedf39
