### ISSUE TITLE
[Bug]: Media item pops out if the title is one long word in small windows

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3679]
### What happened?

The video has a long one word name. In my case it was document_5379649509804501526.mp4

### To Reproduce

3. Do '....'

### What did you expect to happen?

So the item wouldn't pop out

### Version

24.12.0

### What platform are you seeing the problem on?

Windows

### Screenshots

![image](https://github.com/user-attachments/assets/0e52b705-af5c-4d35-b628-69e853174e2a)
![image](https://github.com/user-attachments/assets/cfa1c013-e7e1-43c8-9bc1-21e523d01aff)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
Fixed in f4c4881bed5da4b0e338b041555a7b7aa59a615a.
