### ISSUE TITLE
[BUG] no play button

### ISSUE THREAD

**Issue by riemsesy** [sircharlo/meeting-media-manager#368]
**Describe the bug**
after creating the list and fetching the media I can't continue because there is no button to go to the media play section

https://1drv.ms/u/s!AsP333xoEE8AiQzSCct252n4xq56

latest jwm3
windows 10

**Comment by sircharlo** [comment]
Enable media presentation mode in settings

**Comment by riemsesy** [comment]
ah.. I understand that.. When I turn that off I use JWm3 only to _download_ the media, And to use the downloaded media in combination with ie. VLC.

case closed

**Comment by sircharlo** [comment]
Exactly! Some use M³ as a pure fetcher or downloader (for example, if meetings are still 100% remote); some use it as a media downloader and presenter. Everyone can enable just the features they need.
