### ISSUE TITLE
[Bug]: Renaming media items is laggy

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3680]
### What happened?

it is lagging, maybe because of it happening live (you can see the changes in the main window before you pressed 'save' button)

### To Reproduce

1. Press rename the media item
2. Type something

### What did you expect to happen?

Typing without any lagging for such a simple task and see changes only after you pressed 'save' button. By the way if you renamed an item, then 'reset' the name and press rename again, it will show your pre-reset name.

### Version

24.12.0

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
Yeah, I noticed this too.

@mtdvlpr do you know why the `emit` calls are so laggy? Even setting the 'loop mode' takes about 1 second. If I change the prop directly (I know I know, it's bad practice) it's immediate. Is there something wrong with the logic somewhere?

**Comment by mtdvlpr** [comment]
> @mtdvlpr do you know why the `emit` calls are so laggy? Even setting the 'loop mode' takes about 1 second. If I change the prop directly (I know I know, it's bad practice) it's immediate. Is there something wrong with the logic somewhere?

I'm not sure. I'd have to do some debugging.

**Comment by mtdvlpr** [comment]
I couldn't figure out why it's so lagging, but I changed the logic to only apply tag and title changes when pressing save. That should at least solve the lagging while typing/clicking.
