### ISSUE TITLE
[BUG] After update, version 22.5.7 won't open and doesn't work

### ISSUE THREAD

**Issue by VOGUK** [sircharlo/meeting-media-manager#370]
Hi there, the software just updated to the latest version this morning and sadly will not open or work. 

When we launch the app, we normally get the white screen, then the animated gear and then the regular user interface. However, when updated the software this morning, we only got the white box with nothing else in it and it stalls on that permanently. 

I checked the Windows Task Manager and the app does not appear to have any problems running, it just can't get past the opening white screen.

I was wondering if you have any ideas as to how to resolve this issue? We had to use the share screen on Zoon this morning and using this software is so much better, so we hope the issue can be resolved soon.

We are running Windows 10 Pro with all the latest updates installed.

**Comment by sircharlo** [comment]
Could you hit Ctrl-Shift-i when that happens, to get the debugging view? Let me know if you see any errors in the Console view please.

To get it to work again, try resetting the preferences?
Delete both the `C:\Users\Username\AppData\Roaming\jw-meeting-media-fetcher` and `C:\Users\Username\AppData\Roaming\meeting-media-manager` folders.
