### ISSUE TITLE
[Bug]: Correct color variables?

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3705]
### What happened?

1. What about using the accent-main color for the new update notification. I suppose the current cyan color is some kind of standard Electron palette or something?
<img width="1254" alt="Screenshot 2024-12-09 at 22 40 01" src="https://github.com/user-attachments/assets/4658cb8c-1a1c-4f97-8148-594d702625a1">

2. Does drag and drop import hover state color have both dark and light values? Seems like light blue is used for light theme, and then the same one used for the dark theme. Correct me if I'm wrong.
<img width="678" alt="Screenshot 2024-12-09 at 22 40 28" src="https://github.com/user-attachments/assets/6065d923-b9bb-4bbc-9648-580dc4b274e5">

### To Reproduce

–

### What did you expect to happen?

Just checking if the correct color tokens are applied

### Version

v24.12.0

### What platform are you seeing the problem on?

macOS

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
1: fixed in dd6bb341b1af00f5ad24f611ffaee10ea93719e4
2: light uses `rgb(237, 243, 255)` and dark uses `rgb(100, 110, 120)`

**Comment by mtdvlpr** [comment]
But the entire color configuration is not in sync with the figma color definitions, so that could use a refactor.
