### ISSUE TITLE
[Bug]: New min-height for import modal windows

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3706]
### What happened?

On the 24.12 version, seems like all the import modal windows are way taller. For many of them it works fine, expect for the S-34 import

### To Reproduce

Open the Public talk media import

### What did you expect to happen?

The window height to depend on the content height

### Version

v24.12.0

### What platform are you seeing the problem on?

macOS

### Screenshots

<img width="682" alt="Screenshot 2024-12-09 at 22 43 04" src="https://github.com/user-attachments/assets/35816682-6603-492a-8c2b-7d9be07078da">

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
You're right; logic improved for min-height vs pretty scroll as of 952080b1fa670e8c2c7c817fb5c3b575cb49ab48.
