### ISSUE TITLE
[Bug]: videos treated as images when length not defined in metadata

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3707]
### What happened?

When importing custom media (tried 5 different files), it's imported as images (?) with no pause, timeline and even timestamp on the thumbnail.

### To Reproduce

Import a custom media and play it

### What did you expect to happen?

To behave like every video used to

### Version

v24.12.0

### What platform are you seeing the problem on?

Windows

### Screenshots

<img width="1245" alt="Screenshot 2024-12-09 at 22 50 33" src="https://github.com/user-attachments/assets/d98b75b3-89f6-4cec-88c8-3f273f7eccda">

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
![image](https://github.com/user-attachments/assets/f4d62460-ad95-449c-bc34-d51ba830013c)

I just tried and it worked fine for me; what kind of files are you trying to import? (extension, origin, etc.)

**Comment by ux-git** [comment]
@sircharlo all of them were mp4 – from meeting recordings to other videos from the computer storage.

Restarting the app didn't help. I'll try to reproduce this more times to find any reasons that may cause the bug

**Comment by ux-git** [comment]
For now I can reproduce this weird behaviour only with videos recorded with OBS. Quite weird, and I see no reason, since it's just an mp4 file that has no other issues other than importing into M³

**Comment by mtdvlpr** [comment]
Could you share a demo video where this behavior happens?

**Comment by ux-git** [comment]
@mtdvlpr this is the latest 24.12.1 version

https://github.com/user-attachments/assets/adcc005b-caa2-432b-a710-50bdae68b920

**Comment by mtdvlpr** [comment]
@ux-git, could you share a video file that we can test ourselves? A video file that gets imported as image.

**Comment by mtdvlpr** [comment]
@ux-git, I found the issue and fixed it in 75e6ca5be7c309c17d189cfcca0fea1efb86ae28 :)

The video length was missing from the video metadata, which caused it to be treated as an image.

<details>
<summary>Video is correctly added:</summary>

![image](https://github.com/user-attachments/assets/3a8c87bb-c750-4b69-88dc-0e549dc1cb4a)

</details>

<details>
<summary>Video gets treated as image:</summary>


![image](https://github.com/user-attachments/assets/cccea529-ee81-48f0-a661-02917a42e1e6)

</details>

**Comment by ux-git** [comment]
Well done! Thanks for fixing!
