### ISSUE TITLE
[Bug]: Display select – inherit the tallest button height

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3708]
### What happened?

This will help to make the UI more friendly to languages that use long words

### To Reproduce

Open the Display settings

### What did you expect to happen?

The middle button to follow the height of the tallest button in the row

### Version

v24.12.0

### What platform are you seeing the problem on?

Windows

### Screenshots

<img width="439" alt="Screenshot 2024-12-09 at 23 04 51" src="https://github.com/user-attachments/assets/f83ff4f3-5b53-4958-82de-5ba7eaa17554">

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Fixed in a2048c5c93879ec7f8415d243958854d6fa8d18a
