### ISSUE TITLE
[Feature]: Media import progress indicator

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3709]
### Is your feature request related to a problem?

Media import window is the only place I suppose, where instead of spinning progress indicator is used the full-height progress bar. I have nothing against progress bars, but with such tall element not all users may perceive it as a progress bar.

<img width="697" alt="Screenshot 2024-12-09 at 22 49 04" src="https://github.com/user-attachments/assets/3a433956-764a-410a-8c3d-f6558b92f32c">

### Describe the solution you'd like

Perhaps using the spinning loader is just a bit more consistent and familiar solution? Or am I missing any downsides?

### Describe alternatives you've considered

First few times I though it's a big or something 

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
Good catch; fixed in b1166e9df8d48a210779ba02443dc1457e47aeaa!
