### ISSUE TITLE
[Feature]: jw.org Video import – minor loading indicator adjustment

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3710]
### Is your feature request related to a problem?

Right now there's a loading indicator at the top left corner. At first it seems to be connected to the sign language toggle near it, but then I started thinking that it's just an overall video loading progress. 

And when the load is complete, the inducator is gone which causes a UI with the toggle and label to jump to the left side.

### Describe the solution you'd like

If I'm right and this indicator is related to the whole video list, is it possible to consider moving it to another place, like the title of the window for example, to be more logically connected to the specific thing that is currently loading.

### Describe alternatives you've considered

It's fine even as it is now, but after using the feature multiple times I just started noticing the jump, and then the indicator.

### Additional context

<img width="508" alt="Screenshot 2024-12-09 at 22 47 10" src="https://github.com/user-attachments/assets/f173a78c-0a5b-4934-a61c-5c4f1d68be5d">
<img width="431" alt="Screenshot 2024-12-09 at 22 46 53" src="https://github.com/user-attachments/assets/b3829808-a390-4635-a02f-b32733f778ab">

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
Fixed in a1547a0f83e41b16dedb2d9d699760b1db1113f4.
