### ISSUE TITLE
Allow icons in scene selector to be optional

### ISSUE THREAD

**Issue by edssan-13** [sircharlo/meeting-media-manager#3736]
### Is your feature request related to a problem?

Previously, the OBS scene selector only used the scene name. After many wonderful updates, scenes now have the scene name along with a corresponding icon. Although I find it very beautiful and useful, there are cases where the difficulty in viewing, a small monitor or having many scenes configured could make the letters even smaller along with the icon. So making the icons optional would perhaps be a good improvement.

### Describe the solution you'd like

Suggestion: Create a configuration to add or remove icons in OBS scenes and leave only the words a little larger for quick reading.

![Seletor com ícones](https://github.com/user-attachments/assets/611eaec3-10e2-49b8-8ffe-d2b8b2b06f61)

### Describe alternatives you've considered

.

### Additional context

.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by e-Feitosa** [comment]
Liked the idea. Taking advantage of the MEDIA scene, previously did not appear in this list of M3. @sircharlo, it would be interesting to hide this listing or put as optional have the MEDIA scene.

**Comment by mtdvlpr** [comment]
> Liked the idea. Taking advantage of the MEDIA scene, previously did not appear in this list of M3. @sircharlo, it would be interesting to hide this listing or put as optional have the MEDIA scene.

@e-Feitosa, #3232 might be what you're looking for. Currently when you select a scene, that scene will immediately be active (even if a video is playing). When this happens you need to be able to switch back to the media scene. #3232 is a feature which you can enable that delays the scene switching until after the media has finished playing (like the old version). In that mode, the media scene doesn't have to be selected ever and is therefore hidden.

**Comment by sircharlo** [comment]
In the meantime, also added a toggle to hide icons from the OBS switcher in 71479b6fe44abf92d11f0244f7698ee3d2be994c.
