### ISSUE TITLE
[Bug]: Double-clicking to go fullscreen stopped working

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3739]
### What happened?

When you double-click on Media Player it tries going, but only does a flash and doesn't open fullscreen

### To Reproduce

3. Do '....'

### What did you expect to happen?

To go fullscreen

### Version

24.12.1-beta5

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
I've fixed the glitching in 2892be8583c4049a878b570e5c0c5aad72b28ea8. Are you using one screen? We don't support a fullscreen media window when you're using only one screen. That is intentional.

**Comment by dagandrew** [comment]
Yes, I'm using one screen

**Comment by mtdvlpr** [comment]
This has been fixed in `v24.12.1-beta.6`
