### ISSUE TITLE
[Change Request] Misleading progress bar for custom video start/stop

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#374]
### Describe the bug
When you set a custom video ending, the progress bar still displays the progress as if it were the original length.

### To Reproduce
1. Go to 'media present'
2. Click on 'a video'
3. Do 'set a custom end time'

### Expected behavior
The progress bar should use the custom start en end numbers to calculate the progress.

### Screenshots
![Screenshot from 2022-05-27 10-44-58](https://user-images.githubusercontent.com/46671786/170664781-53858a17-5b1a-4e98-a3c7-2714ae9e2fb8.png)

### System specs
- Linux 5.13.0-44-generic
- M³ v22.5.7

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": true,
  "congServer": "***",
  "congServerDir": "***",
  "congServerPass": "***",
  "congServerPort": "***",
  "congServerUser": "***",
  "congregationName": "***",
  "disableHardwareAcceleration": null,
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": null,
  "enableMusicButton": true,
  "enableMusicFadeOut": true,
  "enableObs": true,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": true,
  "excludeLffiImages": true,
  "excludeTh": true,
  "hideMediaLogo": null,
  "keepOriginalsAfterConversion": null,
  "lang": "O",
  "langUpdatedLast": "2022-05-20T10:49:37.740Z",
  "localAppLang": "nl",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": "60",
  "musicFadeOutType": "smart",
  "musicVolume": "100",
  "mwDay": "2",
  "mwStartTime": "19:15",
  "obsCameraScene": null,
  "obsMediaScene": null,
  "obsPassword": "JWorg",
  "obsPort": "4444",
  "outputFolderDateFormat": "DD-MM-YYYY - dddd",
  "preferredOutput": "window",
  "weDay": "5",
  "weStartTime": "18:00"
}
```

**Comment by sircharlo** [comment]
Considering that the video itself isn't cut, but that M³ is just starting and stopping the video at specific times, I wasn't sure that making the progress bar 0-100% correspond to the custom start/stop times was the best way to go.

As it is right now, the progress bar displays the whole video length, but the user is unable to skip to points before/after the start/stop times.

What are your thoughts on this?

**Comment by mtdvlpr** [comment]
Alright, I can understand that. In that case, the optimal solution would be to somehow visualise the part of the progress bar that the custom duration involves. For example, if the video will stop halway the full video, the forst half of the progress bar should be different from the other half. Maybe grey out the second half or make the first half a brighter color. This is not taking into account any technical hurdles  so if you feel like it's more effort than it's worth, I get that.

**Comment by mtdvlpr** [comment]
Or another visualization would be to have landmarks on the begin and start time, like a little A and B above or below the progress bar. Or red dots (similar to thr blue dot)

**Comment by sircharlo** [comment]
Potentially adressed with https://github.com/sircharlo/meeting-media-manager/commit/d2f160864497419092b790f195247289e3a190d3

We can go from there.
