### ISSUE TITLE
[Bug]: Adding Bible audio recording doesn't cut the audio

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3740]
### What happened?

It just adds the full audio file, maybe it's because of new changes with video cutting and displaying time?

### To Reproduce

3. Do '....'

### What did you expect to happen?

I expected to get only one or multiple verses from a certain chapter

### Version

24.12.1-beta5

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by ux-git** [comment]
Just tested this on v24.12.0 – it works fine on this version.

**Comment by mtdvlpr** [comment]
This has been fixed in `v24.12.1-beta.6`
