### ISSUE TITLE
[Bug]: Time range background color – Audio Bible

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3743]
### What happened?

With the current red color it's hard to see the exact time stamps.

### To Reproduce

Import an Audio verses and observe

### What did you expect to happen?

I understand the point of highlighting the badge with red, but I think that making the progress bar red is enough to attract the attention. Moreover, the badge shows the start and end verse, making it stand out even more compared to other media items. 

That said, I think making the badge normal black would do its job (alternatively, the black color could have less opacity if the white time stamps are still unreadable on top of the white thumbnail text.).

### Version

v24.12.0

### What platform are you seeing the problem on?

macOS

### Screenshots

<img width="160" alt="Screenshot 2024-12-12 at 16 08 05" src="https://github.com/user-attachments/assets/2d8f9156-cffe-4eb6-8deb-cd11d015e516" />

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by ux-git** [comment]
@mtdvlpr by the way, do you think that it would be beneficial to open the verse selector after clicking the time range edit button? This way users will be able to just select different verse instead of guessing a specific time code.

**Comment by mtdvlpr** [comment]
> @mtdvlpr by the way, do you think that it would be beneficial to open the verse selector after clicking the time range edit button? This way users will be able to just select different verse instead of guessing a specific time code.

I think it would, but this is not an easy fix I imagine. Something for the roadmap, perhaps.
