### ISSUE TITLE
[Feature]: Playback timeline color imoprovements

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3744]
### Is your feature request related to a problem?

Since the media playback timeline has been updated with the "Pause to rewind" tooltip, the media timeline has also became single color (vs previous main blue for played part vs secondary for remaining part) which made it a bit harder to navigate.

<img width="556" alt="Screenshot 2024-12-12 at 16 18 24" src="https://github.com/user-attachments/assets/4d895dbe-9837-4512-b464-49e99616c917" />

This also arose the question about bringing the playback current time back, which I agree is useful to see. 

### Describe the solution you'd like

1. Keep the playback head blue, as well as the past time
2. Have the current time above of the playhead in the normal state
<img width="130" alt="Screenshot 2024-12-12 at 16 10 42" src="https://github.com/user-attachments/assets/4462eecf-cfea-4a89-98ce-c7f282ae55a7" />
3. On hover, change the current time to "To enable scrubbing, the video must be paused"

By doing so, the playback will look normal most of the time, but will also inform user how to enable scrubbing when needed.

### Describe alternatives you've considered

–

### Additional context

**Additional points about the media item styling.** 
_Is it overall possible to set different colors for the timeline and media badge only for the click state?_ I'm asking because at the moment click state creates some minor ux conflicts:

4. Badge has the same color as the click state background. Instead of creating another color value, is it possible to re-paint the badge one-step-higher on the accent colors grade (e.g 300 instead of 200) to maintain the necessary contrast when temporarily using a much darker background color?
<img width="145" alt="Screenshot 2024-12-12 at 16 26 59" src="https://github.com/user-attachments/assets/7863fe70-8eff-4d06-b691-ede7c9dcace9" />

5. Similar issue with the playback timeline. We used to have it one-step-lower color variable (which worked great during a normal state), but now it's a) too dark for the normal state as I find it, b) creates no difference between past and upcoming timeline parts. So if you could re-paint the timeline to one-step-higher secondary color value, and then make it darker like now only during the clicked state, that would be wonderful. The point no. 1 should partially solve this issue, but having proper click state recoloring would be better.
<img width="168" alt="Screenshot 2024-12-12 at 16 29 23" src="https://github.com/user-attachments/assets/9e718eb4-a0c0-402d-aa3f-79da8ed08e7b" />

The same reasoning here – most of the time it will look great, with some temp adjustments only when needed.

Alternatively, we can introduce another color variable for click state for example, but there'll still be a gap in the contrast as I can imagine.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
I've fixed the progress bar color and removed the thumb while playing (the tooltip is still available on hover)

![image](https://github.com/user-attachments/assets/f8e4d7c8-d267-448f-a836-2c98f0902986)
