### ISSUE TITLE
[Feature]: Button shadow colors

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3746]
### Is your feature request related to a problem?

Today I introduce the most minor design proposal in the entire history of Meeting Media Manager 🎉

A ~~small~~ nano touch, but it just adds to the overall design experience. The app is already too good, so all the further adjustments might looks small and minor but still make some difference. 

Right now the button shadows are dark and make them look a bit dirty according to color theory. I won't be even upset if you 'won't-do' this, but if you wish to make the UI even better... 

### Describe the solution you'd like

1. Move the shadow's color shade to the blue for blue buttons
2. Move the shadow's color shade to the red for red buttons

<img width="578" alt="Screenshot 2024-12-12 at 17 03 01" src="https://github.com/user-attachments/assets/d6782fa4-2d07-480d-a0a1-ddadfb72ef5b" />

**I found the following colors to work well:**
#335EAB 40% opacity
#A32929 40% opacity

### Describe alternatives you've considered

–

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
That's not supported by Quasar and overwriting it requires overwriting the entire box-shadow property instead of just the color, so I'd say this is more trouble than it's worth.

**Comment by ux-git** [comment]
Totally makes sense. Then maybe someday, when Quasar supports it.
