### ISSUE TITLE
Add MP4 conversion utility to convert a meeting's media to MP4 for use with Zoom sharing

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#3750]
Just recently, we had to meeting in Zoom only, because of a storm that made it unsafe to go outside. I had to use the old version with the MP4 conversion feature to be able to easily present the media through Zoom from a laptop at home without a second screen. 

We can combine this feature with the export folder feature to make the export folder contain the converted MP4 files.

**Comment by sircharlo** [comment]
Working on this in https://github.com/sircharlo/meeting-media-manager/pull/3756
