### ISSUE TITLE
Add ability to present JW Stream links

### ISSUE THREAD

**Issue by Hans4M** [sircharlo/meeting-media-manager#3757]
### Is your feature request related to a problem?

For our branch territory we have an upcoming Special talk that will be streamed over JW Stream and adding a feature that will allow us to present JW Stream in the same way we do with JW.org will enable us to streamline AV operations.

### Describe the solution you'd like

Just as you can input the address of the official website into the app, add an optional ability to put in the stream address allowing you to present the JW Stream website, but also forgets the details of your account for security.

### Describe alternatives you've considered

As of now to present the stream website, I go to the present website tab then present the Jw.org website. I then scroll to the bottom of the website where I log into JW Pub and present JW Stream from there. The issue with this is that the log in process is presented to everyone. 
![WhatsApp Image 2024-12-14 at 07 48 42_6fc38a83](https://github.com/user-attachments/assets/b45bde82-8fbd-462e-b69a-c536d287e51b)

### Additional context

Alternatively we can still use the option I've been using but have the ability to not present the website presentation immediately allowing for the AV brothers to go through the log in process and put the Stream on standby.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
I've started on a feature that allows you to navigate the website before presenting it on the media window in #3758

**Comment by Hans4M** [comment]
Thanks, will be appreciated. Also during presentation of the stream we noticed that when one minimizes the web control window, the stream paused, meaning it has to be on top of other apps/windows to avoid interruptions of the stream. Is it possible for it to run in the background?

**Comment by mtdvlpr** [comment]
> Thanks, will be appreciated. Also during presentation of the stream we noticed that when one minimizes the web control window, the stream paused, meaning it has to be on top of other apps/windows to avoid interruptions of the stream. Is it possible for it to run in the background?
> 

I'd have to look into it, but it sounds like a feature of jw stream itself. Does this happen when you open the stream in a regular browser?
