### ISSUE TITLE
[Feature]: Improve beta version indication

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3769]
### Is your feature request related to a problem?

Right now the big red circle behind the logo looks like an error indicator. 

<img width="121" alt="Bildschirmfoto 2024-12-17 um 13 15 34" src="https://github.com/user-attachments/assets/813f494a-7366-48f3-8254-998c50d44174" />

### Describe the solution you'd like

Add a 'Beta' badge to the logo to attract enough attention but not too much and right away indicate why is it even red – because it's a beta version and user has to be careful.

Something like this: 
<img width="358" alt="Bildschirmfoto 2024-12-17 um 13 11 08" src="https://github.com/user-attachments/assets/31c679b9-6656-42a6-ab5c-a08f01342565" />

### Describe alternatives you've considered

Clicking on the icon to find out why it's read

### Additional context

Perhaps such an indicator would also be useful on the app icon of beta versions to distinguish it more clearly from the stable version. If the beta works well, you might forget that it's a beta :) 

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
The red could also indicate that auto updates are disabled. If either auto updates are disabled or beta updates are enabled, the red is shown. How would you like that to be visually shown?

**Comment by mtdvlpr** [comment]
I do like the idea of a beta logo. Would you want that beta logo only in the top header or also as the application icon (as seen in the taskbar / application menu)?

**Comment by mtdvlpr** [comment]
Maybe something like this:

- A beta version is installed: app icon has beta banner
- Beta updates are enabled: beta badge on top header logo
- Auto updates disabled: orange-ish icon badge on top header logo

Quasar badge component: https://quasar.dev/vue-components/badge

**Comment by mtdvlpr** [comment]
Btw, when you disable auto updates on Windows/Linux and a new version becomes available, you'll see a banner (the same one macOS will always show for new versions). So warning that auto updates are disabled is not that important if it becomes too visually cluttering.

**Comment by ux-git** [comment]
> A beta version is installed: app icon has beta banner
Beta updates are enabled: beta badge on top header logo
Auto updates disabled: orange-ish icon badge on top header logo

Exactly. Sounds good!

> So warning that auto updates are disabled is not that important if it becomes too visually cluttering.

If we use either auto-updates diabled OR beta version badge at once, the UI must be fine, with enough indication for both types of users. But we can start with the beta badge ans see if that's sufficient.

**Comment by e-Feitosa** [comment]
Really this red logo was a little bit out of order, I would suggest also some change, something like the letter B in the logo to differentiate. _**Excellent suggestions.**_

**Comment by mtdvlpr** [comment]
This is what I've got so far. The warning icon is a placeholder until we have a updates-disabled icon.

![image](https://github.com/user-attachments/assets/f0157df7-e8db-470a-8d0a-c3fac6e9c3fa)

![image](https://github.com/user-attachments/assets/1d14bd06-2e32-46b9-a5da-b1f8c2505112)

**Comment by ux-git** [comment]
@mtdvlpr taking a fresh look, maybe more saturated yellow and red would be better? What do you think?

**Comment by ux-git** [comment]
What do you think about having a beta version icon simply visually very different to the stable version's icon instead of trying to incorporate the beta or even β symbol? I've tried multiple versions with the text, but they just don't look right in my opinion. 

That said, we can try to deliver the beta-idea in a visual way without explicitly saying this. Something like this might work for example. What do you think @mtdvlpr @sircharlo ?

<img width="430" alt="Screenshot 2024-12-18 at 21 04 09" src="https://github.com/user-attachments/assets/57e47b90-255d-44da-8f7f-44a38d94c74f" />

<img width="644" alt="Screenshot 2024-12-18 at 21 33 28" src="https://github.com/user-attachments/assets/a34d4166-6983-4a23-b3a6-5e0063fe97bb" />

**Comment by ux-git** [comment]
The 'Updates disabled' icon is already in the UI Kit by the way @mtdvlpr

**Comment by mtdvlpr** [comment]
I personally like number 4 (maybe with a regular B instead of the β). I'm curious what @sircharlo thinks.

![image](https://github.com/user-attachments/assets/45bca38f-5700-4155-aed5-a94d6054af63)

**Comment by sircharlo** [comment]
Oh man. I **love** number one... 
Could it have a beta Indicator right in the centre?

**Comment by ux-git** [comment]
@sircharlo 
<img width="1207" alt="Screenshot 2024-12-19 at 11 35 19" src="https://github.com/user-attachments/assets/8329a7d6-2b8e-4f23-817e-c9219dd707c3" />

**Comment by ux-git** [comment]
And I guess the ultimately selected app icon can also be used in the app's toolbar? Since it's clearly says 'Beta', it would be a good indicator as well. What do you guys think?

**Comment by mtdvlpr** [comment]
@ux-git, thank you for putting so much effort into all these different designs! They all look amazing. If I may share my humble opinion again, I think `beta` is a lot clearer than `β`. I like numbers 4 and 5.

**Comment by ux-git** [comment]
@mtdvlpr I do agree. My favourites are 2 for its simplicity, 5 for being clear, and 7 for being extra clear :D

**Comment by mtdvlpr** [comment]
> And I guess the ultimately selected app icon can also be used in the app's toolbar (but with no stroke and rounded corners, only the white layers)? Since it's clearly says 'Beta', it would be a good indicator as well. What do you guys think?

I think it depends on whether we want a clear distinction between "a beta version is installed" and "beta updates are enabled".

The beta app icon is a great way to say "a beta version is installed". If we use that same icon in the toolbar as a "beta updates are enabled" indicator, it might not be clear that it signifies something else.

**Comment by sircharlo** [comment]
> @sircharlo <img alt="Screenshot 2024-12-19 at 11 35 19" width="1207" src="https://private-user-images.githubusercontent.com/80993061/397341428-8329a7d6-2b8e-4f23-817e-c9219dd707c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTU0MDksIm5iZiI6MTczNDYxNTEwOSwicGF0aCI6Ii84MDk5MzA2MS8zOTczNDE0MjgtODMyOWE3ZDYtMmI4ZS00ZjIzLTgxN2UtYzkyMTlkZDcwN2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEzMzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNmFiOGY3OTNjMTI4YTk3YzZkOWE0MTc2MTcyZDQ4OTAzZTk3YTJmNWY1NTY5NzQ4ZmI4MTBiOWMwYWYyNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ktsgxdbJoHl3etr17e9OfGoY4ht_sbbyaWS5_RycJb0">

I like 4!

**Comment by ux-git** [comment]
Ok, great. The icons are ready for export

**Comment by mtdvlpr** [comment]
Implemented in b3713034068481e311d1fdbb1118eae8d5805e55

**Comment by yulianitarahma** [comment]
hard crosing make media converter so slowly

**Comment by sircharlo** [comment]
> hard crosing make media converter so slowly

Что? Sorry I didn't get that...
