### ISSUE TITLE
[Feature]: Code Sign and Notarize macOS app

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#3804]
### Is your feature request related to a problem?

Currently macOS users have to execute 2 Terminal commands in order to install and use M³. That is rather difficult for regular users.

### Progress

- [x] Set the following environment secrets in the repo:
  - MAC_CERTIFICATE_BASE64 (as shared)
  -  MAC_CERTIFICATE_PASSWORD (as shared)
  - KEYCHAIN_PASSWORD (random string)
  - APPLE_ID (as shared)
  - APPLE_TEAM_ID (as shared)
  - APPLE_APP_SPECIFIC_PASSWORD (as shared)
- [x] Create workflow to automatically sign and notarize app
- [ ] Test a fresh install
- [ ] Test an update from unsigned to signed
- [ ] Test an update from signed to signed

### Resources

- https://www.electronforge.io/guides/code-signing/code-signing-macos#obtaining-signing-certificates
- https://medium.com/@sdqumar09/electron-macos-code-signing-github-actions-and-locally-e7f0c62211d6
- https://dev.to/rwwagner90/signing-electron-apps-with-github-actions-4cof
- https://github.com/electron/notarize?tab=readme-ov-file#usage-with-app-specific-password

**Comment by sircharlo** [comment]
Done!

**Comment by mtdvlpr** [comment]
@sircharlo, please take a look at https://github.com/sircharlo/meeting-media-manager/actions/runs/12419096153/job/34673682981#step:7:1.

I'm logging the length of the variables, but they return 0. Are we using the same names?

**Comment by sircharlo** [comment]
I think you just fixed it ;)
