### ISSUE TITLE
[Feature]: Option to Delete More Than One Media at a Time

### ISSUE THREAD

**Issue by edssan-13** [sircharlo/meeting-media-manager#3811]
### Is your feature request related to a problem?

I noticed that when we add several media, for example for a public speech, there is no quicker way to delete them all at once. If, for example, we add a playlist by mistake and it has a lot of media, we will have to delete them one by one. It is not very difficult to do this when there are few media, but in a situation with a lot of media it would be interesting to have a simpler and faster option.

### Describe the solution you'd like

As a suggestion, it might be interesting to create a way to select all media at once and delete them in bulk. But if you find it interesting, you can develop this idea.

![Exclusão de Mídias Em Massa](https://github.com/user-attachments/assets/2b899e37-45ab-47e8-9c2d-59e002577d6d)

### Describe alternatives you've considered

.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
Hi @edssan-13, this feature already exists :)

Take a look at the "Add media" menu at the top when you have extra media in the list. The last option will be "Delete all extra media".

**Comment by mtdvlpr** [comment]
![App - Media - Header](https://github.com/user-attachments/assets/fa12df59-0612-48b4-a06f-b9b9a7a503c8)

**Comment by edssan-13** [comment]
@mtdvlpr wonderful!!! I really hadn't noticed. Once again, thank you and congratulations on your great work. The program is getting better every day.
