### ISSUE TITLE
[Bug]: Integrated Obs scenes on M3 sometimes get messed up

### ISSUE THREAD

**Issue by edssan-13** [sircharlo/meeting-media-manager#3812]
### What happened?

I noticed that even when we update to a new version, the scenes get messed up. Sometimes they keep working, but sometimes they don't. Then we need to integrate the scenes again. Although it's quick and easy to configure again, the person who configures the M3 is not always the same person who will be taking care of the application during a meeting. I also noticed that when we close and open the M3, the scenes get messed up, at least visually.

### To Reproduce

.

### What did you expect to happen?

If possible and not too much work, I suggest keeping the original configuration of the OBS integrated scenes, even after an update.

### Version

v24.12.2-beta.5

### What platform are you seeing the problem on?

Windows

### Screenshots

![Cenas OBS com embaralhadas](https://github.com/user-attachments/assets/f5bd674b-dc18-48c3-9c4a-d6c82e2a2685)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Hi @edssan-13, thank you for your report! Could you verify something for me? Please check if those long combinations of characters that you've marked in the screenshot change everytime or if they stay the same.

**Comment by edssan-13** [comment]
Oi @mtdvlpr I noticed that the characters remain the same. I took the opportunity to update to the latest beta version and still the characters remain the same. As I said before, sometimes in addition to the characters becoming misconfigured, the scenes also stopped working, having to select each one again. But this last time it didn't happen.

**Comment by mtdvlpr** [comment]
Thank you for testing! The visual bug has been resolved in 585fc0db77032796a6bda41f40dec1fbdfdb5dd8. This might also fix the obs scenes not working, but I'm not sure. You can test this in about 11 hours when the next beta is automatically released.
