### ISSUE TITLE
[Feature]: Question Update of the text of the year

### ISSUE THREAD

**Issue by edssan-13** [sircharlo/meeting-media-manager#3818]
### Is your feature request related to a problem?

As the year 2025 approaches, I would like to know if there is any way for the text of the year to be updated as soon as the last scheduled meeting is completed or as soon as the year ends. I know there is a custom background that we can use manually, but I wanted to know if there is already a way to ensure that the text of the year changes promptly in an automated way. Maybe it is not even an improvement, it is more of a question I have about how this works in m3.

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
The yeartext is automatically retrieved (when not yet present) and displayed for the current year. This means that as of January 1st, 2025 at 12:00:00 AM, the 2025 yeartext will be retrieved and displayed the next time that the app is opened.
