### ISSUE TITLE
[Bug]: Dragging a media item to the top doesn't enable autoscroll

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3820]
### What happened?

When you dragging a media item to the bottom of the window, it autoscrolls down, but you can't do the same to the top and you need to drop the item, then scroll, and drag again (and if there are a lot of items, do this again multiple times)

### To Reproduce

3. Do '....'

### What did you expect to happen?

I expected that it would autoscroll itself

### Version

24.12.12.2-beta.7

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
That's the same behavior exhibited by Chrome. I believe it may be a WebKit bug unfortunately.

**Comment by dagandrew** [comment]
Then we'll wait 😀

**Comment by mtdvlpr** [comment]
Fixed in 7e0803ac84eee969ce6837fb57b8ab9f5dda5a4d
