### ISSUE TITLE
[Bug]: Next media shortcut on the visit of the circuit overseer

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3821]
### What happened?

Next media shortcut on the visit of the circuit overseer (weekend meeting) goes after public talk to final talk media items instead of Watchtower ones

### To Reproduce

3. Do '....'

### What did you expect to happen?

To go on the first item in the Watchtower section

### Version

24.12.12.2-beta.7

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by dagandrew** [comment]
And then if you went through all items of Watchtower section it doesn't go to the next section

**Comment by dagandrew** [comment]
I've checked again and it seems that if you add song number 5 at the end of the meeting, everything works great! But only this song, huh. So strange.

**Comment by sircharlo** [comment]
Fixed in fee34786be36918edbd1cca8d8b658eb6b17d51d.
