### ISSUE TITLE
[Feature]: The ability to drag videos by their thumbnails, but not pictures, is confusing

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3822]
### Is your feature request related to a problem?

I believe that it should be consistent

### Describe the solution you'd like

Allow drag pictures by their thumbnail and use a key to hold and drag pictures from side to side when zooming (for example hold Ctrl and mouse to move it when zoomed)

### Describe alternatives you've considered

Disallow dragging videos by their thumbnails

### Additional context

Or maybe allow dragging (changing positions) with a hotkey

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
Sort-of fixed as of 3cf7f8a197a289c61fda71ff0802c05314e397f1, whereas non-zoomed thumbnails will behave like video thumbnails. Let me know if this improves the experience for you.

**Comment by dagandrew** [comment]
Yeah, it's even better I think
