### ISSUE TITLE
[Feature]: Auto-focus on song input field when entering song-picker

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3823]
### Is your feature request related to a problem?

You need to click on the field, it's one extra step

### Describe the solution you'd like

It would be great if you could immediately enter the song from the keyboard after clicking Song button from the Import menu

### Describe alternatives you've considered

Maybe do the same with video picker from the website? End after entering a number pressing Enter to pick the first one out of filtered ones would be so smooth 😀 

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
The autofocus has been implemented in d685e7e6355178454fac052aace8b1829e25c1c3

The "Enter to pick the first" can be done by "Tab > Tab > Enter"
