### ISSUE TITLE
[Bug]: Hiding multiple items at once

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3824]
### What happened?

Sometimes there are a lot of items in Apply yourself to the field ministry part and there are times that none of them are shown. And I noticed that you can pick a media item and then press Ctrl and pick another or Shift to pick till the end and then you can drag them at once, but when you do the same and right click on any of the items only that one is hidden. 

### To Reproduce

3. Do '....'

### What did you expect to happen?

To hide all of the selected

### Version

24.12.2-beta.7

### What platform are you seeing the problem on?

Windows

### Additional context

And maybe I'd you selected multiple items and right click you could delete Rename and Edit tag, because renaming all of them at once is not necessary

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Thank you for posting! This is intended behavior. The multi select is a feature of the drag library that we use. This can't easily be re-used for other purposes like bulk hiding.

**Comment by dagandrew** [comment]
Thank you for answering! Of course, I understand, it's not that important
