### ISSUE TITLE
[Bug]: If you set maxRes to 480p it downloads videos in 360p 

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3825]
### What happened?

In English it works as it should, but in Russian and I checked Spanish too it downloads in 360 although the videos in 480 are available

### To Reproduce

3. Do '....'

### What did you expect to happen?

Downloading them in 480 if they are available

### Version

24.12.12.2-beta.8

### What platform are you seeing the problem on?

Windows

### Screenshots

![image](https://github.com/user-attachments/assets/4406fa96-dd34-46ac-82b6-349b516458cf)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Fixed in 515f34c12d746123e69049febb3cfb77c1b27b2a
