### ISSUE TITLE
[Bug]: M3 no longer appears on my notebook desktop

### ISSUE THREAD

**Issue by edssan-13** [sircharlo/meeting-media-manager#3831]
### What happened?

Something strange is happening. I use a notebook connected to two monitors and whenever I open the M3 program, it opens on the screen of one of the monitors that I usually use. In the last few days, I had to remove the monitors and only the notebook remains. However, when I open the notebook now without the monitors connected, the M3 program continues to remember the position it was in before and continues to open as if it were with the additional monitor. Even though I know that the M3 is open, I cannot access it because it is hidden. Other programs open normally on the only available and existing screen. In the case of the M3, this is not happening. It continues to remember the last position when there was an additional monitor but that now no longer exists.

### To Reproduce

.

### What did you expect to happen?

.

### Version

v24.12.2-beta.8

### What platform are you seeing the problem on?

Windows

### Screenshots

![Captura de tela 2024-12-22 203255xxx](https://github.com/user-attachments/assets/09128dc9-1d28-4342-ae5d-af0b15c71729)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by e-Feitosa** [comment]
The m3 is behind the year text on the second screen.
You can open the video properties and swap the two monitors

![image](https://github.com/user-attachments/assets/c3ad5367-0050-4a30-a430-607fafae20ec)

**Comment by edssan-13** [comment]
@e-Feitosa thanks for the suggestion. But as I said before, there are no other monitors connected. Therefore, this screen does not appear for me at the moment. Only when I have more monitors. As far as I have tested on other computers, the M3 program and the media player should appear on the only existing screen. In fact, what you mentioned has also happened to me on the KH computer.

**Comment by edssan-13** [comment]
I just adjusted the screen scale from 100% to 125% and after that the program and others that were hidden appeared again. I didn't really understand what happened but it solved it.😅

**Comment by mtdvlpr** [comment]
> I just adjusted the screen scale from 100% to 125% and after that the program and others that were hidden appeared again. I didn't really understand what happened but it solved it.😅

If I understand correctly, it wasn't just M3 that was hidden and therefore this bug report can be closed. If I'm wrong or the issue persists, feel free to open it again.
