### ISSUE TITLE
[Feature]: Indicate bible parts downloading status

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3836]
### Is your feature request related to a problem?

Upon first Study Bible import all other tabs are inactive due to ongoing sync process. As I noticed they appear one by one, depending on the media files size for each specific tab. But the issue is that with slow internet connection user might create a false impression that other tabs are simply unavailable for using in the app.

<img width="1107" alt="Screenshot 2024-12-15 at 16 39 47" src="https://github.com/user-attachments/assets/065dbf1b-a08a-4274-a2fe-260fc3d07750" />

### Describe the solution you'd like

Is it possible to add e.g. spinning indicators for each individual tab? Then the indication will be more flexible and provide more necessary context to avoid confusion.

### Describe alternatives you've considered

Wait long time to start seeing new tabs step-by-step

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by sircharlo** [comment]
I think this should be improved as of 16032ce1766d35cdb6dd8ceea7f350899474083a. Looking forward to your feedback!
