### ISSUE TITLE
[Feature]: Adaptive layouts in settings for smaller windows

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3838]
### Is your feature request related to a problem?

I use one screen so that means the main window is narrow and some elements in Settings page look bad.

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/1e9c0e85-1bd5-470b-9b03-9b58bb81fb17)
It would be great if when the window is narrow the select field could be under the settings description not to the side.

### Describe alternatives you've considered

and keyboard shortcuts could be under too 
![image](https://github.com/user-attachments/assets/db2927ef-5465-4060-9750-f981c8934ed6)

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
Implemented in 72f17f022de32e4c416c9c07183444a0893cc1b7

**Comment by mtdvlpr** [comment]
Improved in 58b4676ddb22abe684cd1eab61f4f72de883e68c
