### ISSUE TITLE
[Bug]: Notification app name

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3839]
### What happened?

I see 'electron.app...' in the notification header
![image](https://github.com/user-attachments/assets/6d4b519a-7f4d-4535-886f-027e86d52b8b) and I guess Media Playback has the same issue
![image](https://github.com/user-attachments/assets/480d4344-cc4a-46d3-941d-46d03c97fd61) and I think the icon is missing because other apps have them 
![image](https://github.com/user-attachments/assets/3846934b-9771-4a0b-9d76-a03d926bbf3e)

### To Reproduce

3. Do '....'

### What did you expect to happen?

To see the name of the app

### Version

24.12.12.2-beta.9

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Fixed in 02a5fe89f84b96f0ba18f136c59799d4c7f9d042
