### ISSUE TITLE
[BUG] Unlocked cong prefs still displayed as locked

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#401]
### Describe the bug
When I unlocked a congregation wide setting (to change the mw meeting day for the circuit overseer) and immediately went to the meeting settings the setting was still displayed as locked, even though I could change it.

### To Reproduce
1. Go to 'Settings'
2. Click on 'congregation wide settings'
3. Do 'lock/Unlock the mw day setting'

### Expected behavior
I would expect the visual aids to match the actual state of the preference

### Screenshots
![Screenshot from 2022-07-01 13-11-51](https://user-images.githubusercontent.com/46671786/176884500-ea237452-88aa-4a64-ab6f-6767c1a8cf28.png)

As you can see in the image, another day is clickable and it does work. It is just the visual cues that don't match.

### System specs
- Linux 5.13.0-51-generic
- M³ v22.6.3-alpha

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": true,
  "congServer": "***",
  "congServerDir": "***",
  "congServerPass": "***",
  "congServerPort": "***",
  "congServerUser": "***",
  "congregationName": "***",
  "disableHardwareAcceleration": null,
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": null,
  "enableMusicButton": true,
  "enableMusicFadeOut": true,
  "enableObs": true,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": true,
  "excludeLffiImages": true,
  "excludeTh": true,
  "hideMediaLogo": null,
  "keepOriginalsAfterConversion": null,
  "lang": "O",
  "langUpdatedLast": "2022-05-20T10:49:37.740Z",
  "localAppLang": "nl",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": "60",
  "musicFadeOutType": "smart",
  "musicVolume": "100",
  "mwDay": "1",
  "mwStartTime": "19:15",
  "obsCameraScene": "Spreker",
  "obsMediaScene": "Media",
  "obsPassword": "JWorg",
  "obsPort": "4444",
  "outputFolderDateFormat": "DD-MM-YYYY - dddd",
  "preferredOutput": "window",
  "weDay": "5",
  "weStartTime": "18:00"
}
```

**Comment by mtdvlpr** [comment]
You're right! It's working as intended. False alarm :)

**Comment by sircharlo** [comment]
Glad to hear it!
