### ISSUE TITLE
obs-websocket mismatch & Sign Language improvements

### ISSUE THREAD

**Issue by mvpapen** [sircharlo/meeting-media-manager#475]
### To Reproduce
3. Do '....'

### Screenshots
If possible, add screenshots to help explain your problem.

### System specs
- Windows_NT 10.0.22622
- M³ v22.8.1

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": null,
  "congServer": null,
  "congServerDir": null,
  "congServerPass": null,
  "congServerPort": null,
  "congServerUser": null,
  "congregationName": "***",
  "disableHardwareAcceleration": null,
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": null,
  "enableMusicButton": true,
  "enableMusicFadeOut": true,
  "enableObs": true,
  "enablePp": null,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": true,
  "excludeLffiImages": null,
  "excludeTh": null,
  "hideMediaLogo": null,
  "keepOriginalsAfterConversion": null,
  "lang": "E",
  "langUpdatedLast": "2022-10-09T22:36:28.762Z",
  "localAppLang": "en",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": "20",
  "musicFadeOutType": "smart",
  "musicVolume": "39",
  "mwDay": "3",
  "mwStartTime": "19:00",
  "obsCameraScene": null,
  "obsMediaScene": null,
  "obsPassword": "4mvp@home",
  "obsPort": "4455",
  "outputFolderDateFormat": "YYYY-MM-DD - dddd",
  "ppBackward": null,
  "ppForward": null,
  "preferredOutput": null,
  "weDay": "6",
  "weStartTime": "10:00"
}
```

**Comment by mtdvlpr** [comment]
Hi @mvpapen, after updating OBS to v28, obs-websocket has probably been updated to v5 which is not yet supported by M³. There are two options for you. You can install the [beta version of the next M³](https://github.com/mtdvlpr/meeting-media-manager/releases/tag/v22.9.0-beta.1) release which does support obs-websocket v5 or you have to install [obs-websocket 4.9.1-compat](https://github.com/obsproject/obs-websocket/releases/tag/4.9.1-compat) so that your new OBS version uses the old obs-websocket plugin.

**Comment by mtdvlpr** [comment]
Keep in mind that the beta version is a beta version. Although it is quite stable and has been tested extensively already, it is not **yet** an official release. The beta version will eventually be released here and then you will automatically receive the newest version with obs-websocket v5 support, but I cannot give you a date for when that will happen.

**Comment by mtdvlpr** [comment]
See https://github.com/sircharlo/meeting-media-manager/issues/451#issuecomment-1232065386 for more information on how to install obs-websocket 4.9.1-compat

**Comment by mvpapen** [comment]
Thank you, much appreciated. Using Stream deck for now as a work around.
Works great

**Comment by mvpapen** [comment]
where do I find the download for the beta version?

**Comment by mtdvlpr** [comment]
You can find it [here](https://github.com/mtdvlpr/meeting-media-manager/releases/tag/v22.9.0-beta.2)

**Comment by mvpapen** [comment]
Thank you. tried Beta, got further but still does not work.
tried older websocket 4.9.1  with beta version. Still some conflict, but M3
opens and is fully functioning.! very good
I will try downloading previous version of OBS. maybe that will work.
Thank you for a great program.

**Comment by mtdvlpr** [comment]
You have to turn on "use v4" off. It's on by default to prevent people who upgrade from experiencing a break in obs suddenly. Under settings > application setup > obs you can turn off use v4 and then the latest obs-websocket will work.

**Comment by mvpapen** [comment]
Works! Yeah. Win 11 original M3 version and websocket 4.9.1

**Comment by mvpapen** [comment]
Hi there. Started using Beta..... I love it.
I don't even want to introduce v22.8 to the congregation
one Bug I found for ASL use of the app....

1 ..after  playing media it *does not return to the previously selected
sourc*e: like CAM 1. or 2
It goes to the "year text" .  In most cases for Hearing congregations that
is just fine.
But for ASL they would like it to go back to Camera...so  that the last
chosen camera is back  on the main screen. In our congregation they look at
the screen all the time.
I try to get ASL on board to switch over to M3. Could that be an "option "
under "Media Setup"?  on- off slider ...go back to the last selected
source( no pressure but ASL are  very particular )
Thank you again. This is a great program
Location: Walnut Creek ,California, 4 congregations-2English-1Russian-1ASL

**Comment by Chipperchap** [comment]
So in your case, at the present time, the booth would have to click on the M<sup>3</sup> "Stop Display" button after each media presentation. That will show the ZOOM dual screen on the auditorium screens which displays the camera that is showing to the ZOOM friends (assuming you are also using the hybrid method). I guess there would need to be some kind or ASL (or any sign language) override option to not default to the yeartext.

**Comment by mvpapen** [comment]
thank you
2 more thinks
1ASL does not want to see the year text.
how can I change the year text for an individual account?
when I changed it,  it changed for all accounts!
2 Alt- Z is taken by GeForce experience, it brings up an error every time I
start the app.
How can I work around that.
Thank you

**Comment by mtdvlpr** [comment]
Hi @mvpapen, just to be sure. After showing media, you want the yeartext/media screen to disappear until media is selected again? That can be arranged. I can also add an option to override the default shortcuts (ALT+Z, ALT+D). The yeartext/background change is a bit tricky at the moment. I will look into how it can be isolated more. Thanks for the valuable feedback!

**Comment by Chipperchap** [comment]
In the meantime you could create a separate account that is ASL specific. For example, as I assist a number of congregations I have several accounts attached to M<sup>3</sup>. Any changes I make in one account do not affect other accounts. These accounts are selected at startup.

(<img src="https://simonsheena-gmail.tinytake.com/media/136d9cf?filename=1665872505237_M3+Congregations_638014693038153892.png&sub_type=thumbnail_preview&type=attachment&width=725&height=393" title="Powered by TinyTake Screen Capture"/><br><a href="https://www.tinytake.com">Powered by TinyTake Screen Capture</a>) 

In the ASL one you would unselect the option to show the yeartext - it would just give you a blank screen until the display is stopped. 

[<img src="https://simonsheena-gmail.tinytake.com/media/136d9d0?filename=1665872693901_2_638014694925315521.png&sub_type=thumbnail_preview&type=attachment&width=706&height=464" title="Powered by TinyTake Screen Capture"/><br><a href="https://www.tinytake.com">Powered by TinyTake Screen Capture</a>](url)

**Comment by mvpapen** [comment]
I could create 2 user accounts!. one for hearing and one for ASL? So I can
change the year text to black!
Would that work

**Comment by Chipperchap** [comment]
Absolutely!

We have two accounts at our K-Hall. Each account has its preferences as determined by their separate BOE's and what the needs of each congregation are.

**Comment by Chipperchap** [comment]
@mvpapen ...Just curious, how do you play your ASL media? Through the JWLSL app?

**Comment by mvpapen** [comment]
Great, thanks!

**Comment by mvpapen** [comment]
media language : american Singlanguage

**Comment by mvpapen** [comment]
so to be clear , after you played media for ASL  it eoukd need to back to
last selected source,  mostly camera

**Comment by mtdvlpr** [comment]
Alright. I think it's clear for me. While we're at it. I was thinking about improving the shuffle music feature to show kingdom song videos for sign language (currently it plays sound only). Would this be something that you're interested in? It requires some extra effort on my part, but if you would definitely use this feature I'm for sure going to implement it.

**Comment by mtdvlpr** [comment]
Hi @mvpapen, I have just released a new version which implements your requested features:
- Possibility to change the shortcuts used (Alt+Z, Alt+D, Alt+K).
- Option to automatically hide the yeartext after media has finished playing (under media setup)
- Making the custom background for the media window congregation specific

While testing for AML, I also found a bug when using the provided markers, which is fixed now (using the markers, the video wouldn't stop in time). 

Let me know what you think of it and if there are any points of improvement!

**Comment by mvpapen** [comment]
Awesome, thanks!

**Comment by mtdvlpr** [comment]
@mvpapen, when you're satisfied with the solution, you can go ahead and close this issue :)

**Comment by mvpapen** [comment]
Tested  all function and it works great. I will have ASL test it in depth. 
![Screenshot_20221017_043803](https://user-images.githubusercontent.com/105513626/196303155-faabc623-16d4-467f-8ee5-a939b95daa84.png)
This function is great for ASL.

**Comment by mvpapen** [comment]
the shuffle asl music with video would be nice.
why is there no sound with the regular ASL meeting songs? does it have no audio??

**Comment by mtdvlpr** [comment]
Sign language songs have no audio indeed

**Comment by mvpapen** [comment]
Thanks!
