### ISSUE TITLE
[BUG] Congregation synced settings are only applied after an app restart

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#493]
**Describe the bug**
Congregation synced settings are only applied after an app restart, instead of immediately

**To Reproduce**

1. Fresh app install
2. Don't configure anything, just enter info for congregation sync
3. Settings get loaded but aren't actually applied anywhere
4. Restart app: settings are now there as per congregation sync

**Expected behavior**
Congregation synced settings should be applied immediately when they are loaded and visible in the UI

**Comment by mtdvlpr** [comment]
Yup, the various settings components need a listener to update when forcedPrefs are changed
