### ISSUE TITLE
[BUG] Path field is not highlighted as required when empty

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#494]
**Describe the bug**
Path field is not highlighted as required when empty

**To Reproduce**

1. Open app when path field is not set
2. Settings open, but path field is not highlighted

**Expected behavior**
Path field should be highlighted as required when empty

**Screenshots**

![image](https://user-images.githubusercontent.com/1275666/197571587-27eee795-f0e2-406f-89e8-c2f081f24a9b.png)

**Comment by mtdvlpr** [comment]
Hmm, seems to be impacting every regular textfield and what's weird is that it does work when running in development (after clearing everything).
