### ISSUE TITLE
[BUG] .current-media-item never gets triggered

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#514]
**Describe the bug**
The `current-media-item` class never gets triggered for currently playing media items. They only ever have the `media-played` class, both during and after playback.

**To Reproduce**

1. Play media
2. Left border is always blue, never orange
3. 
**Expected behavior**
Media should have the `media-played` class while it is being played.

**Screenshots**

Expectation:

![image](https://user-images.githubusercontent.com/1275666/197858212-69d6cd7b-361b-4fea-8808-e376f810fbaf.png)

Reality:

![image](https://user-images.githubusercontent.com/1275666/197858341-59c1fbb9-926f-4573-a8be-92dc12d4fc7e.png)

**Comment by mtdvlpr** [comment]
The current media class is only used when using the keyboard shortcuts to play media

**Comment by mtdvlpr** [comment]
Solved in https://github.com/sircharlo/meeting-media-manager/pull/515/commits/fe8cd39b7e8b6aba198db90d29009bf268a8688c

**Comment by sircharlo** [comment]
If the indicator supposed to go blue when the media is stopped? for the moment it stays orange until other media is played, but that might just be what you'd intended

**Comment by mtdvlpr** [comment]
That's indeed what I intended. Especially when using the keyboard shortcuts. You have to always be able to see where you were. Otherwise you don't know where the previous/next will go
