### ISSUE TITLE
[BUG] Migration of user prefs failed

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#516]
**Describe the bug**
For one user (so far), the migration of user preferences failed, which probably caused him to lose all preferences.

**To Reproduce**

Test out different configurations of "old" prefs.json files until one breaks.

**Expected behavior**
The preferences should correctly be converted to the new pref structure.

**Logs**
```
Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. TypeError: Use `delete()` to clear values
```

**System specs (please complete the following information):**

- OS: Windows 10
- App Version 22.9.0

**Additional context**
See details on Sentry

**Comment by mtdvlpr** [comment]
I haven't been able to find the culprit yet. Maybe if we try together we'll find it and tackle it before the next release, so that this doesn't happen again. It's pretty high priority since we don't want people losing their preferences right before a meeting.

**Comment by mtdvlpr** [comment]
The most likely prefs are those that are numbers, since some are converted from string to number or the other way around.

**Comment by mtdvlpr** [comment]
Then, cong and obs prefs, because their names have been altered.

**Comment by mtdvlpr** [comment]
What I've done now is add some extra checks. If any of those checks fail the default value will be used for a specific pref. See https://github.com/sircharlo/meeting-media-manager/pull/517/commits/35ee953f390945b87106302d1012ee7f9ede3fff

**Comment by mtdvlpr** [comment]
I also now put the entire migration in a try catch, because currently if it fails, you are not able to open your congregation.

**Comment by mtdvlpr** [comment]
Since did is a big issue if encountered, I suggest rolling out v22.10.0 now. I've gone through all sentry issues (mostly obs not connected errors that occur when obs has not been started).

**Comment by sircharlo** [comment]
> I added even more checks and also now put the entire migration in a try catch, because currently if it fails, you are not able to open your congregation. See [deefa9d](https://github.com/sircharlo/meeting-media-manager/commit/deefa9d6b97ce2d7a6852ab944dfb78f2f97f5b0)

That's a good idea; a failed migration is inconvenient, but it shouldn't cause the profile to not load. It should just pop up the settings and force the use to reconfigure them. Inconvenient, but not life-or-death.

**Comment by sircharlo** [comment]
> Since this is a big issue if encountered, I suggest rolling out v22.10.0 now. I've gone through all sentry issues (mostly obs not connected errors that occur when obs has not been started).

Definitely.

**Comment by mtdvlpr** [comment]
See [CONTRIBUTING.md](https://github.com/sircharlo/meeting-media-manager/blob/master/CONTRIBUTING.md#release-procedure) for explicit instructions how

**Comment by sircharlo** [comment]
Okidoke!
