### ISSUE TITLE
Congregation Sync Not Working

### ISSUE THREAD

**Issue by advenimus** [sircharlo/meeting-media-manager#545]
### Describe the bug
The issue seems to be across all devices we use. Since update to 22.10.1 the sync does not work. We see the files go into the webdav disk but are not grabbed in next sync even on originating device. 

### To Reproduce
Just upload custom media then sync. Doesn't work.
- Darwin 22.1.0
- M³ v22.10.1

### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": true,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": false,
    "autoStartSync": false,
    "congregationName": "Brighton",
    "disableHardwareAcceleration": false,
    "localAppLang": "en",
    "localOutputPath": "***",
    "obs": {
      "enable": false,
      "port": "***",
      "password": "***",
      "mediaScene": "Window Capture",
      "cameraScene": "Stage View",
      "useV4": true
    },
    "offline": false,
    "outputFolderDateFormat": "YYYY-MM-DD - dddd",
    "theme": "system"
  },
  "cong": {
    "server": "***",
    "port": "***",
    "user": "***",
    "password": "***",
    "dir": "***"
  },
  "media": {
    "enableMediaDisplayButton": true,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableVlcPlaylistCreation": false,
    "excludeLffi": true,
    "excludeLffiImages": false,
    "excludeTh": false,
    "hideMediaLogo": true,
    "hideWinAfterMedia": false,
    "keepOriginalsAfterConversion": false,
    "lang": "E",
    "langUpdatedLast": "2022-10-30T00:16:39.635Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": null,
    "ppForward": null,
    "preferredOutput": "window",
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "enableMusicButton": true,
    "enableMusicFadeOut": true,
    "musicFadeOutTime": 15,
    "musicFadeOutType": "smart",
    "musicVolume": 28,
    "mwDay": 2,
    "mwStartTime": "19:30",
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 6,
    "weStartTime": "09:30"
  },
  "__internal__": {
    "migrations": {
      "version": "22.10.1"
    }
  }
}
```

### Full error log
```
{}
```

**Comment by advenimus** [comment]
Seems to be related to cPanel based web disks. Works with koofr and 4shared.

**Comment by mtdvlpr** [comment]
Hmm, I will look into it! There was also a similar issue with 4shared (which turned out to be on their end) for which I wrote a work around. Might be the same issue here.

**Comment by mtdvlpr** [comment]
What do I need to set up a similar webdav server to test against?

**Comment by mtdvlpr** [comment]
That would be great!

**Comment by mtdvlpr** [comment]
Hi @advenimus, so I fixed the issue. It's similar to 4shared as in it doesn't work correctly when using `Depth: Infinity` to get all subfiles and subdirectory for a specific path (your configured server dir). In your case it would give no results when using Depth: Inifity, so instead I revert back to the old way which is for each folder only retrieve its direct children and do that for each level.

**Comment by mtdvlpr** [comment]
If this is not configurable by you, you could let your server provider know that this issue occurs.
