### ISSUE TITLE
Media Scene not selectable in scene picker in media presentation mode

### ISSUE THREAD

**Issue by wifilogo** [sircharlo/meeting-media-manager#561]
**Describe the bug**
I selected my _MONITOR_ scene **in M3 22.10.1 settings** for OBS Studio (28.0.3 websocket v5) 
When i want to select this scene, i don't see in ListBox.
If i change my _Media window scene in OBS Studio_ to _UVC Cam_, then i see _MONITOR_ scene but no _UVC Cam_

I send screenshots.

Thanks!

**Screenshots**

![M3_OBS](https://user-images.githubusercontent.com/11198837/198977060-22dfc86b-56e0-46d5-8b24-edfbc3637d62.jpg)

![M3_ListBox](https://user-images.githubusercontent.com/11198837/198977112-9b0082c8-1d76-4922-856c-754f9566d99f.jpg)

![OBS_Version](https://user-images.githubusercontent.com/11198837/198977172-21e9cb8c-a813-4b25-b559-a4c1ab19cabb.jpg)

**System specs (please complete the following information):**

- OS: [e.g. Windows 10]
- App Version [e.g. 22.10.1]

**Comment by mtdvlpr** [comment]
Yes, this is intended behaviour. The selected media scene is automatically used whenever you play media. You're not supposed to select your media scene yourself.

**Comment by wifilogo** [comment]
I'm sorry!
You are Great!

**Comment by mtdvlpr** [comment]
No problem! Could you look at my comment in your other issue: https://github.com/sircharlo/meeting-media-manager/issues/546

**Comment by wifilogo** [comment]
> No problem! Could you look at my comment in your other issue? [#546 (comment)](https://github.com/sircharlo/meeting-media-manager/issues/546#issuecomment-1296138731)

How can i test for Disable Auto Updates?
I execute in Visual Studio Code `yarn run win-dev`

I must be doing something wrong :(
I deactivate the updates, upload the version, and it always shows a notice that it has been updated.

![M3_AU1](https://user-images.githubusercontent.com/11198837/199094110-52000638-f3a0-4403-91e1-0b48be485d7d.jpg)

![M3_AU2](https://user-images.githubusercontent.com/11198837/199094156-45dbbe3d-bee9-46e9-a938-239cf029202c.jpg)

**Comment by mtdvlpr** [comment]
First set your package.json version to an old one. Then you can run `yarn win-build`. This will generate an .exe file in the build folder. If you install that, turn auto update off and restart it. It should still be the same older version.

**Comment by mtdvlpr** [comment]
You get that message everytime the version changes. The last ran version is stored in a file. So if you change it, it will see a change and give the notification.
