### ISSUE TITLE
[BUG] Media screen on second display not full screen by default.

### ISSUE THREAD

**Issue by SquareCircle99** [sircharlo/meeting-media-manager#589]
**Describe the bug**
After updating M3, the media window shows up on the correct display as usual, but as a floating, resizable window rather than going fullscreen by default as it used to on previous releases.

**To Reproduce**
Update M3 to the latest release (22.10.1) and launch it on macOS.

**Expected behavior**
For the media window in the secondary display to be in full screen.

**Logs**
I'm not sure I'm doing this step correctly. When I pressed the keys as directed when the app started up the console tab showed nothing. When I pressed them with the app running, it seems to list the downloaded media
![Screenshot 2022-11-02 at 2 49 12 PM](https://user-images.githubusercontent.com/111548982/199600055-a976338f-d0a8-4fac-b8c6-98f008212bf1.png)

**Screenshots**
Main screen
![Screenshot 2022-11-02 at 2 44 21 PM](https://user-images.githubusercontent.com/111548982/199599003-5241f9bf-5240-4b07-83a5-5cbd662be719.png)
Second screen
![Screenshot 2022-11-02 at 2 44 21 PM (2)](https://user-images.githubusercontent.com/111548982/199599061-b3ffbdc4-fa80-45cc-979a-c410fecfb94e.png)

**System specs (please complete the following information):**

- OS: macOS Ventura 13.0. Apple M1 SoC.
- App Version 22.10.1

**Additional context**
We updated from 22.8.1, with which there were no issues.

**Comment by mtdvlpr** [comment]
Could you check your settings and select the 2nd screen in the dropdown under media setup?

**Comment by SquareCircle99** [comment]
It is indeed selected! I even selected the other option (floating window) and then went back to Screen 2.

**Comment by mtdvlpr** [comment]
Hmm. This is a tricky one, since I don't have a macOS device to test on.

**Comment by SquareCircle99** [comment]
No worries! I have rolled it back to 22.8.1 for the time being. Do let me know if you need me to test or do anything on my end.

**Comment by mtdvlpr** [comment]
Could you try out [this version](https://drive.google.com/file/d/1EJpJa54C2RV6WAhMaPXg7UFlnUq2vvsy/view?usp=sharing)?

**Comment by sircharlo** [comment]
@mtdvlpr I'd be curious to see the values of `windowOptions` from `index.js` and of `setMediaWindowPosition`'s arguments from `util.js`

**Comment by mtdvlpr** [comment]
@sircharlo, same! My first instincts were the rounded corner that was added again, but I will add some debug statements next.

**Comment by SquareCircle99** [comment]
> Could you try out [this version](https://drive.google.com/file/d/1EJpJa54C2RV6WAhMaPXg7UFlnUq2vvsy/view?usp=sharing)?

I just tried it and it worked! Media on second display is now fullscreen.

**Comment by mtdvlpr** [comment]
Nice! I made two changes that potentially fixed it. I will now revert one of those changes to pinpoint which was the fix.

**Comment by mtdvlpr** [comment]
Could you please try [this version](https://drive.google.com/file/d/15q8P7ePTsAnuiHHl5adO1WwGufSp84cY/view?usp=share_link) as well?

**Comment by SquareCircle99** [comment]
> Could you please try [this version](https://drive.google.com/file/d/15q8P7ePTsAnuiHHl5adO1WwGufSp84cY/view?usp=share_link) as well? It also comes with some debug statements, so if you could look at your console and tell me what you see when you open the settings, that would be great!

Sure. I tried this other version and it brought back the problem with the media window.
Here's the console:
![Screenshot 2022-11-03 at 6 20 07 PM](https://user-images.githubusercontent.com/111548982/199859230-bf3150a1-d5a6-468a-82ca-46b07975166a.png)

**Comment by mtdvlpr** [comment]
Alright. Thanks! It definitely has to do with removing the rounded corners of the media window. I will revert again until this is fixed.
