### ISSUE TITLE
[BUG] Application is offline message

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#642]
**Describe the bug**
When starting the application, this message appears.

**Screenshots**
![BUG](https://user-images.githubusercontent.com/76891864/200358092-2aa1bfbc-75f3-452f-9777-1c0646d03e4b.png)

**System specs (please complete the following information):**

- OS: [e.g. Windows 10]
- App Version [e.g. 22.11.0]

**Comment by mtdvlpr** [comment]
Yeah, I noticed this as well. It's because the application doesn't have access to the internet yet, but as soon as the application does, the notification will remove itself.

**Comment by mtdvlpr** [comment]
I suppose it could be move to mounted() instead of beforemount(). It should be called early one to prevent issue when using getLocalJWLangs.

**Comment by mtdvlpr** [comment]
Does moving it to mounted() also solve the issue?

**Comment by sircharlo** [comment]
Not sure I get the difference between `getLocalJWLangs `and `getJWLangs`.

`getJWLangs` gets the latest version of the langs if the current version doesn't exist or is older than 3 months, saves it to file, and returns with the langs.

`getLocalJWLangs` gets the latest version of the langs that is saved to disk, and returns with the langs.

Why do we need `getLocalJWLangs` at all?

**Comment by mtdvlpr** [comment]
It's a synchronous version. When used in a computed property you can't use async functions.

**Comment by mtdvlpr** [comment]
But what we could do is save the entire lang object in the store, so we don't need the synchronous call  anymore. That's probably cleaner anyway.

**Comment by mtdvlpr** [comment]
@joaochrisz fixed in #650

**Comment by mtdvlpr** [comment]
Hmm, because it is quite small and no one has mentioned it before, I didn't bother looking into a solution. I will look into it now!
