### ISSUE TITLE
Alternative for mouse wheel to zoom images

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#643]
> The feature has been merged and will be in the next release :). It's a bit of a discover yourself feature as there is no clear explanation. When you hover over the image preview. When the image is active, you can use your mouse wheel to zoom in and then drag the image to highlight the part of the image you want. The preview image will show the same view as the media window.

I couldn't get it to work. In fact, my mouse wheel broke 😂

It would be interesting for you to activate this feature in another way, in cases where we do not have the mouse wheel.

_Originally posted by @joaochris in https://github.com/sircharlo/meeting-media-manager/discussions/413#discussioncomment-4078076_

**Comment by wifilogo** [comment]
Wow!
Works fine with mouse.
Great!

**Comment by mtdvlpr** [comment]
@joaochris, added in #648
