### ISSUE TITLE
[BUG] Renaming a file sometimes returns a 404 from the cong server

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#682]
**Describe the bug**
When renaming a file in the manage media screen, a 404 error is often thrown.

**To Reproduce**

1. Go to 'a specific day'
2. Click on 'rename file'
3. Do 'Rename a file'

**Expected behavior**

**Logs**
See Sentry for logs

**System specs (please complete the following information):**

- OS: [e.g. Windows 10]
- App Version [e.g. 22.11.0]

**Additional context**
See Sentry for more details

**Comment by sircharlo** [comment]
Hmm. I can't reproduce this, try as I might. Odd.

**Comment by mtdvlpr** [comment]
Yeah, I have the same issue. That's what makes this so difficult to tackle. There is something wrong though, since multiple users are experiencing this at times.

**Comment by sircharlo** [comment]
Hmm. Check my comment in Sentry.

**Comment by mtdvlpr** [comment]
@sircharlo, I'm closing this issue until it appears again in the latest release...

**Comment by mtdvlpr** [comment]
Unfortunately, the issues remains...

**Comment by mtdvlpr** [comment]
I think we need an actual user to experience this and report their findings before being able to solve it...

**Comment by sircharlo** [comment]
> I think we need an actual user to experience this and report their findings before being able to solve it...

You're probably right; it's definitely an intermittent issue at worst.

**Comment by mtdvlpr** [comment]
Definitely, otherwise it would've been reported already
