### ISSUE TITLE
[Feature Request] Secondary media language as fallback

### ISSUE THREAD

**Issue by Stephensce** [sircharlo/meeting-media-manager#816]
### Full error log
```
{
  "1670174954341": [
    "No WE meeting data found for 2022-12-04!"
  ]
}
```
### Error details
```
{
  "stack": "Error: No WE meeting data found for 2022-12-04!\n    at f.<anonymous> (app://./_nuxt/b10be0e.js:1:267052)\n    at async f.getWeMedia (app://./_nuxt/eaf35a3.js:1:7273)\n    at async Promise.allSettled (index 1)\n    at async f.startMediaSync (app://./_nuxt/eaf35a3.js:1:9171)\n    at async f.execute (app://./_nuxt/eaf35a3.js:1:4342)",
  "message": "No WE meeting data found for 2022-12-04!",
  "__sentry_captured__": true
}
```

**Comment by mtdvlpr** [comment]
It seems the Study Edition of The Watchtower is not available in Irish. Or am I mistaken?

**Comment by mtdvlpr** [comment]
There are only questions if I look here:
https://www.jw.org/en/library/magazines/?contentLanguageFilter=ga&pubFilter=w&yearFilter=

**Comment by Stephensce** [comment]
Hi
Thank you for your reply. So the question I was going to ask is, about an
unusual situation as we do a hybrid meeting in both English and Irish. The
items the publications and videos are getting more available in Irish but
until then we have to use both languages to fill the gaps if you know what
I mean, so we were wondering is it possible to pull down the media for each
meeting in both English & Irish? I noticed thet M3 will display the year
text in Irish on the 2nd screen which is fantastic, if we could pull
media/Videos and songs for each meeting in both languages while using the
Irish profile & years text that would be amazing.
Thanks so much for your work so far on the app.
It is a very useful tool.

Kind Regards
Stephen.

**Comment by mtdvlpr** [comment]
That is definitely an interesting request! I believe there is no media (Watchtower  meeting workbook or kingdom song videos) yet in Irish, so implementing this would currently only allow you to have English media with an Irish yeartext. Am I correct?

**Comment by Stephensce** [comment]
Yes it's unusual but the brothers are working hard on getting more
translated, For the Wt we read the paragraphs in English, ask the
questions in Irish & translate our answesr which we give as much as
possible in Irish.The full watchtower study is not available in Irish, a
good number of the videos on the website are now available in Irish, the
first call and return visits videos are available. There are now
around 55 irish songs translated with the lyrics available,the Congregation
Book study (Enjoy Life Forever) is available in irish but not all the the
videos in the book are translated into to Irish but a good number are.

Thanks
Regards Stephen.

**Comment by mtdvlpr** [comment]
I can definitely see a secondary language option being useful in such a scenario. I will see what I can do :)

**Comment by Stephensce** [comment]
Thanks once again for all your work on this.

Regards Stephen.

**Comment by mtdvlpr** [comment]
Great news! I have an initial setup for you to test. It's available [here](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9)

**Comment by Stephensce** [comment]
Thanks so much, that works very well and will save so much time .

I really appreciate your hard work. It will benefit the congregation very
much.

Kind regards
Stephen .

**Comment by mtdvlpr** [comment]
@Stephensce, we have finalized this feature in #817 and it will be in the next release. There were some issues in the version I gave to you to test, but you will probably not encounter them. As soon as a new version has been released, make sure your version is also updated. If not, manually uninstall the test version and install the latest version.

**Comment by Stephensce** [comment]
Great, thanks for the update!
