### ISSUE TITLE
[Enhancement] choose which jwpub images to add

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#839]
When using a jwpub file to add images to a certain date, whether it be from a public talk or a lesson in the Enjoy life forever book, once you select the public talk or lesson, you are forced to add all images/videos that are in that public talk or lesson.

It would be nice if you could remove some of those images/videos before pressing save. This saves time  because those files won't have to be uploaded to the congregation server to be removed right after again.

This could be extended to the scenario when you try to upload multiple files at once, but change your mind about one of them. Instead of having to cancel the whole process, you could just cancel that one file

**Comment by mtdvlpr** [comment]
@sircharlo, thoughts?

**Comment by sircharlo** [comment]
> @sircharlo, thoughts?

Love love love it
