### ISSUE TITLE
[BUG] Powerfolder getDirectoryContent fails

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#891]
**Describe the bug**
The get directory contents fails for powerfolder servers, because it returns a 200 status instead of the normal webdav 207 status.

**To Reproduce**

1. Go to 'Settings'
2. Connect to a PowerFolder server
3. Do 'open specific day'

**Expected behavior**
The powerfolder server should work and its content should correctly be fetched.

**Logs**
See Sentry

**System specs (please complete the following information):**
See Sentry

**Additional context**
A possible fix might be to return to the old way of getting the directory contents  (one layer at a time). This method is already in use for 4shared, because of a bug in 4shared where getting all layers at once returns the wrong locations. We could easily add PowerFolder to the array of servers that need to use the old method.

**Comment by mtdvlpr** [comment]
@sirhcarlo, do you have a PowerFolder server ready to test against? If not, I'll just create one of my own.

**Comment by sircharlo** [comment]
Sure, I'll test that this pm

**Comment by sircharlo** [comment]
No issues for me, oddly:

![image](https://user-images.githubusercontent.com/1275666/208735838-49fbe7fb-c707-43b5-b26f-c338f953927e.png)

**Comment by mtdvlpr** [comment]
And in the settings screen. Do you see a correct file tree for your server?

**Comment by sircharlo** [comment]
> And in the settings screen. Do you see a correct file tree for your server?

![image](https://user-images.githubusercontent.com/1275666/208740624-4d59ade6-d87b-40e4-92ea-2efdc04bfe8d.png)

Yep (albeit incorrectly sorted!)

**Comment by mtdvlpr** [comment]
Alright, then I guess the Sentry issue is a one-off

**Comment by sircharlo** [comment]
I'll add the sort to the files and dirs.

**Comment by mtdvlpr** [comment]
I'll close this then, until an actual PowerFolder user reports a problem with it.

**Comment by sircharlo** [comment]
To be honest, I'm not sure how many users actually use the congregation sync feature anyways!
