### ISSUE TITLE
[Enhancement] Make the tooltip persistent for "click again to confirm" tooltips

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#892]
**Describe the feature**
When a user clicks on something that requires a second click (like stopping a video, clearing the cache, or starting the background music), the tooltip shows up to indicate to click again. However, if the user's mouse moves away from the button, the tooltip disappears, making it hard for the user to realize what is happening, or what they need to do.

**How would this feature work?**
It would be nice if the tooltip could persist until the button goes back to its 'unclicked' state.

**Who would benefit from it?**
Everyone who clicks on things and moves the mouse fast without reading, like me.

**Additional context**
I tried to play around with the shuffle button to make the `v-tooltip` persistent using `v-model` as per the [docs](https://vuetifyjs.com/en/components/tooltips/#visibility), but I couldn't get `v-model` to play along with the `v-if`. I must be missing something. I [got around it](https://github.com/sircharlo/meeting-media-manager/commit/168d9b45e687222d7d67a2f2f8e60f2c77c772c7) using [`close-delay`](https://vuetifyjs.com/en/api/v-tooltip/#props-close-delay), but maybe that's not the best way...

**Comment by mtdvlpr** [comment]
@sircharlo, see #893 :)

**Comment by sircharlo** [comment]
> @sircharlo, if you look at mine (#879), I'll look at yours :)

Sorry, I had to leave quickly! 😆 I'll take a look for sure 😉
