### ISSUE TITLE
[BUG] time and progress freeze during video

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#896]
**Describe the bug**
I experienced a really strange bug. While playing the governing body upate nr 8 the time and progress bar froze at 6 minutes and x seconds. I heard from another brother for whom the same video froze at 1 minute and x seconds.

**To Reproduce**

1. Go to 'manage media'
2. Add update nr 8
3. Play the video
4. See error (maybe?)

**Expected behavior**
The time and progress should continue to increase until the video ends

**System specs (please complete the following information):**

- OS: Windows 10
- App Version 22.12.1

**Additional context**
It's very odd. There's no error in the console of thr main window. Maybe in the media window (couldn't check during the meeting).

**Comment by sircharlo** [comment]
Did the video stutter or glitch? Or did it end normally?

**Comment by mtdvlpr** [comment]
The video played and ended correctly

**Comment by sircharlo** [comment]
Hm. Interesting. I noticed (perhaps unrelated) that it takes one or a few seconds to send the "time left" to the button for background music when going from the main page to the media controller page.

**Comment by sircharlo** [comment]
No luck in trying to get the video time elapsed to freeze even while stress-testing my GPU and CPU..

**Comment by sircharlo** [comment]
Same while running with Electron processes on low priority and battery saver on.

**Comment by mtdvlpr** [comment]
I'm going to try to reproduce the error at home too, but since both occurences had a completely different time when it froze, I don't think it will be easy.

**Comment by mtdvlpr** [comment]
I did encounter some sentry issues a while back which might be related. The media window could not find the video anymore when using the queryselectoe video and that crashed the time update method among other methods. Since then I check if the video is found to prevent the error. So it might be that the video can't be found for some reason after a yet to be determined situation takes place...

**Comment by mtdvlpr** [comment]
Never mind. That was for video scrubbing: 
https://github.com/sircharlo/meeting-media-manager/blob/master/src/renderer/pages/media.vue#L140-L145

**Comment by sircharlo** [comment]
In any case, maybe it would be a good idea to change [this part](https://github.com/sircharlo/meeting-media-manager/blob/c6013e8df3e3fe9a7cd035abf533a33c7d36889a/src/renderer/pages/media.vue#L271-L276) of the code to something less intensive, similar to what is mentioned [here](https://stackoverflow.com/questions/4460263/disabling-the-long-running-script-message-in-internet-explorer/31390750#31390750). I'll test some things out.

**Comment by sircharlo** [comment]
No significant drop in CPU/GPU usage. On my setup, `ontimeupdate `is called about 4-5 times per second. Nothing too major.

**Comment by mtdvlpr** [comment]
Still, I think it's worthwhile to prevent 3-4 calls per second. I could see so many calls in a short timeframe cause issues either with Electron or Vue itself.

**Comment by sircharlo** [comment]
> Still, I think it's worthwhile to prevent 3-4 calls per second. I could see so many calls in a short timeframe cause issues either with Electron or Vue itself.

A few ways that I see we could go about it. 

- Use `ontimeupdate` to check if X number of milliseconds has gone by, and if so send the current time update to the media controller. 
- Use `onplay` to start a looping `settimeout` that will send the current time update to the media controller every X milliseconds, and `onpause` and `onstop` to cancel the timeout
- From the media controller, request the current time from the media window every X milliseconds as long as the stop button is visible on a video line

Thoughts?

**Comment by mtdvlpr** [comment]
I like the settimeout option
