### ISSUE TITLE
[DOCS] Make it easier to translate

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#899]
The documentation website supports translation, but it should be easier. Some pages have been optimized to be translated easily, but the following still need to be optimized:
- [x] configuration
- [x] congregation-sync
- [x] manage-media
- [x] present-media

The problem with some of these pages, is the fact that a quote-block is used inside a table. That is possible in html, but not in markdown. The information will have to be presented differently in order to make it a markdown page which is much easier to translate.

**Comment by sircharlo** [comment]
@joaochris Would you like to help out with this? I remember you mentioning that you would like to contribute if I recall correctly 😄

**Comment by joaochris** [comment]
@sircharlo How do I do that?

**Comment by mtdvlpr** [comment]
@joaochris, so I have converted the English manage-media and present-media pages into markdown files. I have already converted most manage-media pages as well and only the Spanish present-media page. What works best is to open the documentation website in the language that you're converting. Copy paste the English markdown file to the markdown file you're converting and copy paste all content from the documentation site to the markdown file. You'll need to add some markdown specific things to it (which are already done in the English markdown), like ** for bold and _ for italic.

**Comment by mtdvlpr** [comment]
If you look at #907, you can see what I did so far

**Comment by mtdvlpr** [comment]
If it makes sense to you and are willing to help me with this, let me know and we'll divide the work. I still have to the manage-media page for sv and wes-x-pgw

**Comment by joaochris** [comment]
@mtdvlpr Sorry for my slow mind. I still don't understand what needs to be done 😅

**Comment by mtdvlpr** [comment]
To get familiar with the syntax, just open one of those md files and open the corresponding section on the documentation website and compare the two

**Comment by joaochris** [comment]
Got it, are you going to add these two missing ones in English?

**Comment by mtdvlpr** [comment]
@joaochris, i have just added the congregation-sync one. I did English, Spanish (es) and Estonian (et).

**Comment by mtdvlpr** [comment]
The languages that have been translated and need to be converted are: Spanish (es), Estonian (et), Finnish (fi), Hungarian (hu), Italian (it), Dutch (nl), Portuguese Brazil (pt) and Swedish (sv)

**Comment by mtdvlpr** [comment]
Hi @joaochris, I found a much easier and quicker way to update migrate all pages. I just finished the configuration page (which is the most work) this way. Have you started working on the congregation-sync pages yet? If not, I can do the rest relatively fast.

**Comment by joaochris** [comment]
> Hi @joaochris, I found a much easier and quicker way to update migrate all pages. I just finished the configuration page (which is the most work) this way. Have you started working on the congregation-sync pages yet? If not, I can do the rest relatively fast, but if you want to do it, have at it :)

Hi! I was going to do the rest :)

**Comment by joaochris** [comment]
What faster way did you find? 😆

**Comment by mtdvlpr** [comment]
I copied the html from the documentation website and used the search function in VS Code to migrate all translations simultaneously. Replace <strong> with **, replace <p> with nothing, replace <h3> with ###, etc.

**Comment by mtdvlpr** [comment]
> Hi! I was going to do the rest :)

Thank you for your willing spirit!

**Comment by joaochris** [comment]
> I copied the html from the documentation website and used the search function in VS Code to migrate all translations simultaneously. Replace `\<strong\>` with `**`, replace `<p>` with nothing, replace `<h3>` with `###`, etc.

How long did it take you to make each one?

**Comment by mtdvlpr** [comment]
Hard to say. I didn't really pay attention to it. Guessing it took 15 min per page max

**Comment by joaochris** [comment]
> Hard to say. I didn't really pay attention to it. Guessing it took 15 min per page max

I thought it took longer to do it the way you said kkkk. Need to replace several things

**Comment by mtdvlpr** [comment]
@joaochris, that can be! It was useful for the configuration page, because that has a lot of complicated tables and content. So then the effort you put in at first saves enough effort down the road. But since congregation-sync does not have a lot of content, it might be faster and easier to do it one at a time.

**Comment by joaochris** [comment]
I think I'm done

**Comment by mtdvlpr** [comment]
@joaochris, yup. Thank you so much for your efforts!
