### ISSUE TITLE
[Feature]: Shared Media Cache

### ISSUE THREAD

**Issue by danielengels** [sircharlo/meeting-media-manager#990]
### Is your feature request related to a problem?

We share our hall with another assembly. Everyone has their own Windows account because we do different things with it. Unfortunately our internet connection is very bad. So downloading the media is quite time-consuming. So far, we have often brought the media with us from home.
Both assemblies now want to use the Meeting Media Manager. Is it somehow possible to share the media cache. Then one meeting would benefit from the media cache of the other meeting. 

### Describe the solution you'd like

It would be good to select the media cache folder to have it in one place where both windows users can use it? Maybe like the media folder for presenting the media

### Describe alternatives you've considered

Maybe we could use one windows user again - but there a some things we do different and no one, want to change settings from the other.

**Comment by mtdvlpr** [comment]
Hi @danielengels, I have not tried this myself yet, but have you tried installing M³ system-wide instead of only for the current user? I would imagine that the application (along with the cache) would be installed in a shared location.

**Comment by danielengels** [comment]
Hi @mtdvlpr,
I play a little arround - this option only change, where the software itself is installed. On Windows this changes from Program Files (system-wide) to %appdata%/local/programs (user installation). And you don't need admin rights, when you don't install system-wide but this depends on the installation path.

**Comment by mtdvlpr** [comment]
@danielengels, alright, thanks for trying. In that case we can definitely add an option to overwrite the default location for publication cache! Will keep you posted here.

**Comment by mtdvlpr** [comment]
Hi @danielengels, I have a version for you to test out. You can find it [here](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9?usp=sharing). You can set a custom cache location in the settings which will migrate the existing cache to the new location.

**Comment by danielengels** [comment]
Hi Manoah,
seems to work quiet well. But there are two things I don't know what happens.
1. The download is much faster, as they uses the same cache. But at the end of the new download each congregation have to download something. But it is still much much less then before. To reproduce: create two congregation (i do in the same user profile. Start downloading for the first congreagation. This takes a while. After closing and opening MMM with the other congregation u see that it don't need so long. But at "the end" (maybe it is not) it seems like there is something downloaded. After closeing and opening again and refreshing the media this download don't happens again.
2. In the settings there are the size of the cache. It is for every congregation different (and i am talking about >1GB) and more strange for me: I don't know how the size is caclulated and where the size should be located. Even after deleting the cache and downloading again it doesn't seems to be the right size.

But both points are not very impotant. It really reduces the download size very much! So thank's a lot for this!

**Comment by mtdvlpr** [comment]
Hi @danielengels, thanks for testing!

1. This could have multiple reasons: is the media path different? Are the meeting days different?
2. Cache consists of the cache of your language and the contents of your media path (the actual meeting media) snd the cached shuffle music.

**Comment by mtdvlpr** [comment]
Also, after pressing those keys, the console tab shows how much of the media was extracted fom cache and from internet.

**Comment by danielengels** [comment]
@mtdvlpr 
What is a cong server?
So i test now again! And the reason for different downloading or the additional download was the exclude toggles. On the first one I changed them and the other one uses the defaults. When I saw the download task I could see it.
So then I guess it is working.

**Comment by mtdvlpr** [comment]
@danielengels, I noticed in our logs that you're German. Would you be willing to help us complete the German translations? They've fallen a bit behind recently.

**Comment by danielengels** [comment]
Sure I  can do ;)

**Comment by mtdvlpr** [comment]
@danielengels, awesome! See the following instructions:

If any one of you would like to volunteer to become an M³ language moderator for a language you speak, please [sign in to GitLocalize](https://gitlocalize.com/) using your GitHub account, and then let us know by adding a comment in this chat.

**Comment by mtdvlpr** [comment]
More information about this role can be found at #722

**Comment by danielengels** [comment]
Try to translate everything that was not translated ;)

**Comment by mtdvlpr** [comment]
@danielengels, thanks so much!

**Comment by danielengels** [comment]
Sure I can do - but how I get information that there are new keys to translate? Or should I check from time to time? But maybe it is answered in #722 but I can't read it yet. But I will do later

**Comment by mtdvlpr** [comment]
@danielengels, apparently you don't get notified at the moment, but we might switch to a different translation platform soon (as discussed in #722) where you should get notified of new strings.
