### ISSUE TITLE
[Enhancement]: Explanation for specific use cases

### ISSUE THREAD

**Issue by fatmarker** [sircharlo/meeting-media-manager#991]
### What happened?

JPEGs are being converted to MP4 when the option is enabled.

### To Reproduce

1. Set up a new congregation (English media)
2. Enable convert videos to mp4
3. Generate a weekend meeting media folder

### What did you expect to happen?

Image files should not be converted.

### Version

v22.12.1

### What platform are you seeing the problem on?

MacOS

### Screenshots

<img width="711" alt="Screen Shot 2022-12-31 at 20 35 35" src="https://user-images.githubusercontent.com/4668417/210154064-589f8d4f-e4e3-4a43-b611-76ab9e4fa90b.png">

### Additional context

**EDIT**

A new user (like me) might be confused by the MP4 conversion feature. Provide help tips on this setting for additional explanation.

**Comment by mtdvlpr** [comment]
Hi @fatmarker, this is actually intended behaviour. The use case is for fully remote Zoom meetings where you can use the share mp4 video feature of Zoom to easily share media. By converting images to videos, you can use Zoom's feature for all media.

**Comment by fatmarker** [comment]
I see. Then let's change this to a UX improvement. As this is a very specific use case, an explanation of this setting could be included in a help tip.

**Comment by mtdvlpr** [comment]
Good suggestion! I'll see what I can do and keep you posted :)

**Comment by mtdvlpr** [comment]
Hi @fatmarker, I have a version of this feature for you to test. You can find it [here](https://drive.google.com/drive/folders/1_2CzKieYGaK3LcYrEwzNQgfTpNReOSx9?usp=sharing). I have added this explanation feature to the `convert media to MP4` setting. Please let me know what you think of it!

**Comment by fatmarker** [comment]
Perfect! 👌🏼
