### ISSUE TITLE
Can't get media from jan 2, 2023

### ISSUE THREAD

**Issue by Gemeente-Katwijk** [sircharlo/meeting-media-manager#992]
### What happened?

From 2 jan 2023 could not get media

### To Reproduce

3. Do '....'

### What did you expect to happen?

Get media for next week

### Version

V22.12.1

### What platform are you seeing the problem on?

Windows

### Screenshots

![image](https://user-images.githubusercontent.com/116264476/210169945-bf0174d0-c26a-4726-9f7b-36a47892cff6.png)

**Comment by mtdvlpr** [comment]
Hi @Gemeente-Katwijk, could you press `ctrl` + `shift` + `I` and show us what the console tab  shows? It should give you a more detailed error.

**Comment by Gemeente-Katwijk** [comment]
Hi Manoah,

 

Bedoel je dit?

 

Bedankt alvast voor je moeite..

Groetjes.

 



 

 

Van: Manoah Tervoort ***@***.***> 
Verzonden: zondag 1 januari 2023 13:21
Aan: sircharlo/meeting-media-manager ***@***.***>
CC: Gemeente-Katwijk ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [sircharlo/meeting-media-manager] Can't get media from jan 2, 2023 (Issue #992)

 

Hi @Gemeente-Katwijk <https://github.com/Gemeente-Katwijk> , could you press ctrl + shift + I and show us what the console tab shows? It should give you a more detailed error.

**Comment by mtdvlpr** [comment]
@Gemeente-Katwijk, ik zie nog niks. Alleen je bericht...

**Comment by Gemeente-Katwijk** [comment]
Neem me niet kwalijk.

Ik voeg hem in PDF bij.

Hopelijk zie je het nu wel..

 

Groetjes,

Rolf.

 

 

 

Van: Manoah Tervoort ***@***.***> 
Verzonden: zondag 1 januari 2023 13:34
Aan: sircharlo/meeting-media-manager ***@***.***>
CC: Gemeente-Katwijk ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [sircharlo/meeting-media-manager] Can't get media from jan 2, 2023 (Issue #992)

 

@Gemeente-Katwijk <https://github.com/Gemeente-Katwijk> , ik zie nog niks. Alleen je bericht...

**Comment by sircharlo** [comment]
Got it @mtdvlpr

**Comment by sircharlo** [comment]
Fixed [here](https://github.com/sircharlo/meeting-media-manager/commit/a942a17a1ede130379e5072ee33d8ec86013f982). Problem won't occur as of Monday (tomorrow) in any case, but this will be fixed for next time this happens (in 12 months).

**Comment by Gemeente-Katwijk** [comment]
Thanks a lot for this quick fix.
